/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewayListenerSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayListenerSpec{}

// GatewayListenerSpec Gateway listener configuration
type GatewayListenerSpec struct {
	// Port number
	Port *int32 `json:"port,omitempty"`
	// Virtual host for the listener
	Host *string `json:"host,omitempty"`
}

// NewGatewayListenerSpec instantiates a new GatewayListenerSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayListenerSpec() *GatewayListenerSpec {
	this := GatewayListenerSpec{}
	return &this
}

// NewGatewayListenerSpecWithDefaults instantiates a new GatewayListenerSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayListenerSpecWithDefaults() *GatewayListenerSpec {
	this := GatewayListenerSpec{}
	return &this
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *GatewayListenerSpec) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayListenerSpec) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *GatewayListenerSpec) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *GatewayListenerSpec) SetPort(v int32) {
	o.Port = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GatewayListenerSpec) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayListenerSpec) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GatewayListenerSpec) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GatewayListenerSpec) SetHost(v string) {
	o.Host = &v
}

func (o GatewayListenerSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayListenerSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	return toSerialize, nil
}

type NullableGatewayListenerSpec struct {
	value *GatewayListenerSpec
	isSet bool
}

func (v NullableGatewayListenerSpec) Get() *GatewayListenerSpec {
	return v.value
}

func (v *NullableGatewayListenerSpec) Set(val *GatewayListenerSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayListenerSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayListenerSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayListenerSpec(val *GatewayListenerSpec) *NullableGatewayListenerSpec {
	return &NullableGatewayListenerSpec{value: val, isSet: true}
}

func (v NullableGatewayListenerSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayListenerSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
