/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewayEndpointSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayEndpointSpec{}

// GatewayEndpointSpec Gateway resource endpoint configuration
type GatewayEndpointSpec struct {
	Http  *GatewayListenerSpec `json:"http,omitempty"`
	Https *GatewayListenerSpec `json:"https,omitempty"`
	Tls   *GatewayListenerSpec `json:"tls,omitempty"`
}

// NewGatewayEndpointSpec instantiates a new GatewayEndpointSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayEndpointSpec() *GatewayEndpointSpec {
	this := GatewayEndpointSpec{}
	return &this
}

// NewGatewayEndpointSpecWithDefaults instantiates a new GatewayEndpointSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayEndpointSpecWithDefaults() *GatewayEndpointSpec {
	this := GatewayEndpointSpec{}
	return &this
}

// GetHttp returns the Http field value if set, zero value otherwise.
func (o *GatewayEndpointSpec) GetHttp() GatewayListenerSpec {
	if o == nil || IsNil(o.Http) {
		var ret GatewayListenerSpec
		return ret
	}
	return *o.Http
}

// GetHttpOk returns a tuple with the Http field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayEndpointSpec) GetHttpOk() (*GatewayListenerSpec, bool) {
	if o == nil || IsNil(o.Http) {
		return nil, false
	}
	return o.Http, true
}

// HasHttp returns a boolean if a field has been set.
func (o *GatewayEndpointSpec) HasHttp() bool {
	if o != nil && !IsNil(o.Http) {
		return true
	}

	return false
}

// SetHttp gets a reference to the given GatewayListenerSpec and assigns it to the Http field.
func (o *GatewayEndpointSpec) SetHttp(v GatewayListenerSpec) {
	o.Http = &v
}

// GetHttps returns the Https field value if set, zero value otherwise.
func (o *GatewayEndpointSpec) GetHttps() GatewayListenerSpec {
	if o == nil || IsNil(o.Https) {
		var ret GatewayListenerSpec
		return ret
	}
	return *o.Https
}

// GetHttpsOk returns a tuple with the Https field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayEndpointSpec) GetHttpsOk() (*GatewayListenerSpec, bool) {
	if o == nil || IsNil(o.Https) {
		return nil, false
	}
	return o.Https, true
}

// HasHttps returns a boolean if a field has been set.
func (o *GatewayEndpointSpec) HasHttps() bool {
	if o != nil && !IsNil(o.Https) {
		return true
	}

	return false
}

// SetHttps gets a reference to the given GatewayListenerSpec and assigns it to the Https field.
func (o *GatewayEndpointSpec) SetHttps(v GatewayListenerSpec) {
	o.Https = &v
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *GatewayEndpointSpec) GetTls() GatewayListenerSpec {
	if o == nil || IsNil(o.Tls) {
		var ret GatewayListenerSpec
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayEndpointSpec) GetTlsOk() (*GatewayListenerSpec, bool) {
	if o == nil || IsNil(o.Tls) {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *GatewayEndpointSpec) HasTls() bool {
	if o != nil && !IsNil(o.Tls) {
		return true
	}

	return false
}

// SetTls gets a reference to the given GatewayListenerSpec and assigns it to the Tls field.
func (o *GatewayEndpointSpec) SetTls(v GatewayListenerSpec) {
	o.Tls = &v
}

func (o GatewayEndpointSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayEndpointSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Http) {
		toSerialize["http"] = o.Http
	}
	if !IsNil(o.Https) {
		toSerialize["https"] = o.Https
	}
	if !IsNil(o.Tls) {
		toSerialize["tls"] = o.Tls
	}
	return toSerialize, nil
}

type NullableGatewayEndpointSpec struct {
	value *GatewayEndpointSpec
	isSet bool
}

func (v NullableGatewayEndpointSpec) Get() *GatewayEndpointSpec {
	return v.value
}

func (v *NullableGatewayEndpointSpec) Set(val *GatewayEndpointSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayEndpointSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayEndpointSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayEndpointSpec(val *GatewayEndpointSpec) *NullableGatewayEndpointSpec {
	return &NullableGatewayEndpointSpec{value: val, isSet: true}
}

func (v NullableGatewayEndpointSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayEndpointSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
