/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the PromoteAgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromoteAgentResponse{}

// PromoteAgentResponse struct for PromoteAgentResponse
type PromoteAgentResponse struct {
	// Name of the promoted agent
	AgentName *string `json:"agentName,omitempty"`
	// Project containing the agent
	ProjectName *string `json:"projectName,omitempty"`
	// Source environment promoted from
	SourceEnvironment *string `json:"sourceEnvironment,omitempty"`
	// Target environment promoted to
	TargetEnvironment *string `json:"targetEnvironment,omitempty"`
}

// NewPromoteAgentResponse instantiates a new PromoteAgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromoteAgentResponse() *PromoteAgentResponse {
	this := PromoteAgentResponse{}
	return &this
}

// NewPromoteAgentResponseWithDefaults instantiates a new PromoteAgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromoteAgentResponseWithDefaults() *PromoteAgentResponse {
	this := PromoteAgentResponse{}
	return &this
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *PromoteAgentResponse) GetAgentName() string {
	if o == nil || IsNil(o.AgentName) {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentResponse) GetAgentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentName) {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *PromoteAgentResponse) HasAgentName() bool {
	if o != nil && !IsNil(o.AgentName) {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *PromoteAgentResponse) SetAgentName(v string) {
	o.AgentName = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *PromoteAgentResponse) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentResponse) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *PromoteAgentResponse) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *PromoteAgentResponse) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetSourceEnvironment returns the SourceEnvironment field value if set, zero value otherwise.
func (o *PromoteAgentResponse) GetSourceEnvironment() string {
	if o == nil || IsNil(o.SourceEnvironment) {
		var ret string
		return ret
	}
	return *o.SourceEnvironment
}

// GetSourceEnvironmentOk returns a tuple with the SourceEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentResponse) GetSourceEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.SourceEnvironment) {
		return nil, false
	}
	return o.SourceEnvironment, true
}

// HasSourceEnvironment returns a boolean if a field has been set.
func (o *PromoteAgentResponse) HasSourceEnvironment() bool {
	if o != nil && !IsNil(o.SourceEnvironment) {
		return true
	}

	return false
}

// SetSourceEnvironment gets a reference to the given string and assigns it to the SourceEnvironment field.
func (o *PromoteAgentResponse) SetSourceEnvironment(v string) {
	o.SourceEnvironment = &v
}

// GetTargetEnvironment returns the TargetEnvironment field value if set, zero value otherwise.
func (o *PromoteAgentResponse) GetTargetEnvironment() string {
	if o == nil || IsNil(o.TargetEnvironment) {
		var ret string
		return ret
	}
	return *o.TargetEnvironment
}

// GetTargetEnvironmentOk returns a tuple with the TargetEnvironment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteAgentResponse) GetTargetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.TargetEnvironment) {
		return nil, false
	}
	return o.TargetEnvironment, true
}

// HasTargetEnvironment returns a boolean if a field has been set.
func (o *PromoteAgentResponse) HasTargetEnvironment() bool {
	if o != nil && !IsNil(o.TargetEnvironment) {
		return true
	}

	return false
}

// SetTargetEnvironment gets a reference to the given string and assigns it to the TargetEnvironment field.
func (o *PromoteAgentResponse) SetTargetEnvironment(v string) {
	o.TargetEnvironment = &v
}

func (o PromoteAgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromoteAgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentName) {
		toSerialize["agentName"] = o.AgentName
	}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	if !IsNil(o.SourceEnvironment) {
		toSerialize["sourceEnvironment"] = o.SourceEnvironment
	}
	if !IsNil(o.TargetEnvironment) {
		toSerialize["targetEnvironment"] = o.TargetEnvironment
	}
	return toSerialize, nil
}

type NullablePromoteAgentResponse struct {
	value *PromoteAgentResponse
	isSet bool
}

func (v NullablePromoteAgentResponse) Get() *PromoteAgentResponse {
	return v.value
}

func (v *NullablePromoteAgentResponse) Set(val *PromoteAgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePromoteAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePromoteAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromoteAgentResponse(val *PromoteAgentResponse) *NullablePromoteAgentResponse {
	return &NullablePromoteAgentResponse{value: val, isSet: true}
}

func (v NullablePromoteAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromoteAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
