/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewaySpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewaySpec{}

// GatewaySpec Gateway configuration with ingress and egress network specs
type GatewaySpec struct {
	Ingress *GatewayNetworkSpec `json:"ingress,omitempty"`
	Egress  *GatewayNetworkSpec `json:"egress,omitempty"`
}

// NewGatewaySpec instantiates a new GatewaySpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewaySpec() *GatewaySpec {
	this := GatewaySpec{}
	return &this
}

// NewGatewaySpecWithDefaults instantiates a new GatewaySpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewaySpecWithDefaults() *GatewaySpec {
	this := GatewaySpec{}
	return &this
}

// GetIngress returns the Ingress field value if set, zero value otherwise.
func (o *GatewaySpec) GetIngress() GatewayNetworkSpec {
	if o == nil || IsNil(o.Ingress) {
		var ret GatewayNetworkSpec
		return ret
	}
	return *o.Ingress
}

// GetIngressOk returns a tuple with the Ingress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaySpec) GetIngressOk() (*GatewayNetworkSpec, bool) {
	if o == nil || IsNil(o.Ingress) {
		return nil, false
	}
	return o.Ingress, true
}

// HasIngress returns a boolean if a field has been set.
func (o *GatewaySpec) HasIngress() bool {
	if o != nil && !IsNil(o.Ingress) {
		return true
	}

	return false
}

// SetIngress gets a reference to the given GatewayNetworkSpec and assigns it to the Ingress field.
func (o *GatewaySpec) SetIngress(v GatewayNetworkSpec) {
	o.Ingress = &v
}

// GetEgress returns the Egress field value if set, zero value otherwise.
func (o *GatewaySpec) GetEgress() GatewayNetworkSpec {
	if o == nil || IsNil(o.Egress) {
		var ret GatewayNetworkSpec
		return ret
	}
	return *o.Egress
}

// GetEgressOk returns a tuple with the Egress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewaySpec) GetEgressOk() (*GatewayNetworkSpec, bool) {
	if o == nil || IsNil(o.Egress) {
		return nil, false
	}
	return o.Egress, true
}

// HasEgress returns a boolean if a field has been set.
func (o *GatewaySpec) HasEgress() bool {
	if o != nil && !IsNil(o.Egress) {
		return true
	}

	return false
}

// SetEgress gets a reference to the given GatewayNetworkSpec and assigns it to the Egress field.
func (o *GatewaySpec) SetEgress(v GatewayNetworkSpec) {
	o.Egress = &v
}

func (o GatewaySpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewaySpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ingress) {
		toSerialize["ingress"] = o.Ingress
	}
	if !IsNil(o.Egress) {
		toSerialize["egress"] = o.Egress
	}
	return toSerialize, nil
}

type NullableGatewaySpec struct {
	value *GatewaySpec
	isSet bool
}

func (v NullableGatewaySpec) Get() *GatewaySpec {
	return v.value
}

func (v *NullableGatewaySpec) Set(val *GatewaySpec) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewaySpec) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewaySpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewaySpec(val *GatewaySpec) *NullableGatewaySpec {
	return &NullableGatewaySpec{value: val, isSet: true}
}

func (v NullableGatewaySpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewaySpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
