/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewayNetworkSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayNetworkSpec{}

// GatewayNetworkSpec External and internal gateway endpoints
type GatewayNetworkSpec struct {
	External *GatewayEndpointSpec `json:"external,omitempty"`
	Internal *GatewayEndpointSpec `json:"internal,omitempty"`
}

// NewGatewayNetworkSpec instantiates a new GatewayNetworkSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayNetworkSpec() *GatewayNetworkSpec {
	this := GatewayNetworkSpec{}
	return &this
}

// NewGatewayNetworkSpecWithDefaults instantiates a new GatewayNetworkSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayNetworkSpecWithDefaults() *GatewayNetworkSpec {
	this := GatewayNetworkSpec{}
	return &this
}

// GetExternal returns the External field value if set, zero value otherwise.
func (o *GatewayNetworkSpec) GetExternal() GatewayEndpointSpec {
	if o == nil || IsNil(o.External) {
		var ret GatewayEndpointSpec
		return ret
	}
	return *o.External
}

// GetExternalOk returns a tuple with the External field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkSpec) GetExternalOk() (*GatewayEndpointSpec, bool) {
	if o == nil || IsNil(o.External) {
		return nil, false
	}
	return o.External, true
}

// HasExternal returns a boolean if a field has been set.
func (o *GatewayNetworkSpec) HasExternal() bool {
	if o != nil && !IsNil(o.External) {
		return true
	}

	return false
}

// SetExternal gets a reference to the given GatewayEndpointSpec and assigns it to the External field.
func (o *GatewayNetworkSpec) SetExternal(v GatewayEndpointSpec) {
	o.External = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *GatewayNetworkSpec) GetInternal() GatewayEndpointSpec {
	if o == nil || IsNil(o.Internal) {
		var ret GatewayEndpointSpec
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkSpec) GetInternalOk() (*GatewayEndpointSpec, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *GatewayNetworkSpec) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given GatewayEndpointSpec and assigns it to the Internal field.
func (o *GatewayNetworkSpec) SetInternal(v GatewayEndpointSpec) {
	o.Internal = &v
}

func (o GatewayNetworkSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayNetworkSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.External) {
		toSerialize["external"] = o.External
	}
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	return toSerialize, nil
}

type NullableGatewayNetworkSpec struct {
	value *GatewayNetworkSpec
	isSet bool
}

func (v NullableGatewayNetworkSpec) Get() *GatewayNetworkSpec {
	return v.value
}

func (v *NullableGatewayNetworkSpec) Set(val *GatewayNetworkSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayNetworkSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayNetworkSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayNetworkSpec(val *GatewayNetworkSpec) *NullableGatewayNetworkSpec {
	return &NullableGatewayNetworkSpec{value: val, isSet: true}
}

func (v NullableGatewayNetworkSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayNetworkSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
