/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ProviderConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderConfig{}

// ProviderConfig struct for ProviderConfig
type ProviderConfig struct {
	// Name of the llm provider
	ProviderName string `json:"providerName"`
	// UUID of the proxy created
	ProxyUuid string `json:"proxyUuid"`
	// Name/handle of the MCP proxy
	ProxyName *string `json:"proxyName,omitempty"`
	// ID/handle of the MCP proxy
	ProxyId *string `json:"proxyId,omitempty"`
	// Name/handle of the MCP proxy
	McpProxyName *string `json:"mcpProxyName,omitempty"`
	// ID/handle of the MCP proxy
	McpProxyId *string `json:"mcpProxyId,omitempty"`
	// url of the created proxy
	Url      string    `json:"url"`
	AuthInfo *AuthInfo `json:"authInfo,omitempty"`
	// Provider-specific policy configurations
	Policies []LLMPolicy `json:"policies,omitempty"`
	// Status of the proxy
	Status *string `json:"status,omitempty"`
}

// NewProviderConfig instantiates a new ProviderConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderConfig(providerName string, proxyUuid string, url string) *ProviderConfig {
	this := ProviderConfig{}
	this.ProviderName = providerName
	this.ProxyUuid = proxyUuid
	this.Url = url
	return &this
}

// NewProviderConfigWithDefaults instantiates a new ProviderConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderConfigWithDefaults() *ProviderConfig {
	this := ProviderConfig{}
	return &this
}

// GetProviderName returns the ProviderName field value
func (o *ProviderConfig) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetProviderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *ProviderConfig) SetProviderName(v string) {
	o.ProviderName = v
}

// GetProxyUuid returns the ProxyUuid field value
func (o *ProviderConfig) GetProxyUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyUuid
}

// GetProxyUuidOk returns a tuple with the ProxyUuid field value
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetProxyUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyUuid, true
}

// SetProxyUuid sets field value
func (o *ProviderConfig) SetProxyUuid(v string) {
	o.ProxyUuid = v
}

// GetProxyName returns the ProxyName field value if set, zero value otherwise.
func (o *ProviderConfig) GetProxyName() string {
	if o == nil || IsNil(o.ProxyName) {
		var ret string
		return ret
	}
	return *o.ProxyName
}

// GetProxyNameOk returns a tuple with the ProxyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetProxyNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyName) {
		return nil, false
	}
	return o.ProxyName, true
}

// HasProxyName returns a boolean if a field has been set.
func (o *ProviderConfig) HasProxyName() bool {
	if o != nil && !IsNil(o.ProxyName) {
		return true
	}

	return false
}

// SetProxyName gets a reference to the given string and assigns it to the ProxyName field.
func (o *ProviderConfig) SetProxyName(v string) {
	o.ProxyName = &v
}

// GetProxyId returns the ProxyId field value if set, zero value otherwise.
func (o *ProviderConfig) GetProxyId() string {
	if o == nil || IsNil(o.ProxyId) {
		var ret string
		return ret
	}
	return *o.ProxyId
}

// GetProxyIdOk returns a tuple with the ProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyId) {
		return nil, false
	}
	return o.ProxyId, true
}

// HasProxyId returns a boolean if a field has been set.
func (o *ProviderConfig) HasProxyId() bool {
	if o != nil && !IsNil(o.ProxyId) {
		return true
	}

	return false
}

// SetProxyId gets a reference to the given string and assigns it to the ProxyId field.
func (o *ProviderConfig) SetProxyId(v string) {
	o.ProxyId = &v
}

// GetMcpProxyName returns the McpProxyName field value if set, zero value otherwise.
func (o *ProviderConfig) GetMcpProxyName() string {
	if o == nil || IsNil(o.McpProxyName) {
		var ret string
		return ret
	}
	return *o.McpProxyName
}

// GetMcpProxyNameOk returns a tuple with the McpProxyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetMcpProxyNameOk() (*string, bool) {
	if o == nil || IsNil(o.McpProxyName) {
		return nil, false
	}
	return o.McpProxyName, true
}

// HasMcpProxyName returns a boolean if a field has been set.
func (o *ProviderConfig) HasMcpProxyName() bool {
	if o != nil && !IsNil(o.McpProxyName) {
		return true
	}

	return false
}

// SetMcpProxyName gets a reference to the given string and assigns it to the McpProxyName field.
func (o *ProviderConfig) SetMcpProxyName(v string) {
	o.McpProxyName = &v
}

// GetMcpProxyId returns the McpProxyId field value if set, zero value otherwise.
func (o *ProviderConfig) GetMcpProxyId() string {
	if o == nil || IsNil(o.McpProxyId) {
		var ret string
		return ret
	}
	return *o.McpProxyId
}

// GetMcpProxyIdOk returns a tuple with the McpProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetMcpProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.McpProxyId) {
		return nil, false
	}
	return o.McpProxyId, true
}

// HasMcpProxyId returns a boolean if a field has been set.
func (o *ProviderConfig) HasMcpProxyId() bool {
	if o != nil && !IsNil(o.McpProxyId) {
		return true
	}

	return false
}

// SetMcpProxyId gets a reference to the given string and assigns it to the McpProxyId field.
func (o *ProviderConfig) SetMcpProxyId(v string) {
	o.McpProxyId = &v
}

// GetUrl returns the Url field value
func (o *ProviderConfig) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ProviderConfig) SetUrl(v string) {
	o.Url = v
}

// GetAuthInfo returns the AuthInfo field value if set, zero value otherwise.
func (o *ProviderConfig) GetAuthInfo() AuthInfo {
	if o == nil || IsNil(o.AuthInfo) {
		var ret AuthInfo
		return ret
	}
	return *o.AuthInfo
}

// GetAuthInfoOk returns a tuple with the AuthInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetAuthInfoOk() (*AuthInfo, bool) {
	if o == nil || IsNil(o.AuthInfo) {
		return nil, false
	}
	return o.AuthInfo, true
}

// HasAuthInfo returns a boolean if a field has been set.
func (o *ProviderConfig) HasAuthInfo() bool {
	if o != nil && !IsNil(o.AuthInfo) {
		return true
	}

	return false
}

// SetAuthInfo gets a reference to the given AuthInfo and assigns it to the AuthInfo field.
func (o *ProviderConfig) SetAuthInfo(v AuthInfo) {
	o.AuthInfo = &v
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *ProviderConfig) GetPolicies() []LLMPolicy {
	if o == nil || IsNil(o.Policies) {
		var ret []LLMPolicy
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetPoliciesOk() ([]LLMPolicy, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *ProviderConfig) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []LLMPolicy and assigns it to the Policies field.
func (o *ProviderConfig) SetPolicies(v []LLMPolicy) {
	o.Policies = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProviderConfig) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderConfig) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProviderConfig) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProviderConfig) SetStatus(v string) {
	o.Status = &v
}

func (o ProviderConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerName"] = o.ProviderName
	toSerialize["proxyUuid"] = o.ProxyUuid
	if !IsNil(o.ProxyName) {
		toSerialize["proxyName"] = o.ProxyName
	}
	if !IsNil(o.ProxyId) {
		toSerialize["proxyId"] = o.ProxyId
	}
	if !IsNil(o.McpProxyName) {
		toSerialize["mcpProxyName"] = o.McpProxyName
	}
	if !IsNil(o.McpProxyId) {
		toSerialize["mcpProxyId"] = o.McpProxyId
	}
	toSerialize["url"] = o.Url
	if !IsNil(o.AuthInfo) {
		toSerialize["authInfo"] = o.AuthInfo
	}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableProviderConfig struct {
	value *ProviderConfig
	isSet bool
}

func (v NullableProviderConfig) Get() *ProviderConfig {
	return v.value
}

func (v *NullableProviderConfig) Set(val *ProviderConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderConfig(val *ProviderConfig) *NullableProviderConfig {
	return &NullableProviderConfig{value: val, isSet: true}
}

func (v NullableProviderConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
