/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProviderConsumerListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderConsumerListResponse{}

// LLMProviderConsumerListResponse struct for LLMProviderConsumerListResponse
type LLMProviderConsumerListResponse struct {
	Consumers []LLMProviderConsumerItem `json:"consumers"`
	// Total number of consumers
	Total int32 `json:"total"`
}

// NewLLMProviderConsumerListResponse instantiates a new LLMProviderConsumerListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderConsumerListResponse(consumers []LLMProviderConsumerItem, total int32) *LLMProviderConsumerListResponse {
	this := LLMProviderConsumerListResponse{}
	this.Consumers = consumers
	this.Total = total
	return &this
}

// NewLLMProviderConsumerListResponseWithDefaults instantiates a new LLMProviderConsumerListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderConsumerListResponseWithDefaults() *LLMProviderConsumerListResponse {
	this := LLMProviderConsumerListResponse{}
	return &this
}

// GetConsumers returns the Consumers field value
func (o *LLMProviderConsumerListResponse) GetConsumers() []LLMProviderConsumerItem {
	if o == nil {
		var ret []LLMProviderConsumerItem
		return ret
	}

	return o.Consumers
}

// GetConsumersOk returns a tuple with the Consumers field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerListResponse) GetConsumersOk() ([]LLMProviderConsumerItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Consumers, true
}

// SetConsumers sets field value
func (o *LLMProviderConsumerListResponse) SetConsumers(v []LLMProviderConsumerItem) {
	o.Consumers = v
}

// GetTotal returns the Total field value
func (o *LLMProviderConsumerListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *LLMProviderConsumerListResponse) SetTotal(v int32) {
	o.Total = v
}

func (o LLMProviderConsumerListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderConsumerListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consumers"] = o.Consumers
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

type NullableLLMProviderConsumerListResponse struct {
	value *LLMProviderConsumerListResponse
	isSet bool
}

func (v NullableLLMProviderConsumerListResponse) Get() *LLMProviderConsumerListResponse {
	return v.value
}

func (v *NullableLLMProviderConsumerListResponse) Set(val *LLMProviderConsumerListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderConsumerListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderConsumerListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderConsumerListResponse(val *LLMProviderConsumerListResponse) *NullableLLMProviderConsumerListResponse {
	return &NullableLLMProviderConsumerListResponse{value: val, isSet: true}
}

func (v NullableLLMProviderConsumerListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderConsumerListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
