/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EnvModelConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvModelConfigRequest{}

// EnvModelConfigRequest struct for EnvModelConfigRequest
type EnvModelConfigRequest struct {
	// Handle of the LLM provider for this environment. For MCP configs, proxyName/proxyId may be used instead.
	ProviderName *string `json:"providerName,omitempty"`
	// Handle/name of the MCP proxy for this environment
	ProxyName *string `json:"proxyName,omitempty"`
	// ID/handle of the MCP proxy for this environment
	ProxyId *string `json:"proxyId,omitempty"`
	// Handle/name of the MCP proxy for this environment
	McpProxyName *string `json:"mcpProxyName,omitempty"`
	// ID/handle of the MCP proxy for this environment
	McpProxyId    *string                  `json:"mcpProxyId,omitempty"`
	Configuration EnvProviderConfiguration `json:"configuration"`
}

// NewEnvModelConfigRequest instantiates a new EnvModelConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvModelConfigRequest(configuration EnvProviderConfiguration) *EnvModelConfigRequest {
	this := EnvModelConfigRequest{}
	this.Configuration = configuration
	return &this
}

// NewEnvModelConfigRequestWithDefaults instantiates a new EnvModelConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvModelConfigRequestWithDefaults() *EnvModelConfigRequest {
	this := EnvModelConfigRequest{}
	return &this
}

// GetProviderName returns the ProviderName field value if set, zero value otherwise.
func (o *EnvModelConfigRequest) GetProviderName() string {
	if o == nil || IsNil(o.ProviderName) {
		var ret string
		return ret
	}
	return *o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetProviderNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderName) {
		return nil, false
	}
	return o.ProviderName, true
}

// HasProviderName returns a boolean if a field has been set.
func (o *EnvModelConfigRequest) HasProviderName() bool {
	if o != nil && !IsNil(o.ProviderName) {
		return true
	}

	return false
}

// SetProviderName gets a reference to the given string and assigns it to the ProviderName field.
func (o *EnvModelConfigRequest) SetProviderName(v string) {
	o.ProviderName = &v
}

// GetProxyName returns the ProxyName field value if set, zero value otherwise.
func (o *EnvModelConfigRequest) GetProxyName() string {
	if o == nil || IsNil(o.ProxyName) {
		var ret string
		return ret
	}
	return *o.ProxyName
}

// GetProxyNameOk returns a tuple with the ProxyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetProxyNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyName) {
		return nil, false
	}
	return o.ProxyName, true
}

// HasProxyName returns a boolean if a field has been set.
func (o *EnvModelConfigRequest) HasProxyName() bool {
	if o != nil && !IsNil(o.ProxyName) {
		return true
	}

	return false
}

// SetProxyName gets a reference to the given string and assigns it to the ProxyName field.
func (o *EnvModelConfigRequest) SetProxyName(v string) {
	o.ProxyName = &v
}

// GetProxyId returns the ProxyId field value if set, zero value otherwise.
func (o *EnvModelConfigRequest) GetProxyId() string {
	if o == nil || IsNil(o.ProxyId) {
		var ret string
		return ret
	}
	return *o.ProxyId
}

// GetProxyIdOk returns a tuple with the ProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyId) {
		return nil, false
	}
	return o.ProxyId, true
}

// HasProxyId returns a boolean if a field has been set.
func (o *EnvModelConfigRequest) HasProxyId() bool {
	if o != nil && !IsNil(o.ProxyId) {
		return true
	}

	return false
}

// SetProxyId gets a reference to the given string and assigns it to the ProxyId field.
func (o *EnvModelConfigRequest) SetProxyId(v string) {
	o.ProxyId = &v
}

// GetMcpProxyName returns the McpProxyName field value if set, zero value otherwise.
func (o *EnvModelConfigRequest) GetMcpProxyName() string {
	if o == nil || IsNil(o.McpProxyName) {
		var ret string
		return ret
	}
	return *o.McpProxyName
}

// GetMcpProxyNameOk returns a tuple with the McpProxyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetMcpProxyNameOk() (*string, bool) {
	if o == nil || IsNil(o.McpProxyName) {
		return nil, false
	}
	return o.McpProxyName, true
}

// HasMcpProxyName returns a boolean if a field has been set.
func (o *EnvModelConfigRequest) HasMcpProxyName() bool {
	if o != nil && !IsNil(o.McpProxyName) {
		return true
	}

	return false
}

// SetMcpProxyName gets a reference to the given string and assigns it to the McpProxyName field.
func (o *EnvModelConfigRequest) SetMcpProxyName(v string) {
	o.McpProxyName = &v
}

// GetMcpProxyId returns the McpProxyId field value if set, zero value otherwise.
func (o *EnvModelConfigRequest) GetMcpProxyId() string {
	if o == nil || IsNil(o.McpProxyId) {
		var ret string
		return ret
	}
	return *o.McpProxyId
}

// GetMcpProxyIdOk returns a tuple with the McpProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetMcpProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.McpProxyId) {
		return nil, false
	}
	return o.McpProxyId, true
}

// HasMcpProxyId returns a boolean if a field has been set.
func (o *EnvModelConfigRequest) HasMcpProxyId() bool {
	if o != nil && !IsNil(o.McpProxyId) {
		return true
	}

	return false
}

// SetMcpProxyId gets a reference to the given string and assigns it to the McpProxyId field.
func (o *EnvModelConfigRequest) SetMcpProxyId(v string) {
	o.McpProxyId = &v
}

// GetConfiguration returns the Configuration field value
func (o *EnvModelConfigRequest) GetConfiguration() EnvProviderConfiguration {
	if o == nil {
		var ret EnvProviderConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *EnvModelConfigRequest) GetConfigurationOk() (*EnvProviderConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *EnvModelConfigRequest) SetConfiguration(v EnvProviderConfiguration) {
	o.Configuration = v
}

func (o EnvModelConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvModelConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProviderName) {
		toSerialize["providerName"] = o.ProviderName
	}
	if !IsNil(o.ProxyName) {
		toSerialize["proxyName"] = o.ProxyName
	}
	if !IsNil(o.ProxyId) {
		toSerialize["proxyId"] = o.ProxyId
	}
	if !IsNil(o.McpProxyName) {
		toSerialize["mcpProxyName"] = o.McpProxyName
	}
	if !IsNil(o.McpProxyId) {
		toSerialize["mcpProxyId"] = o.McpProxyId
	}
	toSerialize["configuration"] = o.Configuration
	return toSerialize, nil
}

type NullableEnvModelConfigRequest struct {
	value *EnvModelConfigRequest
	isSet bool
}

func (v NullableEnvModelConfigRequest) Get() *EnvModelConfigRequest {
	return v.value
}

func (v *NullableEnvModelConfigRequest) Set(val *EnvModelConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvModelConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvModelConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvModelConfigRequest(val *EnvModelConfigRequest) *NullableEnvModelConfigRequest {
	return &NullableEnvModelConfigRequest{value: val, isSet: true}
}

func (v NullableEnvModelConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvModelConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
