/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateDeploymentPipelineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDeploymentPipelineRequest{}

// UpdateDeploymentPipelineRequest struct for UpdateDeploymentPipelineRequest
type UpdateDeploymentPipelineRequest struct {
	// Updated display name
	DisplayName *string `json:"displayName,omitempty"`
	// Updated description
	Description *string `json:"description,omitempty"`
	// Updated list of promotion paths
	PromotionPaths []PromotionPath `json:"promotionPaths"`
}

// NewUpdateDeploymentPipelineRequest instantiates a new UpdateDeploymentPipelineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDeploymentPipelineRequest(promotionPaths []PromotionPath) *UpdateDeploymentPipelineRequest {
	this := UpdateDeploymentPipelineRequest{}
	this.PromotionPaths = promotionPaths
	return &this
}

// NewUpdateDeploymentPipelineRequestWithDefaults instantiates a new UpdateDeploymentPipelineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDeploymentPipelineRequestWithDefaults() *UpdateDeploymentPipelineRequest {
	this := UpdateDeploymentPipelineRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateDeploymentPipelineRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDeploymentPipelineRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateDeploymentPipelineRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateDeploymentPipelineRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateDeploymentPipelineRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDeploymentPipelineRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateDeploymentPipelineRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateDeploymentPipelineRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPromotionPaths returns the PromotionPaths field value
func (o *UpdateDeploymentPipelineRequest) GetPromotionPaths() []PromotionPath {
	if o == nil {
		var ret []PromotionPath
		return ret
	}

	return o.PromotionPaths
}

// GetPromotionPathsOk returns a tuple with the PromotionPaths field value
// and a boolean to check if the value has been set.
func (o *UpdateDeploymentPipelineRequest) GetPromotionPathsOk() ([]PromotionPath, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromotionPaths, true
}

// SetPromotionPaths sets field value
func (o *UpdateDeploymentPipelineRequest) SetPromotionPaths(v []PromotionPath) {
	o.PromotionPaths = v
}

func (o UpdateDeploymentPipelineRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDeploymentPipelineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["promotionPaths"] = o.PromotionPaths
	return toSerialize, nil
}

type NullableUpdateDeploymentPipelineRequest struct {
	value *UpdateDeploymentPipelineRequest
	isSet bool
}

func (v NullableUpdateDeploymentPipelineRequest) Get() *UpdateDeploymentPipelineRequest {
	return v.value
}

func (v *NullableUpdateDeploymentPipelineRequest) Set(val *UpdateDeploymentPipelineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDeploymentPipelineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDeploymentPipelineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDeploymentPipelineRequest(val *UpdateDeploymentPipelineRequest) *NullableUpdateDeploymentPipelineRequest {
	return &NullableUpdateDeploymentPipelineRequest{value: val, isSet: true}
}

func (v NullableUpdateDeploymentPipelineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDeploymentPipelineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
