/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateDeploymentPipelineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeploymentPipelineRequest{}

// CreateDeploymentPipelineRequest struct for CreateDeploymentPipelineRequest
type CreateDeploymentPipelineRequest struct {
	// Human-readable name for the pipeline
	DisplayName string `json:"displayName"`
	// Optional description
	Description *string `json:"description,omitempty"`
	// Optional project to associate the pipeline with
	ProjectName *string `json:"projectName,omitempty"`
	// Ordered list of promotion paths
	PromotionPaths []PromotionPath `json:"promotionPaths"`
}

// NewCreateDeploymentPipelineRequest instantiates a new CreateDeploymentPipelineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeploymentPipelineRequest(displayName string, promotionPaths []PromotionPath) *CreateDeploymentPipelineRequest {
	this := CreateDeploymentPipelineRequest{}
	this.DisplayName = displayName
	this.PromotionPaths = promotionPaths
	return &this
}

// NewCreateDeploymentPipelineRequestWithDefaults instantiates a new CreateDeploymentPipelineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeploymentPipelineRequestWithDefaults() *CreateDeploymentPipelineRequest {
	this := CreateDeploymentPipelineRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *CreateDeploymentPipelineRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateDeploymentPipelineRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateDeploymentPipelineRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateDeploymentPipelineRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeploymentPipelineRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateDeploymentPipelineRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateDeploymentPipelineRequest) SetDescription(v string) {
	o.Description = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *CreateDeploymentPipelineRequest) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeploymentPipelineRequest) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *CreateDeploymentPipelineRequest) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *CreateDeploymentPipelineRequest) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetPromotionPaths returns the PromotionPaths field value
func (o *CreateDeploymentPipelineRequest) GetPromotionPaths() []PromotionPath {
	if o == nil {
		var ret []PromotionPath
		return ret
	}

	return o.PromotionPaths
}

// GetPromotionPathsOk returns a tuple with the PromotionPaths field value
// and a boolean to check if the value has been set.
func (o *CreateDeploymentPipelineRequest) GetPromotionPathsOk() ([]PromotionPath, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromotionPaths, true
}

// SetPromotionPaths sets field value
func (o *CreateDeploymentPipelineRequest) SetPromotionPaths(v []PromotionPath) {
	o.PromotionPaths = v
}

func (o CreateDeploymentPipelineRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeploymentPipelineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	toSerialize["promotionPaths"] = o.PromotionPaths
	return toSerialize, nil
}

type NullableCreateDeploymentPipelineRequest struct {
	value *CreateDeploymentPipelineRequest
	isSet bool
}

func (v NullableCreateDeploymentPipelineRequest) Get() *CreateDeploymentPipelineRequest {
	return v.value
}

func (v *NullableCreateDeploymentPipelineRequest) Set(val *CreateDeploymentPipelineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeploymentPipelineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeploymentPipelineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeploymentPipelineRequest(val *CreateDeploymentPipelineRequest) *NullableCreateDeploymentPipelineRequest {
	return &NullableCreateDeploymentPipelineRequest{value: val, isSet: true}
}

func (v NullableCreateDeploymentPipelineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeploymentPipelineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
