/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the LLMProviderConsumerItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderConsumerItem{}

// LLMProviderConsumerItem struct for LLMProviderConsumerItem
type LLMProviderConsumerItem struct {
	// Handle/ID of the LLM proxy
	ProxyId string `json:"proxyId"`
	// Display name of the LLM proxy
	ProxyName string `json:"proxyName"`
	// Name of the project the proxy belongs to
	ProjectName string `json:"projectName"`
	// Whether the consumer is an agent or a monitor
	ConsumerType string `json:"consumerType"`
	// Name (handle) of the agent or monitor consuming the proxy
	ConsumerName string `json:"consumerName"`
}

// NewLLMProviderConsumerItem instantiates a new LLMProviderConsumerItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderConsumerItem(proxyId string, proxyName string, projectName string, consumerType string, consumerName string) *LLMProviderConsumerItem {
	this := LLMProviderConsumerItem{}
	this.ProxyId = proxyId
	this.ProxyName = proxyName
	this.ProjectName = projectName
	this.ConsumerType = consumerType
	this.ConsumerName = consumerName
	return &this
}

// NewLLMProviderConsumerItemWithDefaults instantiates a new LLMProviderConsumerItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderConsumerItemWithDefaults() *LLMProviderConsumerItem {
	this := LLMProviderConsumerItem{}
	return &this
}

// GetProxyId returns the ProxyId field value
func (o *LLMProviderConsumerItem) GetProxyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyId
}

// GetProxyIdOk returns a tuple with the ProxyId field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerItem) GetProxyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyId, true
}

// SetProxyId sets field value
func (o *LLMProviderConsumerItem) SetProxyId(v string) {
	o.ProxyId = v
}

// GetProxyName returns the ProxyName field value
func (o *LLMProviderConsumerItem) GetProxyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyName
}

// GetProxyNameOk returns a tuple with the ProxyName field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerItem) GetProxyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyName, true
}

// SetProxyName sets field value
func (o *LLMProviderConsumerItem) SetProxyName(v string) {
	o.ProxyName = v
}

// GetProjectName returns the ProjectName field value
func (o *LLMProviderConsumerItem) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerItem) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *LLMProviderConsumerItem) SetProjectName(v string) {
	o.ProjectName = v
}

// GetConsumerType returns the ConsumerType field value
func (o *LLMProviderConsumerItem) GetConsumerType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsumerType
}

// GetConsumerTypeOk returns a tuple with the ConsumerType field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerItem) GetConsumerTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerType, true
}

// SetConsumerType sets field value
func (o *LLMProviderConsumerItem) SetConsumerType(v string) {
	o.ConsumerType = v
}

// GetConsumerName returns the ConsumerName field value
func (o *LLMProviderConsumerItem) GetConsumerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsumerName
}

// GetConsumerNameOk returns a tuple with the ConsumerName field value
// and a boolean to check if the value has been set.
func (o *LLMProviderConsumerItem) GetConsumerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerName, true
}

// SetConsumerName sets field value
func (o *LLMProviderConsumerItem) SetConsumerName(v string) {
	o.ConsumerName = v
}

func (o LLMProviderConsumerItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderConsumerItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proxyId"] = o.ProxyId
	toSerialize["proxyName"] = o.ProxyName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["consumerType"] = o.ConsumerType
	toSerialize["consumerName"] = o.ConsumerName
	return toSerialize, nil
}

type NullableLLMProviderConsumerItem struct {
	value *LLMProviderConsumerItem
	isSet bool
}

func (v NullableLLMProviderConsumerItem) Get() *LLMProviderConsumerItem {
	return v.value
}

func (v *NullableLLMProviderConsumerItem) Set(val *LLMProviderConsumerItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderConsumerItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderConsumerItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderConsumerItem(val *LLMProviderConsumerItem) *NullableLLMProviderConsumerItem {
	return &NullableLLMProviderConsumerItem{value: val, isSet: true}
}

func (v NullableLLMProviderConsumerItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderConsumerItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
