apiVersion: v1
kind: Secret
metadata:
  name: apim46-lab-env
  namespace: apim46-lab
type: Opaque
stringData:
  SUPER_ADMIN_USERNAME: admin
  SUPER_ADMIN_PASSWORD: CHANGE_ME
  TLS_KEYSTORE_PASSWORD: CHANGE_ME
  TLS_KEY_ALIAS: wso2carbon
  TLS_KEY_PASSWORD: CHANGE_ME
  MOESIF_KEY: CHANGE_ME
  OPENAI_API_KEY: CHANGE_ME
  AZURE_CONTENT_SAFETY_ENDPOINT: https://replace-me.cognitiveservices.azure.com/
  AZURE_CONTENT_SAFETY_KEY: CHANGE_ME
  MCP_SERVER_URL: http://mcp-service.default.svc.cluster.local:8080/mcp
  ZILLIZ_URI: http://milvus.default.svc.cluster.local:19530
  ZILLIZ_TOKEN: CHANGE_ME
  OTLP_GRPC_ENDPOINT: http://otel-collector.openchoreo-observability-plane.svc.cluster.local:4317
  OTLP_HOSTNAME: otel-collector.openchoreo-observability-plane.svc.cluster.local
  OTLP_PORT: "4317"
---
apiVersion: v1
kind: Secret
metadata:
  name: apim46-lab-keystores
  namespace: apim46-lab
type: Opaque
data:
  wso2carbon-new.jks: BASE64_ENCODED_WSO2CARBON_NEW_JKS
  wso2carbon-new.cer: BASE64_ENCODED_WSO2CARBON_NEW_CER
  client-truststore.jks: BASE64_ENCODED_CLIENT_TRUSTSTORE_JKS
  client-truststore-temp.jks: BASE64_ENCODED_CLIENT_TRUSTSTORE_TEMP_JKS
  wso2carbon.jks: BASE64_ENCODED_WSO2CARBON_JKS