apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim46-lab-db
  namespace: apim46-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path