// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// AgentConfigurationRepositoryMock is a mock implementation of repositories.AgentConfigurationRepository.
//
//	func TestSomethingThatUsesAgentConfigurationRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AgentConfigurationRepository
//		mockedAgentConfigurationRepository := &AgentConfigurationRepositoryMock{
//			CountFunc: func(ctx context.Context, orgName string) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CountByAgentFunc: func(ctx context.Context, orgName string, projectName string, agentName string) (int64, error) {
//				panic("mock out the CountByAgent method")
//			},
//			CountByAgentAndTypeFunc: func(ctx context.Context, orgName string, projectName string, agentName string, typeID uint) (int64, error) {
//				panic("mock out the CountByAgentAndType method")
//			},
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, orgName string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(ctx context.Context, configUUID uuid.UUID, orgName string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetByAgentIDFunc: func(ctx context.Context, agentID string, orgName string) (*models.AgentConfiguration, error) {
//				panic("mock out the GetByAgentID method")
//			},
//			GetByUUIDFunc: func(ctx context.Context, configUUID uuid.UUID, orgName string) (*models.AgentConfiguration, error) {
//				panic("mock out the GetByUUID method")
//			},
//			ListFunc: func(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentConfiguration, error) {
//				panic("mock out the List method")
//			},
//			ListByAgentFunc: func(ctx context.Context, orgName string, projectName string, agentName string, limit int, offset int) ([]models.AgentConfiguration, error) {
//				panic("mock out the ListByAgent method")
//			},
//			ListByAgentAndTypeFunc: func(ctx context.Context, orgName string, projectName string, agentName string, typeID uint, limit int, offset int) ([]models.AgentConfiguration, error) {
//				panic("mock out the ListByAgentAndType method")
//			},
//			UpdateFunc: func(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedAgentConfigurationRepository in code that requires repositories.AgentConfigurationRepository
//		// and then make assertions.
//
//	}
type AgentConfigurationRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, orgName string) (int64, error)

	// CountByAgentFunc mocks the CountByAgent method.
	CountByAgentFunc func(ctx context.Context, orgName string, projectName string, agentName string) (int64, error)

	// CountByAgentAndTypeFunc mocks the CountByAgentAndType method.
	CountByAgentAndTypeFunc func(ctx context.Context, orgName string, projectName string, agentName string, typeID uint) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, orgName string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, configUUID uuid.UUID, orgName string) (bool, error)

	// GetByAgentIDFunc mocks the GetByAgentID method.
	GetByAgentIDFunc func(ctx context.Context, agentID string, orgName string) (*models.AgentConfiguration, error)

	// GetByUUIDFunc mocks the GetByUUID method.
	GetByUUIDFunc func(ctx context.Context, configUUID uuid.UUID, orgName string) (*models.AgentConfiguration, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentConfiguration, error)

	// ListByAgentFunc mocks the ListByAgent method.
	ListByAgentFunc func(ctx context.Context, orgName string, projectName string, agentName string, limit int, offset int) ([]models.AgentConfiguration, error)

	// ListByAgentAndTypeFunc mocks the ListByAgentAndType method.
	ListByAgentAndTypeFunc func(ctx context.Context, orgName string, projectName string, agentName string, typeID uint, limit int, offset int) ([]models.AgentConfiguration, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// CountByAgent holds details about calls to the CountByAgent method.
		CountByAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// CountByAgentAndType holds details about calls to the CountByAgentAndType method.
		CountByAgentAndType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// TypeID is the typeID argument value.
			TypeID uint
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Config is the config argument value.
			Config *models.AgentConfiguration
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// OrgName is the orgName argument value.
			OrgName string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetByAgentID holds details about calls to the GetByAgentID method.
		GetByAgentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AgentID is the agentID argument value.
			AgentID string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetByUUID holds details about calls to the GetByUUID method.
		GetByUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// OrgName is the orgName argument value.
			OrgName string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByAgent holds details about calls to the ListByAgent method.
		ListByAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByAgentAndType holds details about calls to the ListByAgentAndType method.
		ListByAgentAndType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// TypeID is the typeID argument value.
			TypeID uint
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Config is the config argument value.
			Config *models.AgentConfiguration
		}
	}
	lockCount               sync.RWMutex
	lockCountByAgent        sync.RWMutex
	lockCountByAgentAndType sync.RWMutex
	lockCreate              sync.RWMutex
	lockDelete              sync.RWMutex
	lockExists              sync.RWMutex
	lockGetByAgentID        sync.RWMutex
	lockGetByUUID           sync.RWMutex
	lockList                sync.RWMutex
	lockListByAgent         sync.RWMutex
	lockListByAgentAndType  sync.RWMutex
	lockUpdate              sync.RWMutex
}

// Count calls CountFunc.
func (mock *AgentConfigurationRepositoryMock) Count(ctx context.Context, orgName string) (int64, error) {
	if mock.CountFunc == nil {
		panic("AgentConfigurationRepositoryMock.CountFunc: method is nil but AgentConfigurationRepository.Count was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, orgName)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.CountCalls())
func (mock *AgentConfigurationRepositoryMock) CountCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// CountByAgent calls CountByAgentFunc.
func (mock *AgentConfigurationRepositoryMock) CountByAgent(ctx context.Context, orgName string, projectName string, agentName string) (int64, error) {
	if mock.CountByAgentFunc == nil {
		panic("AgentConfigurationRepositoryMock.CountByAgentFunc: method is nil but AgentConfigurationRepository.CountByAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockCountByAgent.Lock()
	mock.calls.CountByAgent = append(mock.calls.CountByAgent, callInfo)
	mock.lockCountByAgent.Unlock()
	return mock.CountByAgentFunc(ctx, orgName, projectName, agentName)
}

// CountByAgentCalls gets all the calls that were made to CountByAgent.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.CountByAgentCalls())
func (mock *AgentConfigurationRepositoryMock) CountByAgentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
	}
	mock.lockCountByAgent.RLock()
	calls = mock.calls.CountByAgent
	mock.lockCountByAgent.RUnlock()
	return calls
}

// CountByAgentAndType calls CountByAgentAndTypeFunc.
func (mock *AgentConfigurationRepositoryMock) CountByAgentAndType(ctx context.Context, orgName string, projectName string, agentName string, typeID uint) (int64, error) {
	if mock.CountByAgentAndTypeFunc == nil {
		panic("AgentConfigurationRepositoryMock.CountByAgentAndTypeFunc: method is nil but AgentConfigurationRepository.CountByAgentAndType was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		TypeID      uint
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		TypeID:      typeID,
	}
	mock.lockCountByAgentAndType.Lock()
	mock.calls.CountByAgentAndType = append(mock.calls.CountByAgentAndType, callInfo)
	mock.lockCountByAgentAndType.Unlock()
	return mock.CountByAgentAndTypeFunc(ctx, orgName, projectName, agentName, typeID)
}

// CountByAgentAndTypeCalls gets all the calls that were made to CountByAgentAndType.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.CountByAgentAndTypeCalls())
func (mock *AgentConfigurationRepositoryMock) CountByAgentAndTypeCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
	TypeID      uint
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		TypeID      uint
	}
	mock.lockCountByAgentAndType.RLock()
	calls = mock.calls.CountByAgentAndType
	mock.lockCountByAgentAndType.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *AgentConfigurationRepositoryMock) Create(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error {
	if mock.CreateFunc == nil {
		panic("AgentConfigurationRepositoryMock.CreateFunc: method is nil but AgentConfigurationRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     *gorm.DB
		Config *models.AgentConfiguration
	}{
		Ctx:    ctx,
		Tx:     tx,
		Config: config,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, config)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.CreateCalls())
func (mock *AgentConfigurationRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Tx     *gorm.DB
	Config *models.AgentConfiguration
} {
	var calls []struct {
		Ctx    context.Context
		Tx     *gorm.DB
		Config *models.AgentConfiguration
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AgentConfigurationRepositoryMock) Delete(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, orgName string) error {
	if mock.DeleteFunc == nil {
		panic("AgentConfigurationRepositoryMock.DeleteFunc: method is nil but AgentConfigurationRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		OrgName    string
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
		OrgName:    orgName,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, tx, configUUID, orgName)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.DeleteCalls())
func (mock *AgentConfigurationRepositoryMock) DeleteCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
	OrgName    string
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		OrgName    string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *AgentConfigurationRepositoryMock) Exists(ctx context.Context, configUUID uuid.UUID, orgName string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("AgentConfigurationRepositoryMock.ExistsFunc: method is nil but AgentConfigurationRepository.Exists was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		OrgName    string
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
		OrgName:    orgName,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, configUUID, orgName)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.ExistsCalls())
func (mock *AgentConfigurationRepositoryMock) ExistsCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
	OrgName    string
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		OrgName    string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetByAgentID calls GetByAgentIDFunc.
func (mock *AgentConfigurationRepositoryMock) GetByAgentID(ctx context.Context, agentID string, orgName string) (*models.AgentConfiguration, error) {
	if mock.GetByAgentIDFunc == nil {
		panic("AgentConfigurationRepositoryMock.GetByAgentIDFunc: method is nil but AgentConfigurationRepository.GetByAgentID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AgentID string
		OrgName string
	}{
		Ctx:     ctx,
		AgentID: agentID,
		OrgName: orgName,
	}
	mock.lockGetByAgentID.Lock()
	mock.calls.GetByAgentID = append(mock.calls.GetByAgentID, callInfo)
	mock.lockGetByAgentID.Unlock()
	return mock.GetByAgentIDFunc(ctx, agentID, orgName)
}

// GetByAgentIDCalls gets all the calls that were made to GetByAgentID.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.GetByAgentIDCalls())
func (mock *AgentConfigurationRepositoryMock) GetByAgentIDCalls() []struct {
	Ctx     context.Context
	AgentID string
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		AgentID string
		OrgName string
	}
	mock.lockGetByAgentID.RLock()
	calls = mock.calls.GetByAgentID
	mock.lockGetByAgentID.RUnlock()
	return calls
}

// GetByUUID calls GetByUUIDFunc.
func (mock *AgentConfigurationRepositoryMock) GetByUUID(ctx context.Context, configUUID uuid.UUID, orgName string) (*models.AgentConfiguration, error) {
	if mock.GetByUUIDFunc == nil {
		panic("AgentConfigurationRepositoryMock.GetByUUIDFunc: method is nil but AgentConfigurationRepository.GetByUUID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		OrgName    string
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
		OrgName:    orgName,
	}
	mock.lockGetByUUID.Lock()
	mock.calls.GetByUUID = append(mock.calls.GetByUUID, callInfo)
	mock.lockGetByUUID.Unlock()
	return mock.GetByUUIDFunc(ctx, configUUID, orgName)
}

// GetByUUIDCalls gets all the calls that were made to GetByUUID.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.GetByUUIDCalls())
func (mock *AgentConfigurationRepositoryMock) GetByUUIDCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
	OrgName    string
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		OrgName    string
	}
	mock.lockGetByUUID.RLock()
	calls = mock.calls.GetByUUID
	mock.lockGetByUUID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AgentConfigurationRepositoryMock) List(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentConfiguration, error) {
	if mock.ListFunc == nil {
		panic("AgentConfigurationRepositoryMock.ListFunc: method is nil but AgentConfigurationRepository.List was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Offset  int
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, orgName, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.ListCalls())
func (mock *AgentConfigurationRepositoryMock) ListCalls() []struct {
	Ctx     context.Context
	OrgName string
	Limit   int
	Offset  int
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Offset  int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByAgent calls ListByAgentFunc.
func (mock *AgentConfigurationRepositoryMock) ListByAgent(ctx context.Context, orgName string, projectName string, agentName string, limit int, offset int) ([]models.AgentConfiguration, error) {
	if mock.ListByAgentFunc == nil {
		panic("AgentConfigurationRepositoryMock.ListByAgentFunc: method is nil but AgentConfigurationRepository.ListByAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Limit       int
		Offset      int
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		Limit:       limit,
		Offset:      offset,
	}
	mock.lockListByAgent.Lock()
	mock.calls.ListByAgent = append(mock.calls.ListByAgent, callInfo)
	mock.lockListByAgent.Unlock()
	return mock.ListByAgentFunc(ctx, orgName, projectName, agentName, limit, offset)
}

// ListByAgentCalls gets all the calls that were made to ListByAgent.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.ListByAgentCalls())
func (mock *AgentConfigurationRepositoryMock) ListByAgentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
	Limit       int
	Offset      int
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		Limit       int
		Offset      int
	}
	mock.lockListByAgent.RLock()
	calls = mock.calls.ListByAgent
	mock.lockListByAgent.RUnlock()
	return calls
}

// ListByAgentAndType calls ListByAgentAndTypeFunc.
func (mock *AgentConfigurationRepositoryMock) ListByAgentAndType(ctx context.Context, orgName string, projectName string, agentName string, typeID uint, limit int, offset int) ([]models.AgentConfiguration, error) {
	if mock.ListByAgentAndTypeFunc == nil {
		panic("AgentConfigurationRepositoryMock.ListByAgentAndTypeFunc: method is nil but AgentConfigurationRepository.ListByAgentAndType was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		TypeID      uint
		Limit       int
		Offset      int
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		TypeID:      typeID,
		Limit:       limit,
		Offset:      offset,
	}
	mock.lockListByAgentAndType.Lock()
	mock.calls.ListByAgentAndType = append(mock.calls.ListByAgentAndType, callInfo)
	mock.lockListByAgentAndType.Unlock()
	return mock.ListByAgentAndTypeFunc(ctx, orgName, projectName, agentName, typeID, limit, offset)
}

// ListByAgentAndTypeCalls gets all the calls that were made to ListByAgentAndType.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.ListByAgentAndTypeCalls())
func (mock *AgentConfigurationRepositoryMock) ListByAgentAndTypeCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentName   string
	TypeID      uint
	Limit       int
	Offset      int
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentName   string
		TypeID      uint
		Limit       int
		Offset      int
	}
	mock.lockListByAgentAndType.RLock()
	calls = mock.calls.ListByAgentAndType
	mock.lockListByAgentAndType.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *AgentConfigurationRepositoryMock) Update(ctx context.Context, tx *gorm.DB, config *models.AgentConfiguration) error {
	if mock.UpdateFunc == nil {
		panic("AgentConfigurationRepositoryMock.UpdateFunc: method is nil but AgentConfigurationRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     *gorm.DB
		Config *models.AgentConfiguration
	}{
		Ctx:    ctx,
		Tx:     tx,
		Config: config,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, tx, config)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedAgentConfigurationRepository.UpdateCalls())
func (mock *AgentConfigurationRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Tx     *gorm.DB
	Config *models.AgentConfiguration
} {
	var calls []struct {
		Ctx    context.Context
		Tx     *gorm.DB
		Config *models.AgentConfiguration
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
