// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// AgentKindRepositoryMock is a mock implementation of repositories.AgentKindRepository.
//
//	func TestSomethingThatUsesAgentKindRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AgentKindRepository
//		mockedAgentKindRepository := &AgentKindRepositoryMock{
//			CreateKindFunc: func(ctx context.Context, kind *models.AgentKind) error {
//				panic("mock out the CreateKind method")
//			},
//			CreateVersionFunc: func(ctx context.Context, version *models.AgentKindVersion) error {
//				panic("mock out the CreateVersion method")
//			},
//			DeleteKindFunc: func(ctx context.Context, orgName string, kindName string) error {
//				panic("mock out the DeleteKind method")
//			},
//			DeleteVersionFunc: func(ctx context.Context, kindID uuid.UUID, versionTag string) error {
//				panic("mock out the DeleteVersion method")
//			},
//			FindVersionByImageIDInOrgFunc: func(ctx context.Context, orgName string, imageID string) (*models.AgentKindVersion, error) {
//				panic("mock out the FindVersionByImageIDInOrg method")
//			},
//			GetKindFunc: func(ctx context.Context, orgName string, kindName string) (*models.AgentKind, error) {
//				panic("mock out the GetKind method")
//			},
//			GetVersionFunc: func(ctx context.Context, kindID uuid.UUID, versionTag string) (*models.AgentKindVersion, error) {
//				panic("mock out the GetVersion method")
//			},
//			GetVersionByImageIDFunc: func(ctx context.Context, kindID uuid.UUID, imageID string) (*models.AgentKindVersion, error) {
//				panic("mock out the GetVersionByImageID method")
//			},
//			ListKindsFunc: func(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentKind, int64, error) {
//				panic("mock out the ListKinds method")
//			},
//			ListVersionsFunc: func(ctx context.Context, kindID uuid.UUID) ([]models.AgentKindVersion, error) {
//				panic("mock out the ListVersions method")
//			},
//			UpdateKindFunc: func(ctx context.Context, kind *models.AgentKind) error {
//				panic("mock out the UpdateKind method")
//			},
//		}
//
//		// use mockedAgentKindRepository in code that requires repositories.AgentKindRepository
//		// and then make assertions.
//
//	}
type AgentKindRepositoryMock struct {
	// CreateKindFunc mocks the CreateKind method.
	CreateKindFunc func(ctx context.Context, kind *models.AgentKind) error

	// CreateVersionFunc mocks the CreateVersion method.
	CreateVersionFunc func(ctx context.Context, version *models.AgentKindVersion) error

	// DeleteKindFunc mocks the DeleteKind method.
	DeleteKindFunc func(ctx context.Context, orgName string, kindName string) error

	// DeleteVersionFunc mocks the DeleteVersion method.
	DeleteVersionFunc func(ctx context.Context, kindID uuid.UUID, versionTag string) error

	// FindVersionByImageIDInOrgFunc mocks the FindVersionByImageIDInOrg method.
	FindVersionByImageIDInOrgFunc func(ctx context.Context, orgName string, imageID string) (*models.AgentKindVersion, error)

	// GetKindFunc mocks the GetKind method.
	GetKindFunc func(ctx context.Context, orgName string, kindName string) (*models.AgentKind, error)

	// GetVersionFunc mocks the GetVersion method.
	GetVersionFunc func(ctx context.Context, kindID uuid.UUID, versionTag string) (*models.AgentKindVersion, error)

	// GetVersionByImageIDFunc mocks the GetVersionByImageID method.
	GetVersionByImageIDFunc func(ctx context.Context, kindID uuid.UUID, imageID string) (*models.AgentKindVersion, error)

	// ListKindsFunc mocks the ListKinds method.
	ListKindsFunc func(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentKind, int64, error)

	// ListVersionsFunc mocks the ListVersions method.
	ListVersionsFunc func(ctx context.Context, kindID uuid.UUID) ([]models.AgentKindVersion, error)

	// UpdateKindFunc mocks the UpdateKind method.
	UpdateKindFunc func(ctx context.Context, kind *models.AgentKind) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateKind holds details about calls to the CreateKind method.
		CreateKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Kind is the kind argument value.
			Kind *models.AgentKind
		}
		// CreateVersion holds details about calls to the CreateVersion method.
		CreateVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Version is the version argument value.
			Version *models.AgentKindVersion
		}
		// DeleteKind holds details about calls to the DeleteKind method.
		DeleteKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// KindName is the kindName argument value.
			KindName string
		}
		// DeleteVersion holds details about calls to the DeleteVersion method.
		DeleteVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KindID is the kindID argument value.
			KindID uuid.UUID
			// VersionTag is the versionTag argument value.
			VersionTag string
		}
		// FindVersionByImageIDInOrg holds details about calls to the FindVersionByImageIDInOrg method.
		FindVersionByImageIDInOrg []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ImageID is the imageID argument value.
			ImageID string
		}
		// GetKind holds details about calls to the GetKind method.
		GetKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// KindName is the kindName argument value.
			KindName string
		}
		// GetVersion holds details about calls to the GetVersion method.
		GetVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KindID is the kindID argument value.
			KindID uuid.UUID
			// VersionTag is the versionTag argument value.
			VersionTag string
		}
		// GetVersionByImageID holds details about calls to the GetVersionByImageID method.
		GetVersionByImageID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KindID is the kindID argument value.
			KindID uuid.UUID
			// ImageID is the imageID argument value.
			ImageID string
		}
		// ListKinds holds details about calls to the ListKinds method.
		ListKinds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListVersions holds details about calls to the ListVersions method.
		ListVersions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KindID is the kindID argument value.
			KindID uuid.UUID
		}
		// UpdateKind holds details about calls to the UpdateKind method.
		UpdateKind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Kind is the kind argument value.
			Kind *models.AgentKind
		}
	}
	lockCreateKind                sync.RWMutex
	lockCreateVersion             sync.RWMutex
	lockDeleteKind                sync.RWMutex
	lockDeleteVersion             sync.RWMutex
	lockFindVersionByImageIDInOrg sync.RWMutex
	lockGetKind                   sync.RWMutex
	lockGetVersion                sync.RWMutex
	lockGetVersionByImageID       sync.RWMutex
	lockListKinds                 sync.RWMutex
	lockListVersions              sync.RWMutex
	lockUpdateKind                sync.RWMutex
}

// CreateKind calls CreateKindFunc.
func (mock *AgentKindRepositoryMock) CreateKind(ctx context.Context, kind *models.AgentKind) error {
	if mock.CreateKindFunc == nil {
		panic("AgentKindRepositoryMock.CreateKindFunc: method is nil but AgentKindRepository.CreateKind was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Kind *models.AgentKind
	}{
		Ctx:  ctx,
		Kind: kind,
	}
	mock.lockCreateKind.Lock()
	mock.calls.CreateKind = append(mock.calls.CreateKind, callInfo)
	mock.lockCreateKind.Unlock()
	return mock.CreateKindFunc(ctx, kind)
}

// CreateKindCalls gets all the calls that were made to CreateKind.
// Check the length with:
//
//	len(mockedAgentKindRepository.CreateKindCalls())
func (mock *AgentKindRepositoryMock) CreateKindCalls() []struct {
	Ctx  context.Context
	Kind *models.AgentKind
} {
	var calls []struct {
		Ctx  context.Context
		Kind *models.AgentKind
	}
	mock.lockCreateKind.RLock()
	calls = mock.calls.CreateKind
	mock.lockCreateKind.RUnlock()
	return calls
}

// CreateVersion calls CreateVersionFunc.
func (mock *AgentKindRepositoryMock) CreateVersion(ctx context.Context, version *models.AgentKindVersion) error {
	if mock.CreateVersionFunc == nil {
		panic("AgentKindRepositoryMock.CreateVersionFunc: method is nil but AgentKindRepository.CreateVersion was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Version *models.AgentKindVersion
	}{
		Ctx:     ctx,
		Version: version,
	}
	mock.lockCreateVersion.Lock()
	mock.calls.CreateVersion = append(mock.calls.CreateVersion, callInfo)
	mock.lockCreateVersion.Unlock()
	return mock.CreateVersionFunc(ctx, version)
}

// CreateVersionCalls gets all the calls that were made to CreateVersion.
// Check the length with:
//
//	len(mockedAgentKindRepository.CreateVersionCalls())
func (mock *AgentKindRepositoryMock) CreateVersionCalls() []struct {
	Ctx     context.Context
	Version *models.AgentKindVersion
} {
	var calls []struct {
		Ctx     context.Context
		Version *models.AgentKindVersion
	}
	mock.lockCreateVersion.RLock()
	calls = mock.calls.CreateVersion
	mock.lockCreateVersion.RUnlock()
	return calls
}

// DeleteKind calls DeleteKindFunc.
func (mock *AgentKindRepositoryMock) DeleteKind(ctx context.Context, orgName string, kindName string) error {
	if mock.DeleteKindFunc == nil {
		panic("AgentKindRepositoryMock.DeleteKindFunc: method is nil but AgentKindRepository.DeleteKind was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		KindName string
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		KindName: kindName,
	}
	mock.lockDeleteKind.Lock()
	mock.calls.DeleteKind = append(mock.calls.DeleteKind, callInfo)
	mock.lockDeleteKind.Unlock()
	return mock.DeleteKindFunc(ctx, orgName, kindName)
}

// DeleteKindCalls gets all the calls that were made to DeleteKind.
// Check the length with:
//
//	len(mockedAgentKindRepository.DeleteKindCalls())
func (mock *AgentKindRepositoryMock) DeleteKindCalls() []struct {
	Ctx      context.Context
	OrgName  string
	KindName string
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		KindName string
	}
	mock.lockDeleteKind.RLock()
	calls = mock.calls.DeleteKind
	mock.lockDeleteKind.RUnlock()
	return calls
}

// DeleteVersion calls DeleteVersionFunc.
func (mock *AgentKindRepositoryMock) DeleteVersion(ctx context.Context, kindID uuid.UUID, versionTag string) error {
	if mock.DeleteVersionFunc == nil {
		panic("AgentKindRepositoryMock.DeleteVersionFunc: method is nil but AgentKindRepository.DeleteVersion was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		KindID     uuid.UUID
		VersionTag string
	}{
		Ctx:        ctx,
		KindID:     kindID,
		VersionTag: versionTag,
	}
	mock.lockDeleteVersion.Lock()
	mock.calls.DeleteVersion = append(mock.calls.DeleteVersion, callInfo)
	mock.lockDeleteVersion.Unlock()
	return mock.DeleteVersionFunc(ctx, kindID, versionTag)
}

// DeleteVersionCalls gets all the calls that were made to DeleteVersion.
// Check the length with:
//
//	len(mockedAgentKindRepository.DeleteVersionCalls())
func (mock *AgentKindRepositoryMock) DeleteVersionCalls() []struct {
	Ctx        context.Context
	KindID     uuid.UUID
	VersionTag string
} {
	var calls []struct {
		Ctx        context.Context
		KindID     uuid.UUID
		VersionTag string
	}
	mock.lockDeleteVersion.RLock()
	calls = mock.calls.DeleteVersion
	mock.lockDeleteVersion.RUnlock()
	return calls
}

// FindVersionByImageIDInOrg calls FindVersionByImageIDInOrgFunc.
func (mock *AgentKindRepositoryMock) FindVersionByImageIDInOrg(ctx context.Context, orgName string, imageID string) (*models.AgentKindVersion, error) {
	if mock.FindVersionByImageIDInOrgFunc == nil {
		panic("AgentKindRepositoryMock.FindVersionByImageIDInOrgFunc: method is nil but AgentKindRepository.FindVersionByImageIDInOrg was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		ImageID string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		ImageID: imageID,
	}
	mock.lockFindVersionByImageIDInOrg.Lock()
	mock.calls.FindVersionByImageIDInOrg = append(mock.calls.FindVersionByImageIDInOrg, callInfo)
	mock.lockFindVersionByImageIDInOrg.Unlock()
	return mock.FindVersionByImageIDInOrgFunc(ctx, orgName, imageID)
}

// FindVersionByImageIDInOrgCalls gets all the calls that were made to FindVersionByImageIDInOrg.
// Check the length with:
//
//	len(mockedAgentKindRepository.FindVersionByImageIDInOrgCalls())
func (mock *AgentKindRepositoryMock) FindVersionByImageIDInOrgCalls() []struct {
	Ctx     context.Context
	OrgName string
	ImageID string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		ImageID string
	}
	mock.lockFindVersionByImageIDInOrg.RLock()
	calls = mock.calls.FindVersionByImageIDInOrg
	mock.lockFindVersionByImageIDInOrg.RUnlock()
	return calls
}

// GetKind calls GetKindFunc.
func (mock *AgentKindRepositoryMock) GetKind(ctx context.Context, orgName string, kindName string) (*models.AgentKind, error) {
	if mock.GetKindFunc == nil {
		panic("AgentKindRepositoryMock.GetKindFunc: method is nil but AgentKindRepository.GetKind was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgName  string
		KindName string
	}{
		Ctx:      ctx,
		OrgName:  orgName,
		KindName: kindName,
	}
	mock.lockGetKind.Lock()
	mock.calls.GetKind = append(mock.calls.GetKind, callInfo)
	mock.lockGetKind.Unlock()
	return mock.GetKindFunc(ctx, orgName, kindName)
}

// GetKindCalls gets all the calls that were made to GetKind.
// Check the length with:
//
//	len(mockedAgentKindRepository.GetKindCalls())
func (mock *AgentKindRepositoryMock) GetKindCalls() []struct {
	Ctx      context.Context
	OrgName  string
	KindName string
} {
	var calls []struct {
		Ctx      context.Context
		OrgName  string
		KindName string
	}
	mock.lockGetKind.RLock()
	calls = mock.calls.GetKind
	mock.lockGetKind.RUnlock()
	return calls
}

// GetVersion calls GetVersionFunc.
func (mock *AgentKindRepositoryMock) GetVersion(ctx context.Context, kindID uuid.UUID, versionTag string) (*models.AgentKindVersion, error) {
	if mock.GetVersionFunc == nil {
		panic("AgentKindRepositoryMock.GetVersionFunc: method is nil but AgentKindRepository.GetVersion was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		KindID     uuid.UUID
		VersionTag string
	}{
		Ctx:        ctx,
		KindID:     kindID,
		VersionTag: versionTag,
	}
	mock.lockGetVersion.Lock()
	mock.calls.GetVersion = append(mock.calls.GetVersion, callInfo)
	mock.lockGetVersion.Unlock()
	return mock.GetVersionFunc(ctx, kindID, versionTag)
}

// GetVersionCalls gets all the calls that were made to GetVersion.
// Check the length with:
//
//	len(mockedAgentKindRepository.GetVersionCalls())
func (mock *AgentKindRepositoryMock) GetVersionCalls() []struct {
	Ctx        context.Context
	KindID     uuid.UUID
	VersionTag string
} {
	var calls []struct {
		Ctx        context.Context
		KindID     uuid.UUID
		VersionTag string
	}
	mock.lockGetVersion.RLock()
	calls = mock.calls.GetVersion
	mock.lockGetVersion.RUnlock()
	return calls
}

// GetVersionByImageID calls GetVersionByImageIDFunc.
func (mock *AgentKindRepositoryMock) GetVersionByImageID(ctx context.Context, kindID uuid.UUID, imageID string) (*models.AgentKindVersion, error) {
	if mock.GetVersionByImageIDFunc == nil {
		panic("AgentKindRepositoryMock.GetVersionByImageIDFunc: method is nil but AgentKindRepository.GetVersionByImageID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		KindID  uuid.UUID
		ImageID string
	}{
		Ctx:     ctx,
		KindID:  kindID,
		ImageID: imageID,
	}
	mock.lockGetVersionByImageID.Lock()
	mock.calls.GetVersionByImageID = append(mock.calls.GetVersionByImageID, callInfo)
	mock.lockGetVersionByImageID.Unlock()
	return mock.GetVersionByImageIDFunc(ctx, kindID, imageID)
}

// GetVersionByImageIDCalls gets all the calls that were made to GetVersionByImageID.
// Check the length with:
//
//	len(mockedAgentKindRepository.GetVersionByImageIDCalls())
func (mock *AgentKindRepositoryMock) GetVersionByImageIDCalls() []struct {
	Ctx     context.Context
	KindID  uuid.UUID
	ImageID string
} {
	var calls []struct {
		Ctx     context.Context
		KindID  uuid.UUID
		ImageID string
	}
	mock.lockGetVersionByImageID.RLock()
	calls = mock.calls.GetVersionByImageID
	mock.lockGetVersionByImageID.RUnlock()
	return calls
}

// ListKinds calls ListKindsFunc.
func (mock *AgentKindRepositoryMock) ListKinds(ctx context.Context, orgName string, limit int, offset int) ([]models.AgentKind, int64, error) {
	if mock.ListKindsFunc == nil {
		panic("AgentKindRepositoryMock.ListKindsFunc: method is nil but AgentKindRepository.ListKinds was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Offset  int
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockListKinds.Lock()
	mock.calls.ListKinds = append(mock.calls.ListKinds, callInfo)
	mock.lockListKinds.Unlock()
	return mock.ListKindsFunc(ctx, orgName, limit, offset)
}

// ListKindsCalls gets all the calls that were made to ListKinds.
// Check the length with:
//
//	len(mockedAgentKindRepository.ListKindsCalls())
func (mock *AgentKindRepositoryMock) ListKindsCalls() []struct {
	Ctx     context.Context
	OrgName string
	Limit   int
	Offset  int
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Limit   int
		Offset  int
	}
	mock.lockListKinds.RLock()
	calls = mock.calls.ListKinds
	mock.lockListKinds.RUnlock()
	return calls
}

// ListVersions calls ListVersionsFunc.
func (mock *AgentKindRepositoryMock) ListVersions(ctx context.Context, kindID uuid.UUID) ([]models.AgentKindVersion, error) {
	if mock.ListVersionsFunc == nil {
		panic("AgentKindRepositoryMock.ListVersionsFunc: method is nil but AgentKindRepository.ListVersions was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		KindID uuid.UUID
	}{
		Ctx:    ctx,
		KindID: kindID,
	}
	mock.lockListVersions.Lock()
	mock.calls.ListVersions = append(mock.calls.ListVersions, callInfo)
	mock.lockListVersions.Unlock()
	return mock.ListVersionsFunc(ctx, kindID)
}

// ListVersionsCalls gets all the calls that were made to ListVersions.
// Check the length with:
//
//	len(mockedAgentKindRepository.ListVersionsCalls())
func (mock *AgentKindRepositoryMock) ListVersionsCalls() []struct {
	Ctx    context.Context
	KindID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		KindID uuid.UUID
	}
	mock.lockListVersions.RLock()
	calls = mock.calls.ListVersions
	mock.lockListVersions.RUnlock()
	return calls
}

// UpdateKind calls UpdateKindFunc.
func (mock *AgentKindRepositoryMock) UpdateKind(ctx context.Context, kind *models.AgentKind) error {
	if mock.UpdateKindFunc == nil {
		panic("AgentKindRepositoryMock.UpdateKindFunc: method is nil but AgentKindRepository.UpdateKind was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Kind *models.AgentKind
	}{
		Ctx:  ctx,
		Kind: kind,
	}
	mock.lockUpdateKind.Lock()
	mock.calls.UpdateKind = append(mock.calls.UpdateKind, callInfo)
	mock.lockUpdateKind.Unlock()
	return mock.UpdateKindFunc(ctx, kind)
}

// UpdateKindCalls gets all the calls that were made to UpdateKind.
// Check the length with:
//
//	len(mockedAgentKindRepository.UpdateKindCalls())
func (mock *AgentKindRepositoryMock) UpdateKindCalls() []struct {
	Ctx  context.Context
	Kind *models.AgentKind
} {
	var calls []struct {
		Ctx  context.Context
		Kind *models.AgentKind
	}
	mock.lockUpdateKind.RLock()
	calls = mock.calls.UpdateKind
	mock.lockUpdateKind.RUnlock()
	return calls
}
