// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// AgentEnvConfigVariableRepositoryMock is a mock implementation of repositories.AgentEnvConfigVariableRepository.
//
//	func TestSomethingThatUsesAgentEnvConfigVariableRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AgentEnvConfigVariableRepository
//		mockedAgentEnvConfigVariableRepository := &AgentEnvConfigVariableRepositoryMock{
//			CreateBatchFunc: func(ctx context.Context, tx *gorm.DB, variables []models.AgentEnvConfigVariable) error {
//				panic("mock out the CreateBatch method")
//			},
//			DeleteByConfigFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
//				panic("mock out the DeleteByConfig method")
//			},
//			DeleteByConfigAndEnvFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, envUUID uuid.UUID) error {
//				panic("mock out the DeleteByConfigAndEnv method")
//			},
//			ListByConfigFunc: func(ctx context.Context, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
//				panic("mock out the ListByConfig method")
//			},
//			ListByConfigAndEnvFunc: func(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
//				panic("mock out the ListByConfigAndEnv method")
//			},
//			ListByConfigForUpdateFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
//				panic("mock out the ListByConfigForUpdate method")
//			},
//			ListSecretReferencesByAgentAndEnvFunc: func(ctx context.Context, agentID string, orgName string, envUUID uuid.UUID) ([]string, error) {
//				panic("mock out the ListSecretReferencesByAgentAndEnv method")
//			},
//			UpdateVariableNamesFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, keyNameMap map[string]string) error {
//				panic("mock out the UpdateVariableNames method")
//			},
//		}
//
//		// use mockedAgentEnvConfigVariableRepository in code that requires repositories.AgentEnvConfigVariableRepository
//		// and then make assertions.
//
//	}
type AgentEnvConfigVariableRepositoryMock struct {
	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, tx *gorm.DB, variables []models.AgentEnvConfigVariable) error

	// DeleteByConfigFunc mocks the DeleteByConfig method.
	DeleteByConfigFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error

	// DeleteByConfigAndEnvFunc mocks the DeleteByConfigAndEnv method.
	DeleteByConfigAndEnvFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, envUUID uuid.UUID) error

	// ListByConfigFunc mocks the ListByConfig method.
	ListByConfigFunc func(ctx context.Context, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error)

	// ListByConfigAndEnvFunc mocks the ListByConfigAndEnv method.
	ListByConfigAndEnvFunc func(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error)

	// ListByConfigForUpdateFunc mocks the ListByConfigForUpdate method.
	ListByConfigForUpdateFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error)

	// ListSecretReferencesByAgentAndEnvFunc mocks the ListSecretReferencesByAgentAndEnv method.
	ListSecretReferencesByAgentAndEnvFunc func(ctx context.Context, agentID string, orgName string, envUUID uuid.UUID) ([]string, error)

	// UpdateVariableNamesFunc mocks the UpdateVariableNames method.
	UpdateVariableNamesFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, keyNameMap map[string]string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Variables is the variables argument value.
			Variables []models.AgentEnvConfigVariable
		}
		// DeleteByConfig holds details about calls to the DeleteByConfig method.
		DeleteByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// DeleteByConfigAndEnv holds details about calls to the DeleteByConfigAndEnv method.
		DeleteByConfigAndEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// EnvUUID is the envUUID argument value.
			EnvUUID uuid.UUID
		}
		// ListByConfig holds details about calls to the ListByConfig method.
		ListByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// ListByConfigAndEnv holds details about calls to the ListByConfigAndEnv method.
		ListByConfigAndEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// EnvUUID is the envUUID argument value.
			EnvUUID uuid.UUID
		}
		// ListByConfigForUpdate holds details about calls to the ListByConfigForUpdate method.
		ListByConfigForUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// ListSecretReferencesByAgentAndEnv holds details about calls to the ListSecretReferencesByAgentAndEnv method.
		ListSecretReferencesByAgentAndEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AgentID is the agentID argument value.
			AgentID string
			// OrgName is the orgName argument value.
			OrgName string
			// EnvUUID is the envUUID argument value.
			EnvUUID uuid.UUID
		}
		// UpdateVariableNames holds details about calls to the UpdateVariableNames method.
		UpdateVariableNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// KeyNameMap is the keyNameMap argument value.
			KeyNameMap map[string]string
		}
	}
	lockCreateBatch                       sync.RWMutex
	lockDeleteByConfig                    sync.RWMutex
	lockDeleteByConfigAndEnv              sync.RWMutex
	lockListByConfig                      sync.RWMutex
	lockListByConfigAndEnv                sync.RWMutex
	lockListByConfigForUpdate             sync.RWMutex
	lockListSecretReferencesByAgentAndEnv sync.RWMutex
	lockUpdateVariableNames               sync.RWMutex
}

// CreateBatch calls CreateBatchFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) CreateBatch(ctx context.Context, tx *gorm.DB, variables []models.AgentEnvConfigVariable) error {
	if mock.CreateBatchFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.CreateBatchFunc: method is nil but AgentEnvConfigVariableRepository.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        *gorm.DB
		Variables []models.AgentEnvConfigVariable
	}{
		Ctx:       ctx,
		Tx:        tx,
		Variables: variables,
	}
	mock.lockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	mock.lockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, tx, variables)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.CreateBatchCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) CreateBatchCalls() []struct {
	Ctx       context.Context
	Tx        *gorm.DB
	Variables []models.AgentEnvConfigVariable
} {
	var calls []struct {
		Ctx       context.Context
		Tx        *gorm.DB
		Variables []models.AgentEnvConfigVariable
	}
	mock.lockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	mock.lockCreateBatch.RUnlock()
	return calls
}

// DeleteByConfig calls DeleteByConfigFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) DeleteByConfig(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
	if mock.DeleteByConfigFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.DeleteByConfigFunc: method is nil but AgentEnvConfigVariableRepository.DeleteByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
	}
	mock.lockDeleteByConfig.Lock()
	mock.calls.DeleteByConfig = append(mock.calls.DeleteByConfig, callInfo)
	mock.lockDeleteByConfig.Unlock()
	return mock.DeleteByConfigFunc(ctx, tx, configUUID)
}

// DeleteByConfigCalls gets all the calls that were made to DeleteByConfig.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.DeleteByConfigCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) DeleteByConfigCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}
	mock.lockDeleteByConfig.RLock()
	calls = mock.calls.DeleteByConfig
	mock.lockDeleteByConfig.RUnlock()
	return calls
}

// DeleteByConfigAndEnv calls DeleteByConfigAndEnvFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) DeleteByConfigAndEnv(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, envUUID uuid.UUID) error {
	if mock.DeleteByConfigAndEnvFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.DeleteByConfigAndEnvFunc: method is nil but AgentEnvConfigVariableRepository.DeleteByConfigAndEnv was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
		EnvUUID:    envUUID,
	}
	mock.lockDeleteByConfigAndEnv.Lock()
	mock.calls.DeleteByConfigAndEnv = append(mock.calls.DeleteByConfigAndEnv, callInfo)
	mock.lockDeleteByConfigAndEnv.Unlock()
	return mock.DeleteByConfigAndEnvFunc(ctx, tx, configUUID, envUUID)
}

// DeleteByConfigAndEnvCalls gets all the calls that were made to DeleteByConfigAndEnv.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.DeleteByConfigAndEnvCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) DeleteByConfigAndEnvCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
	EnvUUID    uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}
	mock.lockDeleteByConfigAndEnv.RLock()
	calls = mock.calls.DeleteByConfigAndEnv
	mock.lockDeleteByConfigAndEnv.RUnlock()
	return calls
}

// ListByConfig calls ListByConfigFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfig(ctx context.Context, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
	if mock.ListByConfigFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.ListByConfigFunc: method is nil but AgentEnvConfigVariableRepository.ListByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
	}
	mock.lockListByConfig.Lock()
	mock.calls.ListByConfig = append(mock.calls.ListByConfig, callInfo)
	mock.lockListByConfig.Unlock()
	return mock.ListByConfigFunc(ctx, configUUID)
}

// ListByConfigCalls gets all the calls that were made to ListByConfig.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.ListByConfigCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfigCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}
	mock.lockListByConfig.RLock()
	calls = mock.calls.ListByConfig
	mock.lockListByConfig.RUnlock()
	return calls
}

// ListByConfigAndEnv calls ListByConfigAndEnvFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfigAndEnv(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
	if mock.ListByConfigAndEnvFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.ListByConfigAndEnvFunc: method is nil but AgentEnvConfigVariableRepository.ListByConfigAndEnv was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
		EnvUUID:    envUUID,
	}
	mock.lockListByConfigAndEnv.Lock()
	mock.calls.ListByConfigAndEnv = append(mock.calls.ListByConfigAndEnv, callInfo)
	mock.lockListByConfigAndEnv.Unlock()
	return mock.ListByConfigAndEnvFunc(ctx, configUUID, envUUID)
}

// ListByConfigAndEnvCalls gets all the calls that were made to ListByConfigAndEnv.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.ListByConfigAndEnvCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfigAndEnvCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
	EnvUUID    uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}
	mock.lockListByConfigAndEnv.RLock()
	calls = mock.calls.ListByConfigAndEnv
	mock.lockListByConfigAndEnv.RUnlock()
	return calls
}

// ListByConfigForUpdate calls ListByConfigForUpdateFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfigForUpdate(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) ([]models.AgentEnvConfigVariable, error) {
	if mock.ListByConfigForUpdateFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.ListByConfigForUpdateFunc: method is nil but AgentEnvConfigVariableRepository.ListByConfigForUpdate was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
	}
	mock.lockListByConfigForUpdate.Lock()
	mock.calls.ListByConfigForUpdate = append(mock.calls.ListByConfigForUpdate, callInfo)
	mock.lockListByConfigForUpdate.Unlock()
	return mock.ListByConfigForUpdateFunc(ctx, tx, configUUID)
}

// ListByConfigForUpdateCalls gets all the calls that were made to ListByConfigForUpdate.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.ListByConfigForUpdateCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) ListByConfigForUpdateCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}
	mock.lockListByConfigForUpdate.RLock()
	calls = mock.calls.ListByConfigForUpdate
	mock.lockListByConfigForUpdate.RUnlock()
	return calls
}

// ListSecretReferencesByAgentAndEnv calls ListSecretReferencesByAgentAndEnvFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) ListSecretReferencesByAgentAndEnv(ctx context.Context, agentID string, orgName string, envUUID uuid.UUID) ([]string, error) {
	if mock.ListSecretReferencesByAgentAndEnvFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.ListSecretReferencesByAgentAndEnvFunc: method is nil but AgentEnvConfigVariableRepository.ListSecretReferencesByAgentAndEnv was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AgentID string
		OrgName string
		EnvUUID uuid.UUID
	}{
		Ctx:     ctx,
		AgentID: agentID,
		OrgName: orgName,
		EnvUUID: envUUID,
	}
	mock.lockListSecretReferencesByAgentAndEnv.Lock()
	mock.calls.ListSecretReferencesByAgentAndEnv = append(mock.calls.ListSecretReferencesByAgentAndEnv, callInfo)
	mock.lockListSecretReferencesByAgentAndEnv.Unlock()
	return mock.ListSecretReferencesByAgentAndEnvFunc(ctx, agentID, orgName, envUUID)
}

// ListSecretReferencesByAgentAndEnvCalls gets all the calls that were made to ListSecretReferencesByAgentAndEnv.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.ListSecretReferencesByAgentAndEnvCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) ListSecretReferencesByAgentAndEnvCalls() []struct {
	Ctx     context.Context
	AgentID string
	OrgName string
	EnvUUID uuid.UUID
} {
	var calls []struct {
		Ctx     context.Context
		AgentID string
		OrgName string
		EnvUUID uuid.UUID
	}
	mock.lockListSecretReferencesByAgentAndEnv.RLock()
	calls = mock.calls.ListSecretReferencesByAgentAndEnv
	mock.lockListSecretReferencesByAgentAndEnv.RUnlock()
	return calls
}

// UpdateVariableNames calls UpdateVariableNamesFunc.
func (mock *AgentEnvConfigVariableRepositoryMock) UpdateVariableNames(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID, keyNameMap map[string]string) error {
	if mock.UpdateVariableNamesFunc == nil {
		panic("AgentEnvConfigVariableRepositoryMock.UpdateVariableNamesFunc: method is nil but AgentEnvConfigVariableRepository.UpdateVariableNames was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		KeyNameMap map[string]string
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
		KeyNameMap: keyNameMap,
	}
	mock.lockUpdateVariableNames.Lock()
	mock.calls.UpdateVariableNames = append(mock.calls.UpdateVariableNames, callInfo)
	mock.lockUpdateVariableNames.Unlock()
	return mock.UpdateVariableNamesFunc(ctx, tx, configUUID, keyNameMap)
}

// UpdateVariableNamesCalls gets all the calls that were made to UpdateVariableNames.
// Check the length with:
//
//	len(mockedAgentEnvConfigVariableRepository.UpdateVariableNamesCalls())
func (mock *AgentEnvConfigVariableRepositoryMock) UpdateVariableNamesCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
	KeyNameMap map[string]string
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
		KeyNameMap map[string]string
	}
	mock.lockUpdateVariableNames.RLock()
	calls = mock.calls.UpdateVariableNames
	mock.lockUpdateVariableNames.RUnlock()
	return calls
}
