// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// AgentConfigRepositoryMock is a mock implementation of repositories.AgentConfigRepository.
//
//	func TestSomethingThatUsesAgentConfigRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AgentConfigRepository
//		mockedAgentConfigRepository := &AgentConfigRepositoryMock{
//			DeleteAllByAgentFunc: func(orgName string, projectName string, agentName string) error {
//				panic("mock out the DeleteAllByAgent method")
//			},
//			GetFunc: func(orgName string, projectName string, agentName string, environmentName string) (*models.AgentConfig, error) {
//				panic("mock out the Get method")
//			},
//			UpsertFunc: func(config *models.AgentConfig) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedAgentConfigRepository in code that requires repositories.AgentConfigRepository
//		// and then make assertions.
//
//	}
type AgentConfigRepositoryMock struct {
	// DeleteAllByAgentFunc mocks the DeleteAllByAgent method.
	DeleteAllByAgentFunc func(orgName string, projectName string, agentName string) error

	// GetFunc mocks the Get method.
	GetFunc func(orgName string, projectName string, agentName string, environmentName string) (*models.AgentConfig, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(config *models.AgentConfig) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteAllByAgent holds details about calls to the DeleteAllByAgent method.
		DeleteAllByAgent []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// EnvironmentName is the environmentName argument value.
			EnvironmentName string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Config is the config argument value.
			Config *models.AgentConfig
		}
	}
	lockDeleteAllByAgent sync.RWMutex
	lockGet              sync.RWMutex
	lockUpsert           sync.RWMutex
}

// DeleteAllByAgent calls DeleteAllByAgentFunc.
func (mock *AgentConfigRepositoryMock) DeleteAllByAgent(orgName string, projectName string, agentName string) error {
	if mock.DeleteAllByAgentFunc == nil {
		panic("AgentConfigRepositoryMock.DeleteAllByAgentFunc: method is nil but AgentConfigRepository.DeleteAllByAgent was just called")
	}
	callInfo := struct {
		OrgName     string
		ProjectName string
		AgentName   string
	}{
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockDeleteAllByAgent.Lock()
	mock.calls.DeleteAllByAgent = append(mock.calls.DeleteAllByAgent, callInfo)
	mock.lockDeleteAllByAgent.Unlock()
	return mock.DeleteAllByAgentFunc(orgName, projectName, agentName)
}

// DeleteAllByAgentCalls gets all the calls that were made to DeleteAllByAgent.
// Check the length with:
//
//	len(mockedAgentConfigRepository.DeleteAllByAgentCalls())
func (mock *AgentConfigRepositoryMock) DeleteAllByAgentCalls() []struct {
	OrgName     string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		OrgName     string
		ProjectName string
		AgentName   string
	}
	mock.lockDeleteAllByAgent.RLock()
	calls = mock.calls.DeleteAllByAgent
	mock.lockDeleteAllByAgent.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *AgentConfigRepositoryMock) Get(orgName string, projectName string, agentName string, environmentName string) (*models.AgentConfig, error) {
	if mock.GetFunc == nil {
		panic("AgentConfigRepositoryMock.GetFunc: method is nil but AgentConfigRepository.Get was just called")
	}
	callInfo := struct {
		OrgName         string
		ProjectName     string
		AgentName       string
		EnvironmentName string
	}{
		OrgName:         orgName,
		ProjectName:     projectName,
		AgentName:       agentName,
		EnvironmentName: environmentName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(orgName, projectName, agentName, environmentName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedAgentConfigRepository.GetCalls())
func (mock *AgentConfigRepositoryMock) GetCalls() []struct {
	OrgName         string
	ProjectName     string
	AgentName       string
	EnvironmentName string
} {
	var calls []struct {
		OrgName         string
		ProjectName     string
		AgentName       string
		EnvironmentName string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *AgentConfigRepositoryMock) Upsert(config *models.AgentConfig) error {
	if mock.UpsertFunc == nil {
		panic("AgentConfigRepositoryMock.UpsertFunc: method is nil but AgentConfigRepository.Upsert was just called")
	}
	callInfo := struct {
		Config *models.AgentConfig
	}{
		Config: config,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(config)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedAgentConfigRepository.UpsertCalls())
func (mock *AgentConfigRepositoryMock) UpsertCalls() []struct {
	Config *models.AgentConfig
} {
	var calls []struct {
		Config *models.AgentConfig
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
