// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// AIApplicationRepositoryMock is a mock implementation of repositories.AIApplicationRepository.
//
//	func TestSomethingThatUsesAIApplicationRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.AIApplicationRepository
//		mockedAIApplicationRepository := &AIApplicationRepositoryMock{
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, app *models.AIApplication) (bool, error) {
//				panic("mock out the Create method")
//			},
//			DeleteByAgentFunc: func(ctx context.Context, orgName string, projectName string, agentID string) error {
//				panic("mock out the DeleteByAgent method")
//			},
//			DeleteByAgentEnvFunc: func(ctx context.Context, tx *gorm.DB, orgName string, projectName string, agentID string, envName string) error {
//				panic("mock out the DeleteByAgentEnv method")
//			},
//			GetByAgentEnvFunc: func(ctx context.Context, orgName string, projectName string, agentID string, envName string) (*models.AIApplication, error) {
//				panic("mock out the GetByAgentEnv method")
//			},
//			ListByAgentFunc: func(ctx context.Context, orgName string, projectName string, agentID string) ([]models.AIApplication, error) {
//				panic("mock out the ListByAgent method")
//			},
//			ListByOrgFunc: func(ctx context.Context, orgName string) ([]models.AIApplication, error) {
//				panic("mock out the ListByOrg method")
//			},
//		}
//
//		// use mockedAIApplicationRepository in code that requires repositories.AIApplicationRepository
//		// and then make assertions.
//
//	}
type AIApplicationRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, app *models.AIApplication) (bool, error)

	// DeleteByAgentFunc mocks the DeleteByAgent method.
	DeleteByAgentFunc func(ctx context.Context, orgName string, projectName string, agentID string) error

	// DeleteByAgentEnvFunc mocks the DeleteByAgentEnv method.
	DeleteByAgentEnvFunc func(ctx context.Context, tx *gorm.DB, orgName string, projectName string, agentID string, envName string) error

	// GetByAgentEnvFunc mocks the GetByAgentEnv method.
	GetByAgentEnvFunc func(ctx context.Context, orgName string, projectName string, agentID string, envName string) (*models.AIApplication, error)

	// ListByAgentFunc mocks the ListByAgent method.
	ListByAgentFunc func(ctx context.Context, orgName string, projectName string, agentID string) ([]models.AIApplication, error)

	// ListByOrgFunc mocks the ListByOrg method.
	ListByOrgFunc func(ctx context.Context, orgName string) ([]models.AIApplication, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// App is the app argument value.
			App *models.AIApplication
		}
		// DeleteByAgent holds details about calls to the DeleteByAgent method.
		DeleteByAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentID is the agentID argument value.
			AgentID string
		}
		// DeleteByAgentEnv holds details about calls to the DeleteByAgentEnv method.
		DeleteByAgentEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentID is the agentID argument value.
			AgentID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// GetByAgentEnv holds details about calls to the GetByAgentEnv method.
		GetByAgentEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentID is the agentID argument value.
			AgentID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// ListByAgent holds details about calls to the ListByAgent method.
		ListByAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentID is the agentID argument value.
			AgentID string
		}
		// ListByOrg holds details about calls to the ListByOrg method.
		ListByOrg []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
	}
	lockCreate           sync.RWMutex
	lockDeleteByAgent    sync.RWMutex
	lockDeleteByAgentEnv sync.RWMutex
	lockGetByAgentEnv    sync.RWMutex
	lockListByAgent      sync.RWMutex
	lockListByOrg        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AIApplicationRepositoryMock) Create(ctx context.Context, tx *gorm.DB, app *models.AIApplication) (bool, error) {
	if mock.CreateFunc == nil {
		panic("AIApplicationRepositoryMock.CreateFunc: method is nil but AIApplicationRepository.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Tx  *gorm.DB
		App *models.AIApplication
	}{
		Ctx: ctx,
		Tx:  tx,
		App: app,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, app)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAIApplicationRepository.CreateCalls())
func (mock *AIApplicationRepositoryMock) CreateCalls() []struct {
	Ctx context.Context
	Tx  *gorm.DB
	App *models.AIApplication
} {
	var calls []struct {
		Ctx context.Context
		Tx  *gorm.DB
		App *models.AIApplication
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByAgent calls DeleteByAgentFunc.
func (mock *AIApplicationRepositoryMock) DeleteByAgent(ctx context.Context, orgName string, projectName string, agentID string) error {
	if mock.DeleteByAgentFunc == nil {
		panic("AIApplicationRepositoryMock.DeleteByAgentFunc: method is nil but AIApplicationRepository.DeleteByAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentID:     agentID,
	}
	mock.lockDeleteByAgent.Lock()
	mock.calls.DeleteByAgent = append(mock.calls.DeleteByAgent, callInfo)
	mock.lockDeleteByAgent.Unlock()
	return mock.DeleteByAgentFunc(ctx, orgName, projectName, agentID)
}

// DeleteByAgentCalls gets all the calls that were made to DeleteByAgent.
// Check the length with:
//
//	len(mockedAIApplicationRepository.DeleteByAgentCalls())
func (mock *AIApplicationRepositoryMock) DeleteByAgentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentID     string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
	}
	mock.lockDeleteByAgent.RLock()
	calls = mock.calls.DeleteByAgent
	mock.lockDeleteByAgent.RUnlock()
	return calls
}

// DeleteByAgentEnv calls DeleteByAgentEnvFunc.
func (mock *AIApplicationRepositoryMock) DeleteByAgentEnv(ctx context.Context, tx *gorm.DB, orgName string, projectName string, agentID string, envName string) error {
	if mock.DeleteByAgentEnvFunc == nil {
		panic("AIApplicationRepositoryMock.DeleteByAgentEnvFunc: method is nil but AIApplicationRepository.DeleteByAgentEnv was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Tx          *gorm.DB
		OrgName     string
		ProjectName string
		AgentID     string
		EnvName     string
	}{
		Ctx:         ctx,
		Tx:          tx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentID:     agentID,
		EnvName:     envName,
	}
	mock.lockDeleteByAgentEnv.Lock()
	mock.calls.DeleteByAgentEnv = append(mock.calls.DeleteByAgentEnv, callInfo)
	mock.lockDeleteByAgentEnv.Unlock()
	return mock.DeleteByAgentEnvFunc(ctx, tx, orgName, projectName, agentID, envName)
}

// DeleteByAgentEnvCalls gets all the calls that were made to DeleteByAgentEnv.
// Check the length with:
//
//	len(mockedAIApplicationRepository.DeleteByAgentEnvCalls())
func (mock *AIApplicationRepositoryMock) DeleteByAgentEnvCalls() []struct {
	Ctx         context.Context
	Tx          *gorm.DB
	OrgName     string
	ProjectName string
	AgentID     string
	EnvName     string
} {
	var calls []struct {
		Ctx         context.Context
		Tx          *gorm.DB
		OrgName     string
		ProjectName string
		AgentID     string
		EnvName     string
	}
	mock.lockDeleteByAgentEnv.RLock()
	calls = mock.calls.DeleteByAgentEnv
	mock.lockDeleteByAgentEnv.RUnlock()
	return calls
}

// GetByAgentEnv calls GetByAgentEnvFunc.
func (mock *AIApplicationRepositoryMock) GetByAgentEnv(ctx context.Context, orgName string, projectName string, agentID string, envName string) (*models.AIApplication, error) {
	if mock.GetByAgentEnvFunc == nil {
		panic("AIApplicationRepositoryMock.GetByAgentEnvFunc: method is nil but AIApplicationRepository.GetByAgentEnv was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
		EnvName     string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentID:     agentID,
		EnvName:     envName,
	}
	mock.lockGetByAgentEnv.Lock()
	mock.calls.GetByAgentEnv = append(mock.calls.GetByAgentEnv, callInfo)
	mock.lockGetByAgentEnv.Unlock()
	return mock.GetByAgentEnvFunc(ctx, orgName, projectName, agentID, envName)
}

// GetByAgentEnvCalls gets all the calls that were made to GetByAgentEnv.
// Check the length with:
//
//	len(mockedAIApplicationRepository.GetByAgentEnvCalls())
func (mock *AIApplicationRepositoryMock) GetByAgentEnvCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentID     string
	EnvName     string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
		EnvName     string
	}
	mock.lockGetByAgentEnv.RLock()
	calls = mock.calls.GetByAgentEnv
	mock.lockGetByAgentEnv.RUnlock()
	return calls
}

// ListByAgent calls ListByAgentFunc.
func (mock *AIApplicationRepositoryMock) ListByAgent(ctx context.Context, orgName string, projectName string, agentID string) ([]models.AIApplication, error) {
	if mock.ListByAgentFunc == nil {
		panic("AIApplicationRepositoryMock.ListByAgentFunc: method is nil but AIApplicationRepository.ListByAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		AgentID:     agentID,
	}
	mock.lockListByAgent.Lock()
	mock.calls.ListByAgent = append(mock.calls.ListByAgent, callInfo)
	mock.lockListByAgent.Unlock()
	return mock.ListByAgentFunc(ctx, orgName, projectName, agentID)
}

// ListByAgentCalls gets all the calls that were made to ListByAgent.
// Check the length with:
//
//	len(mockedAIApplicationRepository.ListByAgentCalls())
func (mock *AIApplicationRepositoryMock) ListByAgentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	AgentID     string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		AgentID     string
	}
	mock.lockListByAgent.RLock()
	calls = mock.calls.ListByAgent
	mock.lockListByAgent.RUnlock()
	return calls
}

// ListByOrg calls ListByOrgFunc.
func (mock *AIApplicationRepositoryMock) ListByOrg(ctx context.Context, orgName string) ([]models.AIApplication, error) {
	if mock.ListByOrgFunc == nil {
		panic("AIApplicationRepositoryMock.ListByOrgFunc: method is nil but AIApplicationRepository.ListByOrg was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockListByOrg.Lock()
	mock.calls.ListByOrg = append(mock.calls.ListByOrg, callInfo)
	mock.lockListByOrg.Unlock()
	return mock.ListByOrgFunc(ctx, orgName)
}

// ListByOrgCalls gets all the calls that were made to ListByOrg.
// Check the length with:
//
//	len(mockedAIApplicationRepository.ListByOrgCalls())
func (mock *AIApplicationRepositoryMock) ListByOrgCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockListByOrg.RLock()
	calls = mock.calls.ListByOrg
	mock.lockListByOrg.RUnlock()
	return calls
}
