// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// APIKeyRepositoryMock is a mock implementation of repositories.APIKeyRepository.
//
//	func TestSomethingThatUsesAPIKeyRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.APIKeyRepository
//		mockedAPIKeyRepository := &APIKeyRepositoryMock{
//			DeleteFunc: func(artifactUUID string, name string) error {
//				panic("mock out the Delete method")
//			},
//			GetByArtifactAndNameFunc: func(artifactUUID string, name string) (*models.StoredAPIKey, error) {
//				panic("mock out the GetByArtifactAndName method")
//			},
//			ListByApplicationUUIDFunc: func(applicationUUID string) ([]models.StoredAPIKey, error) {
//				panic("mock out the ListByApplicationUUID method")
//			},
//			ListByArtifactFunc: func(artifactUUID string) ([]models.StoredAPIKey, error) {
//				panic("mock out the ListByArtifact method")
//			},
//			ListByArtifactKindFunc: func(orgName string, kind string) ([]models.StoredAPIKey, error) {
//				panic("mock out the ListByArtifactKind method")
//			},
//			ListByArtifactKindAndEnvsFunc: func(orgName string, kind string, envUUIDs []string) ([]models.StoredAPIKey, error) {
//				panic("mock out the ListByArtifactKindAndEnvs method")
//			},
//			ListPermanentByArtifactKindFunc: func(orgName string, kind string) ([]models.StoredAPIKey, error) {
//				panic("mock out the ListPermanentByArtifactKind method")
//			},
//			UpsertFunc: func(key *models.StoredAPIKey) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedAPIKeyRepository in code that requires repositories.APIKeyRepository
//		// and then make assertions.
//
//	}
type APIKeyRepositoryMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(artifactUUID string, name string) error

	// GetByArtifactAndNameFunc mocks the GetByArtifactAndName method.
	GetByArtifactAndNameFunc func(artifactUUID string, name string) (*models.StoredAPIKey, error)

	// ListByApplicationUUIDFunc mocks the ListByApplicationUUID method.
	ListByApplicationUUIDFunc func(applicationUUID string) ([]models.StoredAPIKey, error)

	// ListByArtifactFunc mocks the ListByArtifact method.
	ListByArtifactFunc func(artifactUUID string) ([]models.StoredAPIKey, error)

	// ListByArtifactKindFunc mocks the ListByArtifactKind method.
	ListByArtifactKindFunc func(orgName string, kind string) ([]models.StoredAPIKey, error)

	// ListByArtifactKindAndEnvsFunc mocks the ListByArtifactKindAndEnvs method.
	ListByArtifactKindAndEnvsFunc func(orgName string, kind string, envUUIDs []string) ([]models.StoredAPIKey, error)

	// ListPermanentByArtifactKindFunc mocks the ListPermanentByArtifactKind method.
	ListPermanentByArtifactKindFunc func(orgName string, kind string) ([]models.StoredAPIKey, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(key *models.StoredAPIKey) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// Name is the name argument value.
			Name string
		}
		// GetByArtifactAndName holds details about calls to the GetByArtifactAndName method.
		GetByArtifactAndName []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// Name is the name argument value.
			Name string
		}
		// ListByApplicationUUID holds details about calls to the ListByApplicationUUID method.
		ListByApplicationUUID []struct {
			// ApplicationUUID is the applicationUUID argument value.
			ApplicationUUID string
		}
		// ListByArtifact holds details about calls to the ListByArtifact method.
		ListByArtifact []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
		}
		// ListByArtifactKind holds details about calls to the ListByArtifactKind method.
		ListByArtifactKind []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Kind is the kind argument value.
			Kind string
		}
		// ListByArtifactKindAndEnvs holds details about calls to the ListByArtifactKindAndEnvs method.
		ListByArtifactKindAndEnvs []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Kind is the kind argument value.
			Kind string
			// EnvUUIDs is the envUUIDs argument value.
			EnvUUIDs []string
		}
		// ListPermanentByArtifactKind holds details about calls to the ListPermanentByArtifactKind method.
		ListPermanentByArtifactKind []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Kind is the kind argument value.
			Kind string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Key is the key argument value.
			Key *models.StoredAPIKey
		}
	}
	lockDelete                      sync.RWMutex
	lockGetByArtifactAndName        sync.RWMutex
	lockListByApplicationUUID       sync.RWMutex
	lockListByArtifact              sync.RWMutex
	lockListByArtifactKind          sync.RWMutex
	lockListByArtifactKindAndEnvs   sync.RWMutex
	lockListPermanentByArtifactKind sync.RWMutex
	lockUpsert                      sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *APIKeyRepositoryMock) Delete(artifactUUID string, name string) error {
	if mock.DeleteFunc == nil {
		panic("APIKeyRepositoryMock.DeleteFunc: method is nil but APIKeyRepository.Delete was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		Name         string
	}{
		ArtifactUUID: artifactUUID,
		Name:         name,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(artifactUUID, name)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAPIKeyRepository.DeleteCalls())
func (mock *APIKeyRepositoryMock) DeleteCalls() []struct {
	ArtifactUUID string
	Name         string
} {
	var calls []struct {
		ArtifactUUID string
		Name         string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByArtifactAndName calls GetByArtifactAndNameFunc.
func (mock *APIKeyRepositoryMock) GetByArtifactAndName(artifactUUID string, name string) (*models.StoredAPIKey, error) {
	if mock.GetByArtifactAndNameFunc == nil {
		panic("APIKeyRepositoryMock.GetByArtifactAndNameFunc: method is nil but APIKeyRepository.GetByArtifactAndName was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		Name         string
	}{
		ArtifactUUID: artifactUUID,
		Name:         name,
	}
	mock.lockGetByArtifactAndName.Lock()
	mock.calls.GetByArtifactAndName = append(mock.calls.GetByArtifactAndName, callInfo)
	mock.lockGetByArtifactAndName.Unlock()
	return mock.GetByArtifactAndNameFunc(artifactUUID, name)
}

// GetByArtifactAndNameCalls gets all the calls that were made to GetByArtifactAndName.
// Check the length with:
//
//	len(mockedAPIKeyRepository.GetByArtifactAndNameCalls())
func (mock *APIKeyRepositoryMock) GetByArtifactAndNameCalls() []struct {
	ArtifactUUID string
	Name         string
} {
	var calls []struct {
		ArtifactUUID string
		Name         string
	}
	mock.lockGetByArtifactAndName.RLock()
	calls = mock.calls.GetByArtifactAndName
	mock.lockGetByArtifactAndName.RUnlock()
	return calls
}

// ListByApplicationUUID calls ListByApplicationUUIDFunc.
func (mock *APIKeyRepositoryMock) ListByApplicationUUID(applicationUUID string) ([]models.StoredAPIKey, error) {
	if mock.ListByApplicationUUIDFunc == nil {
		panic("APIKeyRepositoryMock.ListByApplicationUUIDFunc: method is nil but APIKeyRepository.ListByApplicationUUID was just called")
	}
	callInfo := struct {
		ApplicationUUID string
	}{
		ApplicationUUID: applicationUUID,
	}
	mock.lockListByApplicationUUID.Lock()
	mock.calls.ListByApplicationUUID = append(mock.calls.ListByApplicationUUID, callInfo)
	mock.lockListByApplicationUUID.Unlock()
	return mock.ListByApplicationUUIDFunc(applicationUUID)
}

// ListByApplicationUUIDCalls gets all the calls that were made to ListByApplicationUUID.
// Check the length with:
//
//	len(mockedAPIKeyRepository.ListByApplicationUUIDCalls())
func (mock *APIKeyRepositoryMock) ListByApplicationUUIDCalls() []struct {
	ApplicationUUID string
} {
	var calls []struct {
		ApplicationUUID string
	}
	mock.lockListByApplicationUUID.RLock()
	calls = mock.calls.ListByApplicationUUID
	mock.lockListByApplicationUUID.RUnlock()
	return calls
}

// ListByArtifact calls ListByArtifactFunc.
func (mock *APIKeyRepositoryMock) ListByArtifact(artifactUUID string) ([]models.StoredAPIKey, error) {
	if mock.ListByArtifactFunc == nil {
		panic("APIKeyRepositoryMock.ListByArtifactFunc: method is nil but APIKeyRepository.ListByArtifact was just called")
	}
	callInfo := struct {
		ArtifactUUID string
	}{
		ArtifactUUID: artifactUUID,
	}
	mock.lockListByArtifact.Lock()
	mock.calls.ListByArtifact = append(mock.calls.ListByArtifact, callInfo)
	mock.lockListByArtifact.Unlock()
	return mock.ListByArtifactFunc(artifactUUID)
}

// ListByArtifactCalls gets all the calls that were made to ListByArtifact.
// Check the length with:
//
//	len(mockedAPIKeyRepository.ListByArtifactCalls())
func (mock *APIKeyRepositoryMock) ListByArtifactCalls() []struct {
	ArtifactUUID string
} {
	var calls []struct {
		ArtifactUUID string
	}
	mock.lockListByArtifact.RLock()
	calls = mock.calls.ListByArtifact
	mock.lockListByArtifact.RUnlock()
	return calls
}

// ListByArtifactKind calls ListByArtifactKindFunc.
func (mock *APIKeyRepositoryMock) ListByArtifactKind(orgName string, kind string) ([]models.StoredAPIKey, error) {
	if mock.ListByArtifactKindFunc == nil {
		panic("APIKeyRepositoryMock.ListByArtifactKindFunc: method is nil but APIKeyRepository.ListByArtifactKind was just called")
	}
	callInfo := struct {
		OrgName string
		Kind    string
	}{
		OrgName: orgName,
		Kind:    kind,
	}
	mock.lockListByArtifactKind.Lock()
	mock.calls.ListByArtifactKind = append(mock.calls.ListByArtifactKind, callInfo)
	mock.lockListByArtifactKind.Unlock()
	return mock.ListByArtifactKindFunc(orgName, kind)
}

// ListByArtifactKindCalls gets all the calls that were made to ListByArtifactKind.
// Check the length with:
//
//	len(mockedAPIKeyRepository.ListByArtifactKindCalls())
func (mock *APIKeyRepositoryMock) ListByArtifactKindCalls() []struct {
	OrgName string
	Kind    string
} {
	var calls []struct {
		OrgName string
		Kind    string
	}
	mock.lockListByArtifactKind.RLock()
	calls = mock.calls.ListByArtifactKind
	mock.lockListByArtifactKind.RUnlock()
	return calls
}

// ListByArtifactKindAndEnvs calls ListByArtifactKindAndEnvsFunc.
func (mock *APIKeyRepositoryMock) ListByArtifactKindAndEnvs(orgName string, kind string, envUUIDs []string) ([]models.StoredAPIKey, error) {
	if mock.ListByArtifactKindAndEnvsFunc == nil {
		panic("APIKeyRepositoryMock.ListByArtifactKindAndEnvsFunc: method is nil but APIKeyRepository.ListByArtifactKindAndEnvs was just called")
	}
	callInfo := struct {
		OrgName  string
		Kind     string
		EnvUUIDs []string
	}{
		OrgName:  orgName,
		Kind:     kind,
		EnvUUIDs: envUUIDs,
	}
	mock.lockListByArtifactKindAndEnvs.Lock()
	mock.calls.ListByArtifactKindAndEnvs = append(mock.calls.ListByArtifactKindAndEnvs, callInfo)
	mock.lockListByArtifactKindAndEnvs.Unlock()
	return mock.ListByArtifactKindAndEnvsFunc(orgName, kind, envUUIDs)
}

// ListByArtifactKindAndEnvsCalls gets all the calls that were made to ListByArtifactKindAndEnvs.
// Check the length with:
//
//	len(mockedAPIKeyRepository.ListByArtifactKindAndEnvsCalls())
func (mock *APIKeyRepositoryMock) ListByArtifactKindAndEnvsCalls() []struct {
	OrgName  string
	Kind     string
	EnvUUIDs []string
} {
	var calls []struct {
		OrgName  string
		Kind     string
		EnvUUIDs []string
	}
	mock.lockListByArtifactKindAndEnvs.RLock()
	calls = mock.calls.ListByArtifactKindAndEnvs
	mock.lockListByArtifactKindAndEnvs.RUnlock()
	return calls
}

// ListPermanentByArtifactKind calls ListPermanentByArtifactKindFunc.
func (mock *APIKeyRepositoryMock) ListPermanentByArtifactKind(orgName string, kind string) ([]models.StoredAPIKey, error) {
	if mock.ListPermanentByArtifactKindFunc == nil {
		panic("APIKeyRepositoryMock.ListPermanentByArtifactKindFunc: method is nil but APIKeyRepository.ListPermanentByArtifactKind was just called")
	}
	callInfo := struct {
		OrgName string
		Kind    string
	}{
		OrgName: orgName,
		Kind:    kind,
	}
	mock.lockListPermanentByArtifactKind.Lock()
	mock.calls.ListPermanentByArtifactKind = append(mock.calls.ListPermanentByArtifactKind, callInfo)
	mock.lockListPermanentByArtifactKind.Unlock()
	return mock.ListPermanentByArtifactKindFunc(orgName, kind)
}

// ListPermanentByArtifactKindCalls gets all the calls that were made to ListPermanentByArtifactKind.
// Check the length with:
//
//	len(mockedAPIKeyRepository.ListPermanentByArtifactKindCalls())
func (mock *APIKeyRepositoryMock) ListPermanentByArtifactKindCalls() []struct {
	OrgName string
	Kind    string
} {
	var calls []struct {
		OrgName string
		Kind    string
	}
	mock.lockListPermanentByArtifactKind.RLock()
	calls = mock.calls.ListPermanentByArtifactKind
	mock.lockListPermanentByArtifactKind.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *APIKeyRepositoryMock) Upsert(key *models.StoredAPIKey) error {
	if mock.UpsertFunc == nil {
		panic("APIKeyRepositoryMock.UpsertFunc: method is nil but APIKeyRepository.Upsert was just called")
	}
	callInfo := struct {
		Key *models.StoredAPIKey
	}{
		Key: key,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(key)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedAPIKeyRepository.UpsertCalls())
func (mock *APIKeyRepositoryMock) UpsertCalls() []struct {
	Key *models.StoredAPIKey
} {
	var calls []struct {
		Key *models.StoredAPIKey
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
