// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// ArtifactRepositoryMock is a mock implementation of repositories.ArtifactRepository.
//
//	func TestSomethingThatUsesArtifactRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.ArtifactRepository
//		mockedArtifactRepository := &ArtifactRepositoryMock{
//			CountByKindAndOrgFunc: func(kind string, orgUUID string) (int, error) {
//				panic("mock out the CountByKindAndOrg method")
//			},
//			CreateFunc: func(tx *gorm.DB, artifact *models.Artifact) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(tx *gorm.DB, uuid string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(kind string, handle string, orgUUID string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetByHandleFunc: func(handle string, orgUUID string) (*models.Artifact, error) {
//				panic("mock out the GetByHandle method")
//			},
//			UpdateFunc: func(tx *gorm.DB, artifact *models.Artifact) error {
//				panic("mock out the Update method")
//			},
//			UpdateCatalogStatusFunc: func(tx *gorm.DB, uuid string, organizationUUID string, inCatalog bool) error {
//				panic("mock out the UpdateCatalogStatus method")
//			},
//		}
//
//		// use mockedArtifactRepository in code that requires repositories.ArtifactRepository
//		// and then make assertions.
//
//	}
type ArtifactRepositoryMock struct {
	// CountByKindAndOrgFunc mocks the CountByKindAndOrg method.
	CountByKindAndOrgFunc func(kind string, orgUUID string) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(tx *gorm.DB, artifact *models.Artifact) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(tx *gorm.DB, uuid string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(kind string, handle string, orgUUID string) (bool, error)

	// GetByHandleFunc mocks the GetByHandle method.
	GetByHandleFunc func(handle string, orgUUID string) (*models.Artifact, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(tx *gorm.DB, artifact *models.Artifact) error

	// UpdateCatalogStatusFunc mocks the UpdateCatalogStatus method.
	UpdateCatalogStatusFunc func(tx *gorm.DB, uuid string, organizationUUID string, inCatalog bool) error

	// calls tracks calls to the methods.
	calls struct {
		// CountByKindAndOrg holds details about calls to the CountByKindAndOrg method.
		CountByKindAndOrg []struct {
			// Kind is the kind argument value.
			Kind string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Artifact is the artifact argument value.
			Artifact *models.Artifact
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
			// UUID is the uuid argument value.
			UUID string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Kind is the kind argument value.
			Kind string
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByHandle holds details about calls to the GetByHandle method.
		GetByHandle []struct {
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Artifact is the artifact argument value.
			Artifact *models.Artifact
		}
		// UpdateCatalogStatus holds details about calls to the UpdateCatalogStatus method.
		UpdateCatalogStatus []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
			// UUID is the uuid argument value.
			UUID string
			// OrganizationUUID is the organizationUUID argument value.
			OrganizationUUID string
			// InCatalog is the inCatalog argument value.
			InCatalog bool
		}
	}
	lockCountByKindAndOrg   sync.RWMutex
	lockCreate              sync.RWMutex
	lockDelete              sync.RWMutex
	lockExists              sync.RWMutex
	lockGetByHandle         sync.RWMutex
	lockUpdate              sync.RWMutex
	lockUpdateCatalogStatus sync.RWMutex
}

// CountByKindAndOrg calls CountByKindAndOrgFunc.
func (mock *ArtifactRepositoryMock) CountByKindAndOrg(kind string, orgUUID string) (int, error) {
	if mock.CountByKindAndOrgFunc == nil {
		panic("ArtifactRepositoryMock.CountByKindAndOrgFunc: method is nil but ArtifactRepository.CountByKindAndOrg was just called")
	}
	callInfo := struct {
		Kind    string
		OrgUUID string
	}{
		Kind:    kind,
		OrgUUID: orgUUID,
	}
	mock.lockCountByKindAndOrg.Lock()
	mock.calls.CountByKindAndOrg = append(mock.calls.CountByKindAndOrg, callInfo)
	mock.lockCountByKindAndOrg.Unlock()
	return mock.CountByKindAndOrgFunc(kind, orgUUID)
}

// CountByKindAndOrgCalls gets all the calls that were made to CountByKindAndOrg.
// Check the length with:
//
//	len(mockedArtifactRepository.CountByKindAndOrgCalls())
func (mock *ArtifactRepositoryMock) CountByKindAndOrgCalls() []struct {
	Kind    string
	OrgUUID string
} {
	var calls []struct {
		Kind    string
		OrgUUID string
	}
	mock.lockCountByKindAndOrg.RLock()
	calls = mock.calls.CountByKindAndOrg
	mock.lockCountByKindAndOrg.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ArtifactRepositoryMock) Create(tx *gorm.DB, artifact *models.Artifact) error {
	if mock.CreateFunc == nil {
		panic("ArtifactRepositoryMock.CreateFunc: method is nil but ArtifactRepository.Create was just called")
	}
	callInfo := struct {
		Tx       *gorm.DB
		Artifact *models.Artifact
	}{
		Tx:       tx,
		Artifact: artifact,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(tx, artifact)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedArtifactRepository.CreateCalls())
func (mock *ArtifactRepositoryMock) CreateCalls() []struct {
	Tx       *gorm.DB
	Artifact *models.Artifact
} {
	var calls []struct {
		Tx       *gorm.DB
		Artifact *models.Artifact
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ArtifactRepositoryMock) Delete(tx *gorm.DB, uuid string) error {
	if mock.DeleteFunc == nil {
		panic("ArtifactRepositoryMock.DeleteFunc: method is nil but ArtifactRepository.Delete was just called")
	}
	callInfo := struct {
		Tx   *gorm.DB
		UUID string
	}{
		Tx:   tx,
		UUID: uuid,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(tx, uuid)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedArtifactRepository.DeleteCalls())
func (mock *ArtifactRepositoryMock) DeleteCalls() []struct {
	Tx   *gorm.DB
	UUID string
} {
	var calls []struct {
		Tx   *gorm.DB
		UUID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *ArtifactRepositoryMock) Exists(kind string, handle string, orgUUID string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("ArtifactRepositoryMock.ExistsFunc: method is nil but ArtifactRepository.Exists was just called")
	}
	callInfo := struct {
		Kind    string
		Handle  string
		OrgUUID string
	}{
		Kind:    kind,
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(kind, handle, orgUUID)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedArtifactRepository.ExistsCalls())
func (mock *ArtifactRepositoryMock) ExistsCalls() []struct {
	Kind    string
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Kind    string
		Handle  string
		OrgUUID string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetByHandle calls GetByHandleFunc.
func (mock *ArtifactRepositoryMock) GetByHandle(handle string, orgUUID string) (*models.Artifact, error) {
	if mock.GetByHandleFunc == nil {
		panic("ArtifactRepositoryMock.GetByHandleFunc: method is nil but ArtifactRepository.GetByHandle was just called")
	}
	callInfo := struct {
		Handle  string
		OrgUUID string
	}{
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockGetByHandle.Lock()
	mock.calls.GetByHandle = append(mock.calls.GetByHandle, callInfo)
	mock.lockGetByHandle.Unlock()
	return mock.GetByHandleFunc(handle, orgUUID)
}

// GetByHandleCalls gets all the calls that were made to GetByHandle.
// Check the length with:
//
//	len(mockedArtifactRepository.GetByHandleCalls())
func (mock *ArtifactRepositoryMock) GetByHandleCalls() []struct {
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Handle  string
		OrgUUID string
	}
	mock.lockGetByHandle.RLock()
	calls = mock.calls.GetByHandle
	mock.lockGetByHandle.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ArtifactRepositoryMock) Update(tx *gorm.DB, artifact *models.Artifact) error {
	if mock.UpdateFunc == nil {
		panic("ArtifactRepositoryMock.UpdateFunc: method is nil but ArtifactRepository.Update was just called")
	}
	callInfo := struct {
		Tx       *gorm.DB
		Artifact *models.Artifact
	}{
		Tx:       tx,
		Artifact: artifact,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(tx, artifact)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedArtifactRepository.UpdateCalls())
func (mock *ArtifactRepositoryMock) UpdateCalls() []struct {
	Tx       *gorm.DB
	Artifact *models.Artifact
} {
	var calls []struct {
		Tx       *gorm.DB
		Artifact *models.Artifact
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateCatalogStatus calls UpdateCatalogStatusFunc.
func (mock *ArtifactRepositoryMock) UpdateCatalogStatus(tx *gorm.DB, uuid string, organizationUUID string, inCatalog bool) error {
	if mock.UpdateCatalogStatusFunc == nil {
		panic("ArtifactRepositoryMock.UpdateCatalogStatusFunc: method is nil but ArtifactRepository.UpdateCatalogStatus was just called")
	}
	callInfo := struct {
		Tx               *gorm.DB
		UUID             string
		OrganizationUUID string
		InCatalog        bool
	}{
		Tx:               tx,
		UUID:             uuid,
		OrganizationUUID: organizationUUID,
		InCatalog:        inCatalog,
	}
	mock.lockUpdateCatalogStatus.Lock()
	mock.calls.UpdateCatalogStatus = append(mock.calls.UpdateCatalogStatus, callInfo)
	mock.lockUpdateCatalogStatus.Unlock()
	return mock.UpdateCatalogStatusFunc(tx, uuid, organizationUUID, inCatalog)
}

// UpdateCatalogStatusCalls gets all the calls that were made to UpdateCatalogStatus.
// Check the length with:
//
//	len(mockedArtifactRepository.UpdateCatalogStatusCalls())
func (mock *ArtifactRepositoryMock) UpdateCatalogStatusCalls() []struct {
	Tx               *gorm.DB
	UUID             string
	OrganizationUUID string
	InCatalog        bool
} {
	var calls []struct {
		Tx               *gorm.DB
		UUID             string
		OrganizationUUID string
		InCatalog        bool
	}
	mock.lockUpdateCatalogStatus.RLock()
	calls = mock.calls.UpdateCatalogStatus
	mock.lockUpdateCatalogStatus.RUnlock()
	return calls
}
