// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// CatalogRepositoryMock is a mock implementation of repositories.CatalogRepository.
//
//	func TestSomethingThatUsesCatalogRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.CatalogRepository
//		mockedCatalogRepository := &CatalogRepositoryMock{
//			ListAllFunc: func(orgUUID string, limit int, offset int) ([]models.CatalogEntry, int64, error) {
//				panic("mock out the ListAll method")
//			},
//			ListByKindFunc: func(orgUUID string, kind string, limit int, offset int) ([]models.CatalogEntry, int64, error) {
//				panic("mock out the ListByKind method")
//			},
//			ListLLMProvidersFunc: func(filters *models.CatalogListFilters) ([]models.CatalogLLMProviderEntry, int64, error) {
//				panic("mock out the ListLLMProviders method")
//			},
//		}
//
//		// use mockedCatalogRepository in code that requires repositories.CatalogRepository
//		// and then make assertions.
//
//	}
type CatalogRepositoryMock struct {
	// ListAllFunc mocks the ListAll method.
	ListAllFunc func(orgUUID string, limit int, offset int) ([]models.CatalogEntry, int64, error)

	// ListByKindFunc mocks the ListByKind method.
	ListByKindFunc func(orgUUID string, kind string, limit int, offset int) ([]models.CatalogEntry, int64, error)

	// ListLLMProvidersFunc mocks the ListLLMProviders method.
	ListLLMProvidersFunc func(filters *models.CatalogListFilters) ([]models.CatalogLLMProviderEntry, int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListAll holds details about calls to the ListAll method.
		ListAll []struct {
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByKind holds details about calls to the ListByKind method.
		ListByKind []struct {
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// Kind is the kind argument value.
			Kind string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListLLMProviders holds details about calls to the ListLLMProviders method.
		ListLLMProviders []struct {
			// Filters is the filters argument value.
			Filters *models.CatalogListFilters
		}
	}
	lockListAll          sync.RWMutex
	lockListByKind       sync.RWMutex
	lockListLLMProviders sync.RWMutex
}

// ListAll calls ListAllFunc.
func (mock *CatalogRepositoryMock) ListAll(orgUUID string, limit int, offset int) ([]models.CatalogEntry, int64, error) {
	if mock.ListAllFunc == nil {
		panic("CatalogRepositoryMock.ListAllFunc: method is nil but CatalogRepository.ListAll was just called")
	}
	callInfo := struct {
		OrgUUID string
		Limit   int
		Offset  int
	}{
		OrgUUID: orgUUID,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockListAll.Lock()
	mock.calls.ListAll = append(mock.calls.ListAll, callInfo)
	mock.lockListAll.Unlock()
	return mock.ListAllFunc(orgUUID, limit, offset)
}

// ListAllCalls gets all the calls that were made to ListAll.
// Check the length with:
//
//	len(mockedCatalogRepository.ListAllCalls())
func (mock *CatalogRepositoryMock) ListAllCalls() []struct {
	OrgUUID string
	Limit   int
	Offset  int
} {
	var calls []struct {
		OrgUUID string
		Limit   int
		Offset  int
	}
	mock.lockListAll.RLock()
	calls = mock.calls.ListAll
	mock.lockListAll.RUnlock()
	return calls
}

// ListByKind calls ListByKindFunc.
func (mock *CatalogRepositoryMock) ListByKind(orgUUID string, kind string, limit int, offset int) ([]models.CatalogEntry, int64, error) {
	if mock.ListByKindFunc == nil {
		panic("CatalogRepositoryMock.ListByKindFunc: method is nil but CatalogRepository.ListByKind was just called")
	}
	callInfo := struct {
		OrgUUID string
		Kind    string
		Limit   int
		Offset  int
	}{
		OrgUUID: orgUUID,
		Kind:    kind,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockListByKind.Lock()
	mock.calls.ListByKind = append(mock.calls.ListByKind, callInfo)
	mock.lockListByKind.Unlock()
	return mock.ListByKindFunc(orgUUID, kind, limit, offset)
}

// ListByKindCalls gets all the calls that were made to ListByKind.
// Check the length with:
//
//	len(mockedCatalogRepository.ListByKindCalls())
func (mock *CatalogRepositoryMock) ListByKindCalls() []struct {
	OrgUUID string
	Kind    string
	Limit   int
	Offset  int
} {
	var calls []struct {
		OrgUUID string
		Kind    string
		Limit   int
		Offset  int
	}
	mock.lockListByKind.RLock()
	calls = mock.calls.ListByKind
	mock.lockListByKind.RUnlock()
	return calls
}

// ListLLMProviders calls ListLLMProvidersFunc.
func (mock *CatalogRepositoryMock) ListLLMProviders(filters *models.CatalogListFilters) ([]models.CatalogLLMProviderEntry, int64, error) {
	if mock.ListLLMProvidersFunc == nil {
		panic("CatalogRepositoryMock.ListLLMProvidersFunc: method is nil but CatalogRepository.ListLLMProviders was just called")
	}
	callInfo := struct {
		Filters *models.CatalogListFilters
	}{
		Filters: filters,
	}
	mock.lockListLLMProviders.Lock()
	mock.calls.ListLLMProviders = append(mock.calls.ListLLMProviders, callInfo)
	mock.lockListLLMProviders.Unlock()
	return mock.ListLLMProvidersFunc(filters)
}

// ListLLMProvidersCalls gets all the calls that were made to ListLLMProviders.
// Check the length with:
//
//	len(mockedCatalogRepository.ListLLMProvidersCalls())
func (mock *CatalogRepositoryMock) ListLLMProvidersCalls() []struct {
	Filters *models.CatalogListFilters
} {
	var calls []struct {
		Filters *models.CatalogListFilters
	}
	mock.lockListLLMProviders.RLock()
	calls = mock.calls.ListLLMProviders
	mock.lockListLLMProviders.RUnlock()
	return calls
}
