// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"github.com/wso2/agent-manager/agent-manager-service/repositories"
	"gorm.io/gorm"
)

// CustomEvaluatorRepositoryMock is a mock implementation of repositories.CustomEvaluatorRepository.
//
//	func TestSomethingThatUsesCustomEvaluatorRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.CustomEvaluatorRepository
//		mockedCustomEvaluatorRepository := &CustomEvaluatorRepositoryMock{
//			CreateFunc: func(evaluator *models.CustomEvaluator) error {
//				panic("mock out the Create method")
//			},
//			GetByIdentifierFunc: func(orgName string, identifier string) (*models.CustomEvaluator, error) {
//				panic("mock out the GetByIdentifier method")
//			},
//			GetByIdentifiersFunc: func(orgName string, identifiers []string) ([]models.CustomEvaluator, error) {
//				panic("mock out the GetByIdentifiers method")
//			},
//			ListFunc: func(orgName string, filters repositories.CustomEvaluatorFilters) ([]models.CustomEvaluator, int64, error) {
//				panic("mock out the List method")
//			},
//			RunInTransactionFunc: func(fn func(txRepo repositories.CustomEvaluatorRepository) error) error {
//				panic("mock out the RunInTransaction method")
//			},
//			SoftDeleteFunc: func(evaluator *models.CustomEvaluator) error {
//				panic("mock out the SoftDelete method")
//			},
//			UpdateFunc: func(evaluator *models.CustomEvaluator) error {
//				panic("mock out the Update method")
//			},
//			WithTxFunc: func(tx *gorm.DB) repositories.CustomEvaluatorRepository {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedCustomEvaluatorRepository in code that requires repositories.CustomEvaluatorRepository
//		// and then make assertions.
//
//	}
type CustomEvaluatorRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(evaluator *models.CustomEvaluator) error

	// GetByIdentifierFunc mocks the GetByIdentifier method.
	GetByIdentifierFunc func(orgName string, identifier string) (*models.CustomEvaluator, error)

	// GetByIdentifiersFunc mocks the GetByIdentifiers method.
	GetByIdentifiersFunc func(orgName string, identifiers []string) ([]models.CustomEvaluator, error)

	// ListFunc mocks the List method.
	ListFunc func(orgName string, filters repositories.CustomEvaluatorFilters) ([]models.CustomEvaluator, int64, error)

	// RunInTransactionFunc mocks the RunInTransaction method.
	RunInTransactionFunc func(fn func(txRepo repositories.CustomEvaluatorRepository) error) error

	// SoftDeleteFunc mocks the SoftDelete method.
	SoftDeleteFunc func(evaluator *models.CustomEvaluator) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(evaluator *models.CustomEvaluator) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(tx *gorm.DB) repositories.CustomEvaluatorRepository

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Evaluator is the evaluator argument value.
			Evaluator *models.CustomEvaluator
		}
		// GetByIdentifier holds details about calls to the GetByIdentifier method.
		GetByIdentifier []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Identifier is the identifier argument value.
			Identifier string
		}
		// GetByIdentifiers holds details about calls to the GetByIdentifiers method.
		GetByIdentifiers []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Identifiers is the identifiers argument value.
			Identifiers []string
		}
		// List holds details about calls to the List method.
		List []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Filters is the filters argument value.
			Filters repositories.CustomEvaluatorFilters
		}
		// RunInTransaction holds details about calls to the RunInTransaction method.
		RunInTransaction []struct {
			// Fn is the fn argument value.
			Fn func(txRepo repositories.CustomEvaluatorRepository) error
		}
		// SoftDelete holds details about calls to the SoftDelete method.
		SoftDelete []struct {
			// Evaluator is the evaluator argument value.
			Evaluator *models.CustomEvaluator
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Evaluator is the evaluator argument value.
			Evaluator *models.CustomEvaluator
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
		}
	}
	lockCreate           sync.RWMutex
	lockGetByIdentifier  sync.RWMutex
	lockGetByIdentifiers sync.RWMutex
	lockList             sync.RWMutex
	lockRunInTransaction sync.RWMutex
	lockSoftDelete       sync.RWMutex
	lockUpdate           sync.RWMutex
	lockWithTx           sync.RWMutex
}

// Create calls CreateFunc.
func (mock *CustomEvaluatorRepositoryMock) Create(evaluator *models.CustomEvaluator) error {
	if mock.CreateFunc == nil {
		panic("CustomEvaluatorRepositoryMock.CreateFunc: method is nil but CustomEvaluatorRepository.Create was just called")
	}
	callInfo := struct {
		Evaluator *models.CustomEvaluator
	}{
		Evaluator: evaluator,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(evaluator)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.CreateCalls())
func (mock *CustomEvaluatorRepositoryMock) CreateCalls() []struct {
	Evaluator *models.CustomEvaluator
} {
	var calls []struct {
		Evaluator *models.CustomEvaluator
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByIdentifier calls GetByIdentifierFunc.
func (mock *CustomEvaluatorRepositoryMock) GetByIdentifier(orgName string, identifier string) (*models.CustomEvaluator, error) {
	if mock.GetByIdentifierFunc == nil {
		panic("CustomEvaluatorRepositoryMock.GetByIdentifierFunc: method is nil but CustomEvaluatorRepository.GetByIdentifier was just called")
	}
	callInfo := struct {
		OrgName    string
		Identifier string
	}{
		OrgName:    orgName,
		Identifier: identifier,
	}
	mock.lockGetByIdentifier.Lock()
	mock.calls.GetByIdentifier = append(mock.calls.GetByIdentifier, callInfo)
	mock.lockGetByIdentifier.Unlock()
	return mock.GetByIdentifierFunc(orgName, identifier)
}

// GetByIdentifierCalls gets all the calls that were made to GetByIdentifier.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.GetByIdentifierCalls())
func (mock *CustomEvaluatorRepositoryMock) GetByIdentifierCalls() []struct {
	OrgName    string
	Identifier string
} {
	var calls []struct {
		OrgName    string
		Identifier string
	}
	mock.lockGetByIdentifier.RLock()
	calls = mock.calls.GetByIdentifier
	mock.lockGetByIdentifier.RUnlock()
	return calls
}

// GetByIdentifiers calls GetByIdentifiersFunc.
func (mock *CustomEvaluatorRepositoryMock) GetByIdentifiers(orgName string, identifiers []string) ([]models.CustomEvaluator, error) {
	if mock.GetByIdentifiersFunc == nil {
		panic("CustomEvaluatorRepositoryMock.GetByIdentifiersFunc: method is nil but CustomEvaluatorRepository.GetByIdentifiers was just called")
	}
	callInfo := struct {
		OrgName     string
		Identifiers []string
	}{
		OrgName:     orgName,
		Identifiers: identifiers,
	}
	mock.lockGetByIdentifiers.Lock()
	mock.calls.GetByIdentifiers = append(mock.calls.GetByIdentifiers, callInfo)
	mock.lockGetByIdentifiers.Unlock()
	return mock.GetByIdentifiersFunc(orgName, identifiers)
}

// GetByIdentifiersCalls gets all the calls that were made to GetByIdentifiers.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.GetByIdentifiersCalls())
func (mock *CustomEvaluatorRepositoryMock) GetByIdentifiersCalls() []struct {
	OrgName     string
	Identifiers []string
} {
	var calls []struct {
		OrgName     string
		Identifiers []string
	}
	mock.lockGetByIdentifiers.RLock()
	calls = mock.calls.GetByIdentifiers
	mock.lockGetByIdentifiers.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *CustomEvaluatorRepositoryMock) List(orgName string, filters repositories.CustomEvaluatorFilters) ([]models.CustomEvaluator, int64, error) {
	if mock.ListFunc == nil {
		panic("CustomEvaluatorRepositoryMock.ListFunc: method is nil but CustomEvaluatorRepository.List was just called")
	}
	callInfo := struct {
		OrgName string
		Filters repositories.CustomEvaluatorFilters
	}{
		OrgName: orgName,
		Filters: filters,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(orgName, filters)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.ListCalls())
func (mock *CustomEvaluatorRepositoryMock) ListCalls() []struct {
	OrgName string
	Filters repositories.CustomEvaluatorFilters
} {
	var calls []struct {
		OrgName string
		Filters repositories.CustomEvaluatorFilters
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// RunInTransaction calls RunInTransactionFunc.
func (mock *CustomEvaluatorRepositoryMock) RunInTransaction(fn func(txRepo repositories.CustomEvaluatorRepository) error) error {
	if mock.RunInTransactionFunc == nil {
		panic("CustomEvaluatorRepositoryMock.RunInTransactionFunc: method is nil but CustomEvaluatorRepository.RunInTransaction was just called")
	}
	callInfo := struct {
		Fn func(txRepo repositories.CustomEvaluatorRepository) error
	}{
		Fn: fn,
	}
	mock.lockRunInTransaction.Lock()
	mock.calls.RunInTransaction = append(mock.calls.RunInTransaction, callInfo)
	mock.lockRunInTransaction.Unlock()
	return mock.RunInTransactionFunc(fn)
}

// RunInTransactionCalls gets all the calls that were made to RunInTransaction.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.RunInTransactionCalls())
func (mock *CustomEvaluatorRepositoryMock) RunInTransactionCalls() []struct {
	Fn func(txRepo repositories.CustomEvaluatorRepository) error
} {
	var calls []struct {
		Fn func(txRepo repositories.CustomEvaluatorRepository) error
	}
	mock.lockRunInTransaction.RLock()
	calls = mock.calls.RunInTransaction
	mock.lockRunInTransaction.RUnlock()
	return calls
}

// SoftDelete calls SoftDeleteFunc.
func (mock *CustomEvaluatorRepositoryMock) SoftDelete(evaluator *models.CustomEvaluator) error {
	if mock.SoftDeleteFunc == nil {
		panic("CustomEvaluatorRepositoryMock.SoftDeleteFunc: method is nil but CustomEvaluatorRepository.SoftDelete was just called")
	}
	callInfo := struct {
		Evaluator *models.CustomEvaluator
	}{
		Evaluator: evaluator,
	}
	mock.lockSoftDelete.Lock()
	mock.calls.SoftDelete = append(mock.calls.SoftDelete, callInfo)
	mock.lockSoftDelete.Unlock()
	return mock.SoftDeleteFunc(evaluator)
}

// SoftDeleteCalls gets all the calls that were made to SoftDelete.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.SoftDeleteCalls())
func (mock *CustomEvaluatorRepositoryMock) SoftDeleteCalls() []struct {
	Evaluator *models.CustomEvaluator
} {
	var calls []struct {
		Evaluator *models.CustomEvaluator
	}
	mock.lockSoftDelete.RLock()
	calls = mock.calls.SoftDelete
	mock.lockSoftDelete.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *CustomEvaluatorRepositoryMock) Update(evaluator *models.CustomEvaluator) error {
	if mock.UpdateFunc == nil {
		panic("CustomEvaluatorRepositoryMock.UpdateFunc: method is nil but CustomEvaluatorRepository.Update was just called")
	}
	callInfo := struct {
		Evaluator *models.CustomEvaluator
	}{
		Evaluator: evaluator,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(evaluator)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.UpdateCalls())
func (mock *CustomEvaluatorRepositoryMock) UpdateCalls() []struct {
	Evaluator *models.CustomEvaluator
} {
	var calls []struct {
		Evaluator *models.CustomEvaluator
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *CustomEvaluatorRepositoryMock) WithTx(tx *gorm.DB) repositories.CustomEvaluatorRepository {
	if mock.WithTxFunc == nil {
		panic("CustomEvaluatorRepositoryMock.WithTxFunc: method is nil but CustomEvaluatorRepository.WithTx was just called")
	}
	callInfo := struct {
		Tx *gorm.DB
	}{
		Tx: tx,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(tx)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedCustomEvaluatorRepository.WithTxCalls())
func (mock *CustomEvaluatorRepositoryMock) WithTxCalls() []struct {
	Tx *gorm.DB
} {
	var calls []struct {
		Tx *gorm.DB
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
