// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// DeploymentRepositoryMock is a mock implementation of repositories.DeploymentRepository.
//
//	func TestSomethingThatUsesDeploymentRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.DeploymentRepository
//		mockedDeploymentRepository := &DeploymentRepositoryMock{
//			CreateWithLimitEnforcementFunc: func(deployment *models.Deployment, hardLimit int) error {
//				panic("mock out the CreateWithLimitEnforcement method")
//			},
//			DeleteFunc: func(deploymentID string, artifactUUID string, orgUUID string) error {
//				panic("mock out the Delete method")
//			},
//			DeleteStatusFunc: func(artifactUUID string, orgUUID string, gatewayID string) error {
//				panic("mock out the DeleteStatus method")
//			},
//			GetByArtifactAndGatewayFunc: func(artifactUUID string, gatewayUUID string, orgUUID string) (*models.Deployment, error) {
//				panic("mock out the GetByArtifactAndGateway method")
//			},
//			GetCurrentByGatewayFunc: func(artifactUUID string, gatewayID string, orgUUID string) (*models.Deployment, error) {
//				panic("mock out the GetCurrentByGateway method")
//			},
//			GetDeployedGatewaysByProviderFunc: func(artifactUUID uuid.UUID, orgUUID string) ([]string, error) {
//				panic("mock out the GetDeployedGatewaysByProvider method")
//			},
//			GetDeployedProvidersByGatewayFunc: func(gatewayUUID uuid.UUID, orgUUID string) ([]string, error) {
//				panic("mock out the GetDeployedProvidersByGateway method")
//			},
//			GetDeploymentsWithStateFunc: func(artifactUUID string, orgUUID string, gatewayID *string, status *string, maxPerAPIGW int) ([]*models.Deployment, error) {
//				panic("mock out the GetDeploymentsWithState method")
//			},
//			GetStatusFunc: func(artifactUUID string, orgUUID string, gatewayID string) (string, models.DeploymentStatus, *time.Time, error) {
//				panic("mock out the GetStatus method")
//			},
//			GetTrackedGatewaysByProviderFunc: func(artifactUUID uuid.UUID, orgUUID string) ([]string, error) {
//				panic("mock out the GetTrackedGatewaysByProvider method")
//			},
//			GetWithContentFunc: func(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error) {
//				panic("mock out the GetWithContent method")
//			},
//			GetWithStateFunc: func(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error) {
//				panic("mock out the GetWithState method")
//			},
//			IsProviderDeployedToGatewayFunc: func(artifactUUID uuid.UUID, gatewayUUID uuid.UUID, orgUUID string) (bool, error) {
//				panic("mock out the IsProviderDeployedToGateway method")
//			},
//			SetCurrentFunc: func(artifactUUID string, orgUUID string, gatewayID string, deploymentID string, status models.DeploymentStatus) (time.Time, error) {
//				panic("mock out the SetCurrent method")
//			},
//			UpdateStatusByDeploymentIDFunc: func(deploymentID string, gatewayUUID string, status models.DeploymentStatus) (time.Time, error) {
//				panic("mock out the UpdateStatusByDeploymentID method")
//			},
//		}
//
//		// use mockedDeploymentRepository in code that requires repositories.DeploymentRepository
//		// and then make assertions.
//
//	}
type DeploymentRepositoryMock struct {
	// CreateWithLimitEnforcementFunc mocks the CreateWithLimitEnforcement method.
	CreateWithLimitEnforcementFunc func(deployment *models.Deployment, hardLimit int) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(deploymentID string, artifactUUID string, orgUUID string) error

	// DeleteStatusFunc mocks the DeleteStatus method.
	DeleteStatusFunc func(artifactUUID string, orgUUID string, gatewayID string) error

	// GetByArtifactAndGatewayFunc mocks the GetByArtifactAndGateway method.
	GetByArtifactAndGatewayFunc func(artifactUUID string, gatewayUUID string, orgUUID string) (*models.Deployment, error)

	// GetCurrentByGatewayFunc mocks the GetCurrentByGateway method.
	GetCurrentByGatewayFunc func(artifactUUID string, gatewayID string, orgUUID string) (*models.Deployment, error)

	// GetDeployedGatewaysByProviderFunc mocks the GetDeployedGatewaysByProvider method.
	GetDeployedGatewaysByProviderFunc func(artifactUUID uuid.UUID, orgUUID string) ([]string, error)

	// GetDeployedProvidersByGatewayFunc mocks the GetDeployedProvidersByGateway method.
	GetDeployedProvidersByGatewayFunc func(gatewayUUID uuid.UUID, orgUUID string) ([]string, error)

	// GetDeploymentsWithStateFunc mocks the GetDeploymentsWithState method.
	GetDeploymentsWithStateFunc func(artifactUUID string, orgUUID string, gatewayID *string, status *string, maxPerAPIGW int) ([]*models.Deployment, error)

	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func(artifactUUID string, orgUUID string, gatewayID string) (string, models.DeploymentStatus, *time.Time, error)

	// GetTrackedGatewaysByProviderFunc mocks the GetTrackedGatewaysByProvider method.
	GetTrackedGatewaysByProviderFunc func(artifactUUID uuid.UUID, orgUUID string) ([]string, error)

	// GetWithContentFunc mocks the GetWithContent method.
	GetWithContentFunc func(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error)

	// GetWithStateFunc mocks the GetWithState method.
	GetWithStateFunc func(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error)

	// IsProviderDeployedToGatewayFunc mocks the IsProviderDeployedToGateway method.
	IsProviderDeployedToGatewayFunc func(artifactUUID uuid.UUID, gatewayUUID uuid.UUID, orgUUID string) (bool, error)

	// SetCurrentFunc mocks the SetCurrent method.
	SetCurrentFunc func(artifactUUID string, orgUUID string, gatewayID string, deploymentID string, status models.DeploymentStatus) (time.Time, error)

	// UpdateStatusByDeploymentIDFunc mocks the UpdateStatusByDeploymentID method.
	UpdateStatusByDeploymentIDFunc func(deploymentID string, gatewayUUID string, status models.DeploymentStatus) (time.Time, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateWithLimitEnforcement holds details about calls to the CreateWithLimitEnforcement method.
		CreateWithLimitEnforcement []struct {
			// Deployment is the deployment argument value.
			Deployment *models.Deployment
			// HardLimit is the hardLimit argument value.
			HardLimit int
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// DeleteStatus holds details about calls to the DeleteStatus method.
		DeleteStatus []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetByArtifactAndGateway holds details about calls to the GetByArtifactAndGateway method.
		GetByArtifactAndGateway []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// GatewayUUID is the gatewayUUID argument value.
			GatewayUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetCurrentByGateway holds details about calls to the GetCurrentByGateway method.
		GetCurrentByGateway []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetDeployedGatewaysByProvider holds details about calls to the GetDeployedGatewaysByProvider method.
		GetDeployedGatewaysByProvider []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID uuid.UUID
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetDeployedProvidersByGateway holds details about calls to the GetDeployedProvidersByGateway method.
		GetDeployedProvidersByGateway []struct {
			// GatewayUUID is the gatewayUUID argument value.
			GatewayUUID uuid.UUID
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetDeploymentsWithState holds details about calls to the GetDeploymentsWithState method.
		GetDeploymentsWithState []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// GatewayID is the gatewayID argument value.
			GatewayID *string
			// Status is the status argument value.
			Status *string
			// MaxPerAPIGW is the maxPerAPIGW argument value.
			MaxPerAPIGW int
		}
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetTrackedGatewaysByProvider holds details about calls to the GetTrackedGatewaysByProvider method.
		GetTrackedGatewaysByProvider []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID uuid.UUID
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetWithContent holds details about calls to the GetWithContent method.
		GetWithContent []struct {
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetWithState holds details about calls to the GetWithState method.
		GetWithState []struct {
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// IsProviderDeployedToGateway holds details about calls to the IsProviderDeployedToGateway method.
		IsProviderDeployedToGateway []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID uuid.UUID
			// GatewayUUID is the gatewayUUID argument value.
			GatewayUUID uuid.UUID
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// SetCurrent holds details about calls to the SetCurrent method.
		SetCurrent []struct {
			// ArtifactUUID is the artifactUUID argument value.
			ArtifactUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// Status is the status argument value.
			Status models.DeploymentStatus
		}
		// UpdateStatusByDeploymentID holds details about calls to the UpdateStatusByDeploymentID method.
		UpdateStatusByDeploymentID []struct {
			// DeploymentID is the deploymentID argument value.
			DeploymentID string
			// GatewayUUID is the gatewayUUID argument value.
			GatewayUUID string
			// Status is the status argument value.
			Status models.DeploymentStatus
		}
	}
	lockCreateWithLimitEnforcement    sync.RWMutex
	lockDelete                        sync.RWMutex
	lockDeleteStatus                  sync.RWMutex
	lockGetByArtifactAndGateway       sync.RWMutex
	lockGetCurrentByGateway           sync.RWMutex
	lockGetDeployedGatewaysByProvider sync.RWMutex
	lockGetDeployedProvidersByGateway sync.RWMutex
	lockGetDeploymentsWithState       sync.RWMutex
	lockGetStatus                     sync.RWMutex
	lockGetTrackedGatewaysByProvider  sync.RWMutex
	lockGetWithContent                sync.RWMutex
	lockGetWithState                  sync.RWMutex
	lockIsProviderDeployedToGateway   sync.RWMutex
	lockSetCurrent                    sync.RWMutex
	lockUpdateStatusByDeploymentID    sync.RWMutex
}

// CreateWithLimitEnforcement calls CreateWithLimitEnforcementFunc.
func (mock *DeploymentRepositoryMock) CreateWithLimitEnforcement(deployment *models.Deployment, hardLimit int) error {
	if mock.CreateWithLimitEnforcementFunc == nil {
		panic("DeploymentRepositoryMock.CreateWithLimitEnforcementFunc: method is nil but DeploymentRepository.CreateWithLimitEnforcement was just called")
	}
	callInfo := struct {
		Deployment *models.Deployment
		HardLimit  int
	}{
		Deployment: deployment,
		HardLimit:  hardLimit,
	}
	mock.lockCreateWithLimitEnforcement.Lock()
	mock.calls.CreateWithLimitEnforcement = append(mock.calls.CreateWithLimitEnforcement, callInfo)
	mock.lockCreateWithLimitEnforcement.Unlock()
	return mock.CreateWithLimitEnforcementFunc(deployment, hardLimit)
}

// CreateWithLimitEnforcementCalls gets all the calls that were made to CreateWithLimitEnforcement.
// Check the length with:
//
//	len(mockedDeploymentRepository.CreateWithLimitEnforcementCalls())
func (mock *DeploymentRepositoryMock) CreateWithLimitEnforcementCalls() []struct {
	Deployment *models.Deployment
	HardLimit  int
} {
	var calls []struct {
		Deployment *models.Deployment
		HardLimit  int
	}
	mock.lockCreateWithLimitEnforcement.RLock()
	calls = mock.calls.CreateWithLimitEnforcement
	mock.lockCreateWithLimitEnforcement.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *DeploymentRepositoryMock) Delete(deploymentID string, artifactUUID string, orgUUID string) error {
	if mock.DeleteFunc == nil {
		panic("DeploymentRepositoryMock.DeleteFunc: method is nil but DeploymentRepository.Delete was just called")
	}
	callInfo := struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}{
		DeploymentID: deploymentID,
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(deploymentID, artifactUUID, orgUUID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedDeploymentRepository.DeleteCalls())
func (mock *DeploymentRepositoryMock) DeleteCalls() []struct {
	DeploymentID string
	ArtifactUUID string
	OrgUUID      string
} {
	var calls []struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteStatus calls DeleteStatusFunc.
func (mock *DeploymentRepositoryMock) DeleteStatus(artifactUUID string, orgUUID string, gatewayID string) error {
	if mock.DeleteStatusFunc == nil {
		panic("DeploymentRepositoryMock.DeleteStatusFunc: method is nil but DeploymentRepository.DeleteStatus was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
		GatewayID:    gatewayID,
	}
	mock.lockDeleteStatus.Lock()
	mock.calls.DeleteStatus = append(mock.calls.DeleteStatus, callInfo)
	mock.lockDeleteStatus.Unlock()
	return mock.DeleteStatusFunc(artifactUUID, orgUUID, gatewayID)
}

// DeleteStatusCalls gets all the calls that were made to DeleteStatus.
// Check the length with:
//
//	len(mockedDeploymentRepository.DeleteStatusCalls())
func (mock *DeploymentRepositoryMock) DeleteStatusCalls() []struct {
	ArtifactUUID string
	OrgUUID      string
	GatewayID    string
} {
	var calls []struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
	}
	mock.lockDeleteStatus.RLock()
	calls = mock.calls.DeleteStatus
	mock.lockDeleteStatus.RUnlock()
	return calls
}

// GetByArtifactAndGateway calls GetByArtifactAndGatewayFunc.
func (mock *DeploymentRepositoryMock) GetByArtifactAndGateway(artifactUUID string, gatewayUUID string, orgUUID string) (*models.Deployment, error) {
	if mock.GetByArtifactAndGatewayFunc == nil {
		panic("DeploymentRepositoryMock.GetByArtifactAndGatewayFunc: method is nil but DeploymentRepository.GetByArtifactAndGateway was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		GatewayUUID  string
		OrgUUID      string
	}{
		ArtifactUUID: artifactUUID,
		GatewayUUID:  gatewayUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetByArtifactAndGateway.Lock()
	mock.calls.GetByArtifactAndGateway = append(mock.calls.GetByArtifactAndGateway, callInfo)
	mock.lockGetByArtifactAndGateway.Unlock()
	return mock.GetByArtifactAndGatewayFunc(artifactUUID, gatewayUUID, orgUUID)
}

// GetByArtifactAndGatewayCalls gets all the calls that were made to GetByArtifactAndGateway.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetByArtifactAndGatewayCalls())
func (mock *DeploymentRepositoryMock) GetByArtifactAndGatewayCalls() []struct {
	ArtifactUUID string
	GatewayUUID  string
	OrgUUID      string
} {
	var calls []struct {
		ArtifactUUID string
		GatewayUUID  string
		OrgUUID      string
	}
	mock.lockGetByArtifactAndGateway.RLock()
	calls = mock.calls.GetByArtifactAndGateway
	mock.lockGetByArtifactAndGateway.RUnlock()
	return calls
}

// GetCurrentByGateway calls GetCurrentByGatewayFunc.
func (mock *DeploymentRepositoryMock) GetCurrentByGateway(artifactUUID string, gatewayID string, orgUUID string) (*models.Deployment, error) {
	if mock.GetCurrentByGatewayFunc == nil {
		panic("DeploymentRepositoryMock.GetCurrentByGatewayFunc: method is nil but DeploymentRepository.GetCurrentByGateway was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		GatewayID    string
		OrgUUID      string
	}{
		ArtifactUUID: artifactUUID,
		GatewayID:    gatewayID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetCurrentByGateway.Lock()
	mock.calls.GetCurrentByGateway = append(mock.calls.GetCurrentByGateway, callInfo)
	mock.lockGetCurrentByGateway.Unlock()
	return mock.GetCurrentByGatewayFunc(artifactUUID, gatewayID, orgUUID)
}

// GetCurrentByGatewayCalls gets all the calls that were made to GetCurrentByGateway.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetCurrentByGatewayCalls())
func (mock *DeploymentRepositoryMock) GetCurrentByGatewayCalls() []struct {
	ArtifactUUID string
	GatewayID    string
	OrgUUID      string
} {
	var calls []struct {
		ArtifactUUID string
		GatewayID    string
		OrgUUID      string
	}
	mock.lockGetCurrentByGateway.RLock()
	calls = mock.calls.GetCurrentByGateway
	mock.lockGetCurrentByGateway.RUnlock()
	return calls
}

// GetDeployedGatewaysByProvider calls GetDeployedGatewaysByProviderFunc.
func (mock *DeploymentRepositoryMock) GetDeployedGatewaysByProvider(artifactUUID uuid.UUID, orgUUID string) ([]string, error) {
	if mock.GetDeployedGatewaysByProviderFunc == nil {
		panic("DeploymentRepositoryMock.GetDeployedGatewaysByProviderFunc: method is nil but DeploymentRepository.GetDeployedGatewaysByProvider was just called")
	}
	callInfo := struct {
		ArtifactUUID uuid.UUID
		OrgUUID      string
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetDeployedGatewaysByProvider.Lock()
	mock.calls.GetDeployedGatewaysByProvider = append(mock.calls.GetDeployedGatewaysByProvider, callInfo)
	mock.lockGetDeployedGatewaysByProvider.Unlock()
	return mock.GetDeployedGatewaysByProviderFunc(artifactUUID, orgUUID)
}

// GetDeployedGatewaysByProviderCalls gets all the calls that were made to GetDeployedGatewaysByProvider.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetDeployedGatewaysByProviderCalls())
func (mock *DeploymentRepositoryMock) GetDeployedGatewaysByProviderCalls() []struct {
	ArtifactUUID uuid.UUID
	OrgUUID      string
} {
	var calls []struct {
		ArtifactUUID uuid.UUID
		OrgUUID      string
	}
	mock.lockGetDeployedGatewaysByProvider.RLock()
	calls = mock.calls.GetDeployedGatewaysByProvider
	mock.lockGetDeployedGatewaysByProvider.RUnlock()
	return calls
}

// GetDeployedProvidersByGateway calls GetDeployedProvidersByGatewayFunc.
func (mock *DeploymentRepositoryMock) GetDeployedProvidersByGateway(gatewayUUID uuid.UUID, orgUUID string) ([]string, error) {
	if mock.GetDeployedProvidersByGatewayFunc == nil {
		panic("DeploymentRepositoryMock.GetDeployedProvidersByGatewayFunc: method is nil but DeploymentRepository.GetDeployedProvidersByGateway was just called")
	}
	callInfo := struct {
		GatewayUUID uuid.UUID
		OrgUUID     string
	}{
		GatewayUUID: gatewayUUID,
		OrgUUID:     orgUUID,
	}
	mock.lockGetDeployedProvidersByGateway.Lock()
	mock.calls.GetDeployedProvidersByGateway = append(mock.calls.GetDeployedProvidersByGateway, callInfo)
	mock.lockGetDeployedProvidersByGateway.Unlock()
	return mock.GetDeployedProvidersByGatewayFunc(gatewayUUID, orgUUID)
}

// GetDeployedProvidersByGatewayCalls gets all the calls that were made to GetDeployedProvidersByGateway.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetDeployedProvidersByGatewayCalls())
func (mock *DeploymentRepositoryMock) GetDeployedProvidersByGatewayCalls() []struct {
	GatewayUUID uuid.UUID
	OrgUUID     string
} {
	var calls []struct {
		GatewayUUID uuid.UUID
		OrgUUID     string
	}
	mock.lockGetDeployedProvidersByGateway.RLock()
	calls = mock.calls.GetDeployedProvidersByGateway
	mock.lockGetDeployedProvidersByGateway.RUnlock()
	return calls
}

// GetDeploymentsWithState calls GetDeploymentsWithStateFunc.
func (mock *DeploymentRepositoryMock) GetDeploymentsWithState(artifactUUID string, orgUUID string, gatewayID *string, status *string, maxPerAPIGW int) ([]*models.Deployment, error) {
	if mock.GetDeploymentsWithStateFunc == nil {
		panic("DeploymentRepositoryMock.GetDeploymentsWithStateFunc: method is nil but DeploymentRepository.GetDeploymentsWithState was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    *string
		Status       *string
		MaxPerAPIGW  int
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
		GatewayID:    gatewayID,
		Status:       status,
		MaxPerAPIGW:  maxPerAPIGW,
	}
	mock.lockGetDeploymentsWithState.Lock()
	mock.calls.GetDeploymentsWithState = append(mock.calls.GetDeploymentsWithState, callInfo)
	mock.lockGetDeploymentsWithState.Unlock()
	return mock.GetDeploymentsWithStateFunc(artifactUUID, orgUUID, gatewayID, status, maxPerAPIGW)
}

// GetDeploymentsWithStateCalls gets all the calls that were made to GetDeploymentsWithState.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetDeploymentsWithStateCalls())
func (mock *DeploymentRepositoryMock) GetDeploymentsWithStateCalls() []struct {
	ArtifactUUID string
	OrgUUID      string
	GatewayID    *string
	Status       *string
	MaxPerAPIGW  int
} {
	var calls []struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    *string
		Status       *string
		MaxPerAPIGW  int
	}
	mock.lockGetDeploymentsWithState.RLock()
	calls = mock.calls.GetDeploymentsWithState
	mock.lockGetDeploymentsWithState.RUnlock()
	return calls
}

// GetStatus calls GetStatusFunc.
func (mock *DeploymentRepositoryMock) GetStatus(artifactUUID string, orgUUID string, gatewayID string) (string, models.DeploymentStatus, *time.Time, error) {
	if mock.GetStatusFunc == nil {
		panic("DeploymentRepositoryMock.GetStatusFunc: method is nil but DeploymentRepository.GetStatus was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
		GatewayID:    gatewayID,
	}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc(artifactUUID, orgUUID, gatewayID)
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetStatusCalls())
func (mock *DeploymentRepositoryMock) GetStatusCalls() []struct {
	ArtifactUUID string
	OrgUUID      string
	GatewayID    string
} {
	var calls []struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}

// GetTrackedGatewaysByProvider calls GetTrackedGatewaysByProviderFunc.
func (mock *DeploymentRepositoryMock) GetTrackedGatewaysByProvider(artifactUUID uuid.UUID, orgUUID string) ([]string, error) {
	if mock.GetTrackedGatewaysByProviderFunc == nil {
		panic("DeploymentRepositoryMock.GetTrackedGatewaysByProviderFunc: method is nil but DeploymentRepository.GetTrackedGatewaysByProvider was just called")
	}
	callInfo := struct {
		ArtifactUUID uuid.UUID
		OrgUUID      string
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetTrackedGatewaysByProvider.Lock()
	mock.calls.GetTrackedGatewaysByProvider = append(mock.calls.GetTrackedGatewaysByProvider, callInfo)
	mock.lockGetTrackedGatewaysByProvider.Unlock()
	return mock.GetTrackedGatewaysByProviderFunc(artifactUUID, orgUUID)
}

// GetTrackedGatewaysByProviderCalls gets all the calls that were made to GetTrackedGatewaysByProvider.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetTrackedGatewaysByProviderCalls())
func (mock *DeploymentRepositoryMock) GetTrackedGatewaysByProviderCalls() []struct {
	ArtifactUUID uuid.UUID
	OrgUUID      string
} {
	var calls []struct {
		ArtifactUUID uuid.UUID
		OrgUUID      string
	}
	mock.lockGetTrackedGatewaysByProvider.RLock()
	calls = mock.calls.GetTrackedGatewaysByProvider
	mock.lockGetTrackedGatewaysByProvider.RUnlock()
	return calls
}

// GetWithContent calls GetWithContentFunc.
func (mock *DeploymentRepositoryMock) GetWithContent(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error) {
	if mock.GetWithContentFunc == nil {
		panic("DeploymentRepositoryMock.GetWithContentFunc: method is nil but DeploymentRepository.GetWithContent was just called")
	}
	callInfo := struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}{
		DeploymentID: deploymentID,
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetWithContent.Lock()
	mock.calls.GetWithContent = append(mock.calls.GetWithContent, callInfo)
	mock.lockGetWithContent.Unlock()
	return mock.GetWithContentFunc(deploymentID, artifactUUID, orgUUID)
}

// GetWithContentCalls gets all the calls that were made to GetWithContent.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetWithContentCalls())
func (mock *DeploymentRepositoryMock) GetWithContentCalls() []struct {
	DeploymentID string
	ArtifactUUID string
	OrgUUID      string
} {
	var calls []struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}
	mock.lockGetWithContent.RLock()
	calls = mock.calls.GetWithContent
	mock.lockGetWithContent.RUnlock()
	return calls
}

// GetWithState calls GetWithStateFunc.
func (mock *DeploymentRepositoryMock) GetWithState(deploymentID string, artifactUUID string, orgUUID string) (*models.Deployment, error) {
	if mock.GetWithStateFunc == nil {
		panic("DeploymentRepositoryMock.GetWithStateFunc: method is nil but DeploymentRepository.GetWithState was just called")
	}
	callInfo := struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}{
		DeploymentID: deploymentID,
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockGetWithState.Lock()
	mock.calls.GetWithState = append(mock.calls.GetWithState, callInfo)
	mock.lockGetWithState.Unlock()
	return mock.GetWithStateFunc(deploymentID, artifactUUID, orgUUID)
}

// GetWithStateCalls gets all the calls that were made to GetWithState.
// Check the length with:
//
//	len(mockedDeploymentRepository.GetWithStateCalls())
func (mock *DeploymentRepositoryMock) GetWithStateCalls() []struct {
	DeploymentID string
	ArtifactUUID string
	OrgUUID      string
} {
	var calls []struct {
		DeploymentID string
		ArtifactUUID string
		OrgUUID      string
	}
	mock.lockGetWithState.RLock()
	calls = mock.calls.GetWithState
	mock.lockGetWithState.RUnlock()
	return calls
}

// IsProviderDeployedToGateway calls IsProviderDeployedToGatewayFunc.
func (mock *DeploymentRepositoryMock) IsProviderDeployedToGateway(artifactUUID uuid.UUID, gatewayUUID uuid.UUID, orgUUID string) (bool, error) {
	if mock.IsProviderDeployedToGatewayFunc == nil {
		panic("DeploymentRepositoryMock.IsProviderDeployedToGatewayFunc: method is nil but DeploymentRepository.IsProviderDeployedToGateway was just called")
	}
	callInfo := struct {
		ArtifactUUID uuid.UUID
		GatewayUUID  uuid.UUID
		OrgUUID      string
	}{
		ArtifactUUID: artifactUUID,
		GatewayUUID:  gatewayUUID,
		OrgUUID:      orgUUID,
	}
	mock.lockIsProviderDeployedToGateway.Lock()
	mock.calls.IsProviderDeployedToGateway = append(mock.calls.IsProviderDeployedToGateway, callInfo)
	mock.lockIsProviderDeployedToGateway.Unlock()
	return mock.IsProviderDeployedToGatewayFunc(artifactUUID, gatewayUUID, orgUUID)
}

// IsProviderDeployedToGatewayCalls gets all the calls that were made to IsProviderDeployedToGateway.
// Check the length with:
//
//	len(mockedDeploymentRepository.IsProviderDeployedToGatewayCalls())
func (mock *DeploymentRepositoryMock) IsProviderDeployedToGatewayCalls() []struct {
	ArtifactUUID uuid.UUID
	GatewayUUID  uuid.UUID
	OrgUUID      string
} {
	var calls []struct {
		ArtifactUUID uuid.UUID
		GatewayUUID  uuid.UUID
		OrgUUID      string
	}
	mock.lockIsProviderDeployedToGateway.RLock()
	calls = mock.calls.IsProviderDeployedToGateway
	mock.lockIsProviderDeployedToGateway.RUnlock()
	return calls
}

// SetCurrent calls SetCurrentFunc.
func (mock *DeploymentRepositoryMock) SetCurrent(artifactUUID string, orgUUID string, gatewayID string, deploymentID string, status models.DeploymentStatus) (time.Time, error) {
	if mock.SetCurrentFunc == nil {
		panic("DeploymentRepositoryMock.SetCurrentFunc: method is nil but DeploymentRepository.SetCurrent was just called")
	}
	callInfo := struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
		DeploymentID string
		Status       models.DeploymentStatus
	}{
		ArtifactUUID: artifactUUID,
		OrgUUID:      orgUUID,
		GatewayID:    gatewayID,
		DeploymentID: deploymentID,
		Status:       status,
	}
	mock.lockSetCurrent.Lock()
	mock.calls.SetCurrent = append(mock.calls.SetCurrent, callInfo)
	mock.lockSetCurrent.Unlock()
	return mock.SetCurrentFunc(artifactUUID, orgUUID, gatewayID, deploymentID, status)
}

// SetCurrentCalls gets all the calls that were made to SetCurrent.
// Check the length with:
//
//	len(mockedDeploymentRepository.SetCurrentCalls())
func (mock *DeploymentRepositoryMock) SetCurrentCalls() []struct {
	ArtifactUUID string
	OrgUUID      string
	GatewayID    string
	DeploymentID string
	Status       models.DeploymentStatus
} {
	var calls []struct {
		ArtifactUUID string
		OrgUUID      string
		GatewayID    string
		DeploymentID string
		Status       models.DeploymentStatus
	}
	mock.lockSetCurrent.RLock()
	calls = mock.calls.SetCurrent
	mock.lockSetCurrent.RUnlock()
	return calls
}

// UpdateStatusByDeploymentID calls UpdateStatusByDeploymentIDFunc.
func (mock *DeploymentRepositoryMock) UpdateStatusByDeploymentID(deploymentID string, gatewayUUID string, status models.DeploymentStatus) (time.Time, error) {
	if mock.UpdateStatusByDeploymentIDFunc == nil {
		panic("DeploymentRepositoryMock.UpdateStatusByDeploymentIDFunc: method is nil but DeploymentRepository.UpdateStatusByDeploymentID was just called")
	}
	callInfo := struct {
		DeploymentID string
		GatewayUUID  string
		Status       models.DeploymentStatus
	}{
		DeploymentID: deploymentID,
		GatewayUUID:  gatewayUUID,
		Status:       status,
	}
	mock.lockUpdateStatusByDeploymentID.Lock()
	mock.calls.UpdateStatusByDeploymentID = append(mock.calls.UpdateStatusByDeploymentID, callInfo)
	mock.lockUpdateStatusByDeploymentID.Unlock()
	return mock.UpdateStatusByDeploymentIDFunc(deploymentID, gatewayUUID, status)
}

// UpdateStatusByDeploymentIDCalls gets all the calls that were made to UpdateStatusByDeploymentID.
// Check the length with:
//
//	len(mockedDeploymentRepository.UpdateStatusByDeploymentIDCalls())
func (mock *DeploymentRepositoryMock) UpdateStatusByDeploymentIDCalls() []struct {
	DeploymentID string
	GatewayUUID  string
	Status       models.DeploymentStatus
} {
	var calls []struct {
		DeploymentID string
		GatewayUUID  string
		Status       models.DeploymentStatus
	}
	mock.lockUpdateStatusByDeploymentID.RLock()
	calls = mock.calls.UpdateStatusByDeploymentID
	mock.lockUpdateStatusByDeploymentID.RUnlock()
	return calls
}
