// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// EnvAgentModelMappingRepositoryMock is a mock implementation of repositories.EnvAgentModelMappingRepository.
//
//	func TestSomethingThatUsesEnvAgentModelMappingRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.EnvAgentModelMappingRepository
//		mockedEnvAgentModelMappingRepository := &EnvAgentModelMappingRepositoryMock{
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, tx *gorm.DB, mappingID uint) error {
//				panic("mock out the Delete method")
//			},
//			DeleteByConfigFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
//				panic("mock out the DeleteByConfig method")
//			},
//			GetByConfigAndEnvFunc: func(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) (*models.EnvAgentModelMapping, error) {
//				panic("mock out the GetByConfigAndEnv method")
//			},
//			ListByConfigFunc: func(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentModelMapping, error) {
//				panic("mock out the ListByConfig method")
//			},
//			UpdateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedEnvAgentModelMappingRepository in code that requires repositories.EnvAgentModelMappingRepository
//		// and then make assertions.
//
//	}
type EnvAgentModelMappingRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, tx *gorm.DB, mappingID uint) error

	// DeleteByConfigFunc mocks the DeleteByConfig method.
	DeleteByConfigFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error

	// GetByConfigAndEnvFunc mocks the GetByConfigAndEnv method.
	GetByConfigAndEnvFunc func(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) (*models.EnvAgentModelMapping, error)

	// ListByConfigFunc mocks the ListByConfig method.
	ListByConfigFunc func(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentModelMapping, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.EnvAgentModelMapping
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// MappingID is the mappingID argument value.
			MappingID uint
		}
		// DeleteByConfig holds details about calls to the DeleteByConfig method.
		DeleteByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// GetByConfigAndEnv holds details about calls to the GetByConfigAndEnv method.
		GetByConfigAndEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
			// EnvUUID is the envUUID argument value.
			EnvUUID uuid.UUID
		}
		// ListByConfig holds details about calls to the ListByConfig method.
		ListByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.EnvAgentModelMapping
		}
	}
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockDeleteByConfig    sync.RWMutex
	lockGetByConfigAndEnv sync.RWMutex
	lockListByConfig      sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Create calls CreateFunc.
func (mock *EnvAgentModelMappingRepositoryMock) Create(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error {
	if mock.CreateFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.CreateFunc: method is nil but EnvAgentModelMappingRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentModelMapping
	}{
		Ctx:     ctx,
		Tx:      tx,
		Mapping: mapping,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, mapping)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.CreateCalls())
func (mock *EnvAgentModelMappingRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Mapping *models.EnvAgentModelMapping
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentModelMapping
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *EnvAgentModelMappingRepositoryMock) Delete(ctx context.Context, tx *gorm.DB, mappingID uint) error {
	if mock.DeleteFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.DeleteFunc: method is nil but EnvAgentModelMappingRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MappingID uint
	}{
		Ctx:       ctx,
		Tx:        tx,
		MappingID: mappingID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, tx, mappingID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.DeleteCalls())
func (mock *EnvAgentModelMappingRepositoryMock) DeleteCalls() []struct {
	Ctx       context.Context
	Tx        *gorm.DB
	MappingID uint
} {
	var calls []struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MappingID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteByConfig calls DeleteByConfigFunc.
func (mock *EnvAgentModelMappingRepositoryMock) DeleteByConfig(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
	if mock.DeleteByConfigFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.DeleteByConfigFunc: method is nil but EnvAgentModelMappingRepository.DeleteByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
	}
	mock.lockDeleteByConfig.Lock()
	mock.calls.DeleteByConfig = append(mock.calls.DeleteByConfig, callInfo)
	mock.lockDeleteByConfig.Unlock()
	return mock.DeleteByConfigFunc(ctx, tx, configUUID)
}

// DeleteByConfigCalls gets all the calls that were made to DeleteByConfig.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.DeleteByConfigCalls())
func (mock *EnvAgentModelMappingRepositoryMock) DeleteByConfigCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}
	mock.lockDeleteByConfig.RLock()
	calls = mock.calls.DeleteByConfig
	mock.lockDeleteByConfig.RUnlock()
	return calls
}

// GetByConfigAndEnv calls GetByConfigAndEnvFunc.
func (mock *EnvAgentModelMappingRepositoryMock) GetByConfigAndEnv(ctx context.Context, configUUID uuid.UUID, envUUID uuid.UUID) (*models.EnvAgentModelMapping, error) {
	if mock.GetByConfigAndEnvFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.GetByConfigAndEnvFunc: method is nil but EnvAgentModelMappingRepository.GetByConfigAndEnv was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
		EnvUUID:    envUUID,
	}
	mock.lockGetByConfigAndEnv.Lock()
	mock.calls.GetByConfigAndEnv = append(mock.calls.GetByConfigAndEnv, callInfo)
	mock.lockGetByConfigAndEnv.Unlock()
	return mock.GetByConfigAndEnvFunc(ctx, configUUID, envUUID)
}

// GetByConfigAndEnvCalls gets all the calls that were made to GetByConfigAndEnv.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.GetByConfigAndEnvCalls())
func (mock *EnvAgentModelMappingRepositoryMock) GetByConfigAndEnvCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
	EnvUUID    uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
		EnvUUID    uuid.UUID
	}
	mock.lockGetByConfigAndEnv.RLock()
	calls = mock.calls.GetByConfigAndEnv
	mock.lockGetByConfigAndEnv.RUnlock()
	return calls
}

// ListByConfig calls ListByConfigFunc.
func (mock *EnvAgentModelMappingRepositoryMock) ListByConfig(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentModelMapping, error) {
	if mock.ListByConfigFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.ListByConfigFunc: method is nil but EnvAgentModelMappingRepository.ListByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
	}
	mock.lockListByConfig.Lock()
	mock.calls.ListByConfig = append(mock.calls.ListByConfig, callInfo)
	mock.lockListByConfig.Unlock()
	return mock.ListByConfigFunc(ctx, configUUID)
}

// ListByConfigCalls gets all the calls that were made to ListByConfig.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.ListByConfigCalls())
func (mock *EnvAgentModelMappingRepositoryMock) ListByConfigCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}
	mock.lockListByConfig.RLock()
	calls = mock.calls.ListByConfig
	mock.lockListByConfig.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *EnvAgentModelMappingRepositoryMock) Update(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentModelMapping) error {
	if mock.UpdateFunc == nil {
		panic("EnvAgentModelMappingRepositoryMock.UpdateFunc: method is nil but EnvAgentModelMappingRepository.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentModelMapping
	}{
		Ctx:     ctx,
		Tx:      tx,
		Mapping: mapping,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, tx, mapping)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedEnvAgentModelMappingRepository.UpdateCalls())
func (mock *EnvAgentModelMappingRepositoryMock) UpdateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Mapping *models.EnvAgentModelMapping
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentModelMapping
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
