// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// EnvAgentMCPMappingRepositoryMock is a mock implementation of repositories.EnvAgentMCPMappingRepository.
//
//	func TestSomethingThatUsesEnvAgentMCPMappingRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.EnvAgentMCPMappingRepository
//		mockedEnvAgentMCPMappingRepository := &EnvAgentMCPMappingRepositoryMock{
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping, proxyMapping *models.MCPProxyMapping, handle string, name string, version string, orgName string) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, tx *gorm.DB, mappingID uint) error {
//				panic("mock out the Delete method")
//			},
//			DeleteByConfigFunc: func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
//				panic("mock out the DeleteByConfig method")
//			},
//			ListByConfigFunc: func(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error) {
//				panic("mock out the ListByConfig method")
//			},
//			ListByMCPProxyFunc: func(ctx context.Context, mcpProxyUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error) {
//				panic("mock out the ListByMCPProxy method")
//			},
//			UpdateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedEnvAgentMCPMappingRepository in code that requires repositories.EnvAgentMCPMappingRepository
//		// and then make assertions.
//
//	}
type EnvAgentMCPMappingRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping, proxyMapping *models.MCPProxyMapping, handle string, name string, version string, orgName string) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, tx *gorm.DB, mappingID uint) error

	// DeleteByConfigFunc mocks the DeleteByConfig method.
	DeleteByConfigFunc func(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error

	// ListByConfigFunc mocks the ListByConfig method.
	ListByConfigFunc func(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error)

	// ListByMCPProxyFunc mocks the ListByMCPProxy method.
	ListByMCPProxyFunc func(ctx context.Context, mcpProxyUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.EnvAgentMCPMapping
			// ProxyMapping is the proxyMapping argument value.
			ProxyMapping *models.MCPProxyMapping
			// Handle is the handle argument value.
			Handle string
			// Name is the name argument value.
			Name string
			// Version is the version argument value.
			Version string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// MappingID is the mappingID argument value.
			MappingID uint
		}
		// DeleteByConfig holds details about calls to the DeleteByConfig method.
		DeleteByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// ListByConfig holds details about calls to the ListByConfig method.
		ListByConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigUUID is the configUUID argument value.
			ConfigUUID uuid.UUID
		}
		// ListByMCPProxy holds details about calls to the ListByMCPProxy method.
		ListByMCPProxy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// McpProxyUUID is the mcpProxyUUID argument value.
			McpProxyUUID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.EnvAgentMCPMapping
		}
	}
	lockCreate         sync.RWMutex
	lockDelete         sync.RWMutex
	lockDeleteByConfig sync.RWMutex
	lockListByConfig   sync.RWMutex
	lockListByMCPProxy sync.RWMutex
	lockUpdate         sync.RWMutex
}

// Create calls CreateFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) Create(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping, proxyMapping *models.MCPProxyMapping, handle string, name string, version string, orgName string) error {
	if mock.CreateFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.CreateFunc: method is nil but EnvAgentMCPMappingRepository.Create was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Tx           *gorm.DB
		Mapping      *models.EnvAgentMCPMapping
		ProxyMapping *models.MCPProxyMapping
		Handle       string
		Name         string
		Version      string
		OrgName      string
	}{
		Ctx:          ctx,
		Tx:           tx,
		Mapping:      mapping,
		ProxyMapping: proxyMapping,
		Handle:       handle,
		Name:         name,
		Version:      version,
		OrgName:      orgName,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, mapping, proxyMapping, handle, name, version, orgName)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.CreateCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) CreateCalls() []struct {
	Ctx          context.Context
	Tx           *gorm.DB
	Mapping      *models.EnvAgentMCPMapping
	ProxyMapping *models.MCPProxyMapping
	Handle       string
	Name         string
	Version      string
	OrgName      string
} {
	var calls []struct {
		Ctx          context.Context
		Tx           *gorm.DB
		Mapping      *models.EnvAgentMCPMapping
		ProxyMapping *models.MCPProxyMapping
		Handle       string
		Name         string
		Version      string
		OrgName      string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) Delete(ctx context.Context, tx *gorm.DB, mappingID uint) error {
	if mock.DeleteFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.DeleteFunc: method is nil but EnvAgentMCPMappingRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MappingID uint
	}{
		Ctx:       ctx,
		Tx:        tx,
		MappingID: mappingID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, tx, mappingID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.DeleteCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) DeleteCalls() []struct {
	Ctx       context.Context
	Tx        *gorm.DB
	MappingID uint
} {
	var calls []struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MappingID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteByConfig calls DeleteByConfigFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) DeleteByConfig(ctx context.Context, tx *gorm.DB, configUUID uuid.UUID) error {
	if mock.DeleteByConfigFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.DeleteByConfigFunc: method is nil but EnvAgentMCPMappingRepository.DeleteByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		Tx:         tx,
		ConfigUUID: configUUID,
	}
	mock.lockDeleteByConfig.Lock()
	mock.calls.DeleteByConfig = append(mock.calls.DeleteByConfig, callInfo)
	mock.lockDeleteByConfig.Unlock()
	return mock.DeleteByConfigFunc(ctx, tx, configUUID)
}

// DeleteByConfigCalls gets all the calls that were made to DeleteByConfig.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.DeleteByConfigCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) DeleteByConfigCalls() []struct {
	Ctx        context.Context
	Tx         *gorm.DB
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		Tx         *gorm.DB
		ConfigUUID uuid.UUID
	}
	mock.lockDeleteByConfig.RLock()
	calls = mock.calls.DeleteByConfig
	mock.lockDeleteByConfig.RUnlock()
	return calls
}

// ListByConfig calls ListByConfigFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) ListByConfig(ctx context.Context, configUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error) {
	if mock.ListByConfigFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.ListByConfigFunc: method is nil but EnvAgentMCPMappingRepository.ListByConfig was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}{
		Ctx:        ctx,
		ConfigUUID: configUUID,
	}
	mock.lockListByConfig.Lock()
	mock.calls.ListByConfig = append(mock.calls.ListByConfig, callInfo)
	mock.lockListByConfig.Unlock()
	return mock.ListByConfigFunc(ctx, configUUID)
}

// ListByConfigCalls gets all the calls that were made to ListByConfig.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.ListByConfigCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) ListByConfigCalls() []struct {
	Ctx        context.Context
	ConfigUUID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ConfigUUID uuid.UUID
	}
	mock.lockListByConfig.RLock()
	calls = mock.calls.ListByConfig
	mock.lockListByConfig.RUnlock()
	return calls
}

// ListByMCPProxy calls ListByMCPProxyFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) ListByMCPProxy(ctx context.Context, mcpProxyUUID uuid.UUID) ([]models.EnvAgentMCPMapping, error) {
	if mock.ListByMCPProxyFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.ListByMCPProxyFunc: method is nil but EnvAgentMCPMappingRepository.ListByMCPProxy was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		McpProxyUUID uuid.UUID
	}{
		Ctx:          ctx,
		McpProxyUUID: mcpProxyUUID,
	}
	mock.lockListByMCPProxy.Lock()
	mock.calls.ListByMCPProxy = append(mock.calls.ListByMCPProxy, callInfo)
	mock.lockListByMCPProxy.Unlock()
	return mock.ListByMCPProxyFunc(ctx, mcpProxyUUID)
}

// ListByMCPProxyCalls gets all the calls that were made to ListByMCPProxy.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.ListByMCPProxyCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) ListByMCPProxyCalls() []struct {
	Ctx          context.Context
	McpProxyUUID uuid.UUID
} {
	var calls []struct {
		Ctx          context.Context
		McpProxyUUID uuid.UUID
	}
	mock.lockListByMCPProxy.RLock()
	calls = mock.calls.ListByMCPProxy
	mock.lockListByMCPProxy.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *EnvAgentMCPMappingRepositoryMock) Update(ctx context.Context, tx *gorm.DB, mapping *models.EnvAgentMCPMapping) error {
	if mock.UpdateFunc == nil {
		panic("EnvAgentMCPMappingRepositoryMock.UpdateFunc: method is nil but EnvAgentMCPMappingRepository.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentMCPMapping
	}{
		Ctx:     ctx,
		Tx:      tx,
		Mapping: mapping,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, tx, mapping)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedEnvAgentMCPMappingRepository.UpdateCalls())
func (mock *EnvAgentMCPMappingRepositoryMock) UpdateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Mapping *models.EnvAgentMCPMapping
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.EnvAgentMCPMapping
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
