// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"github.com/wso2/agent-manager/agent-manager-service/repositories"
)

// GatewayRepositoryMock is a mock implementation of repositories.GatewayRepository.
//
//	func TestSomethingThatUsesGatewayRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.GatewayRepository
//		mockedGatewayRepository := &GatewayRepositoryMock{
//			CountActiveTokensFunc: func(gatewayId string) (int, error) {
//				panic("mock out the CountActiveTokens method")
//			},
//			CountWithFiltersFunc: func(filters repositories.GatewayFilterOptions) (int64, error) {
//				panic("mock out the CountWithFilters method")
//			},
//			CreateFunc: func(gateway *models.Gateway) error {
//				panic("mock out the Create method")
//			},
//			CreateEnvironmentMappingFunc: func(mapping *models.GatewayEnvironmentMapping) error {
//				panic("mock out the CreateEnvironmentMapping method")
//			},
//			CreateTokenFunc: func(token *models.GatewayToken) error {
//				panic("mock out the CreateToken method")
//			},
//			DeleteFunc: func(gatewayID string, orgName string) error {
//				panic("mock out the Delete method")
//			},
//			DeleteEnvironmentMappingFunc: func(gatewayID string, environmentID string) error {
//				panic("mock out the DeleteEnvironmentMapping method")
//			},
//			DeleteEnvironmentMappingsByEnvironmentIDFunc: func(environmentID string) (int64, error) {
//				panic("mock out the DeleteEnvironmentMappingsByEnvironmentID method")
//			},
//			DeleteIdentityProviderFunc: func(gatewayID string, name string) error {
//				panic("mock out the DeleteIdentityProvider method")
//			},
//			EnvironmentMappingExistsFunc: func(gatewayID string, environmentID string) (bool, error) {
//				panic("mock out the EnvironmentMappingExists method")
//			},
//			GetActiveTokenByPrefixFunc: func(tokenPrefix string) (*models.GatewayToken, error) {
//				panic("mock out the GetActiveTokenByPrefix method")
//			},
//			GetActiveTokensByGatewayUUIDFunc: func(gatewayId string) ([]*models.GatewayToken, error) {
//				panic("mock out the GetActiveTokensByGatewayUUID method")
//			},
//			GetByNameAndOrgIDFunc: func(name string, orgName string) (*models.Gateway, error) {
//				panic("mock out the GetByNameAndOrgID method")
//			},
//			GetByOrganizationIDFunc: func(orgName string) ([]*models.Gateway, error) {
//				panic("mock out the GetByOrganizationID method")
//			},
//			GetByUUIDFunc: func(gatewayId string) (*models.Gateway, error) {
//				panic("mock out the GetByUUID method")
//			},
//			GetEnvironmentMappingsByEnvironmentIDFunc: func(environmentID string) ([]models.GatewayEnvironmentMapping, error) {
//				panic("mock out the GetEnvironmentMappingsByEnvironmentID method")
//			},
//			GetEnvironmentMappingsByGatewayIDFunc: func(gatewayID string) ([]models.GatewayEnvironmentMapping, error) {
//				panic("mock out the GetEnvironmentMappingsByGatewayID method")
//			},
//			GetEnvironmentMappingsByGatewayIDsFunc: func(gatewayIDs []string) (map[string][]models.GatewayEnvironmentMapping, error) {
//				panic("mock out the GetEnvironmentMappingsByGatewayIDs method")
//			},
//			GetTokenByUUIDFunc: func(tokenId string) (*models.GatewayToken, error) {
//				panic("mock out the GetTokenByUUID method")
//			},
//			HasGatewayAssociationsFunc: func(gatewayID string, orgName string) (bool, error) {
//				panic("mock out the HasGatewayAssociations method")
//			},
//			HasGatewayAssociationsOrDeploymentsFunc: func(gatewayID string, orgName string) (bool, error) {
//				panic("mock out the HasGatewayAssociationsOrDeployments method")
//			},
//			HasGatewayDeploymentsFunc: func(gatewayID string, orgName string) (bool, error) {
//				panic("mock out the HasGatewayDeployments method")
//			},
//			ListFunc: func() ([]*models.Gateway, error) {
//				panic("mock out the List method")
//			},
//			ListIdentityProvidersByEnvironmentFunc: func(environmentID string) ([]models.GatewayIdentityProvider, error) {
//				panic("mock out the ListIdentityProvidersByEnvironment method")
//			},
//			ListIdentityProvidersByGatewayFunc: func(gatewayID string) ([]models.GatewayIdentityProvider, error) {
//				panic("mock out the ListIdentityProvidersByGateway method")
//			},
//			ListIdentityProvidersByOrgFunc: func(orgName string) ([]repositories.IdentityProviderWithContext, error) {
//				panic("mock out the ListIdentityProvidersByOrg method")
//			},
//			ListWithFiltersFunc: func(filters repositories.GatewayFilterOptions) ([]*models.Gateway, error) {
//				panic("mock out the ListWithFilters method")
//			},
//			RevokeTokenFunc: func(tokenId string) error {
//				panic("mock out the RevokeToken method")
//			},
//			UpdateActiveStatusFunc: func(gatewayId string, isActive bool) error {
//				panic("mock out the UpdateActiveStatus method")
//			},
//			UpdateGatewayFunc: func(gateway *models.Gateway) error {
//				panic("mock out the UpdateGateway method")
//			},
//			UpsertIdentityProviderFunc: func(provider *models.GatewayIdentityProvider) error {
//				panic("mock out the UpsertIdentityProvider method")
//			},
//		}
//
//		// use mockedGatewayRepository in code that requires repositories.GatewayRepository
//		// and then make assertions.
//
//	}
type GatewayRepositoryMock struct {
	// CountActiveTokensFunc mocks the CountActiveTokens method.
	CountActiveTokensFunc func(gatewayId string) (int, error)

	// CountWithFiltersFunc mocks the CountWithFilters method.
	CountWithFiltersFunc func(filters repositories.GatewayFilterOptions) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(gateway *models.Gateway) error

	// CreateEnvironmentMappingFunc mocks the CreateEnvironmentMapping method.
	CreateEnvironmentMappingFunc func(mapping *models.GatewayEnvironmentMapping) error

	// CreateTokenFunc mocks the CreateToken method.
	CreateTokenFunc func(token *models.GatewayToken) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(gatewayID string, orgName string) error

	// DeleteEnvironmentMappingFunc mocks the DeleteEnvironmentMapping method.
	DeleteEnvironmentMappingFunc func(gatewayID string, environmentID string) error

	// DeleteEnvironmentMappingsByEnvironmentIDFunc mocks the DeleteEnvironmentMappingsByEnvironmentID method.
	DeleteEnvironmentMappingsByEnvironmentIDFunc func(environmentID string) (int64, error)

	// DeleteIdentityProviderFunc mocks the DeleteIdentityProvider method.
	DeleteIdentityProviderFunc func(gatewayID string, name string) error

	// EnvironmentMappingExistsFunc mocks the EnvironmentMappingExists method.
	EnvironmentMappingExistsFunc func(gatewayID string, environmentID string) (bool, error)

	// GetActiveTokenByPrefixFunc mocks the GetActiveTokenByPrefix method.
	GetActiveTokenByPrefixFunc func(tokenPrefix string) (*models.GatewayToken, error)

	// GetActiveTokensByGatewayUUIDFunc mocks the GetActiveTokensByGatewayUUID method.
	GetActiveTokensByGatewayUUIDFunc func(gatewayId string) ([]*models.GatewayToken, error)

	// GetByNameAndOrgIDFunc mocks the GetByNameAndOrgID method.
	GetByNameAndOrgIDFunc func(name string, orgName string) (*models.Gateway, error)

	// GetByOrganizationIDFunc mocks the GetByOrganizationID method.
	GetByOrganizationIDFunc func(orgName string) ([]*models.Gateway, error)

	// GetByUUIDFunc mocks the GetByUUID method.
	GetByUUIDFunc func(gatewayId string) (*models.Gateway, error)

	// GetEnvironmentMappingsByEnvironmentIDFunc mocks the GetEnvironmentMappingsByEnvironmentID method.
	GetEnvironmentMappingsByEnvironmentIDFunc func(environmentID string) ([]models.GatewayEnvironmentMapping, error)

	// GetEnvironmentMappingsByGatewayIDFunc mocks the GetEnvironmentMappingsByGatewayID method.
	GetEnvironmentMappingsByGatewayIDFunc func(gatewayID string) ([]models.GatewayEnvironmentMapping, error)

	// GetEnvironmentMappingsByGatewayIDsFunc mocks the GetEnvironmentMappingsByGatewayIDs method.
	GetEnvironmentMappingsByGatewayIDsFunc func(gatewayIDs []string) (map[string][]models.GatewayEnvironmentMapping, error)

	// GetTokenByUUIDFunc mocks the GetTokenByUUID method.
	GetTokenByUUIDFunc func(tokenId string) (*models.GatewayToken, error)

	// HasGatewayAssociationsFunc mocks the HasGatewayAssociations method.
	HasGatewayAssociationsFunc func(gatewayID string, orgName string) (bool, error)

	// HasGatewayAssociationsOrDeploymentsFunc mocks the HasGatewayAssociationsOrDeployments method.
	HasGatewayAssociationsOrDeploymentsFunc func(gatewayID string, orgName string) (bool, error)

	// HasGatewayDeploymentsFunc mocks the HasGatewayDeployments method.
	HasGatewayDeploymentsFunc func(gatewayID string, orgName string) (bool, error)

	// ListFunc mocks the List method.
	ListFunc func() ([]*models.Gateway, error)

	// ListIdentityProvidersByEnvironmentFunc mocks the ListIdentityProvidersByEnvironment method.
	ListIdentityProvidersByEnvironmentFunc func(environmentID string) ([]models.GatewayIdentityProvider, error)

	// ListIdentityProvidersByGatewayFunc mocks the ListIdentityProvidersByGateway method.
	ListIdentityProvidersByGatewayFunc func(gatewayID string) ([]models.GatewayIdentityProvider, error)

	// ListIdentityProvidersByOrgFunc mocks the ListIdentityProvidersByOrg method.
	ListIdentityProvidersByOrgFunc func(orgName string) ([]repositories.IdentityProviderWithContext, error)

	// ListWithFiltersFunc mocks the ListWithFilters method.
	ListWithFiltersFunc func(filters repositories.GatewayFilterOptions) ([]*models.Gateway, error)

	// RevokeTokenFunc mocks the RevokeToken method.
	RevokeTokenFunc func(tokenId string) error

	// UpdateActiveStatusFunc mocks the UpdateActiveStatus method.
	UpdateActiveStatusFunc func(gatewayId string, isActive bool) error

	// UpdateGatewayFunc mocks the UpdateGateway method.
	UpdateGatewayFunc func(gateway *models.Gateway) error

	// UpsertIdentityProviderFunc mocks the UpsertIdentityProvider method.
	UpsertIdentityProviderFunc func(provider *models.GatewayIdentityProvider) error

	// calls tracks calls to the methods.
	calls struct {
		// CountActiveTokens holds details about calls to the CountActiveTokens method.
		CountActiveTokens []struct {
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
		// CountWithFilters holds details about calls to the CountWithFilters method.
		CountWithFilters []struct {
			// Filters is the filters argument value.
			Filters repositories.GatewayFilterOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Gateway is the gateway argument value.
			Gateway *models.Gateway
		}
		// CreateEnvironmentMapping holds details about calls to the CreateEnvironmentMapping method.
		CreateEnvironmentMapping []struct {
			// Mapping is the mapping argument value.
			Mapping *models.GatewayEnvironmentMapping
		}
		// CreateToken holds details about calls to the CreateToken method.
		CreateToken []struct {
			// Token is the token argument value.
			Token *models.GatewayToken
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// DeleteEnvironmentMapping holds details about calls to the DeleteEnvironmentMapping method.
		DeleteEnvironmentMapping []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// EnvironmentID is the environmentID argument value.
			EnvironmentID string
		}
		// DeleteEnvironmentMappingsByEnvironmentID holds details about calls to the DeleteEnvironmentMappingsByEnvironmentID method.
		DeleteEnvironmentMappingsByEnvironmentID []struct {
			// EnvironmentID is the environmentID argument value.
			EnvironmentID string
		}
		// DeleteIdentityProvider holds details about calls to the DeleteIdentityProvider method.
		DeleteIdentityProvider []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// Name is the name argument value.
			Name string
		}
		// EnvironmentMappingExists holds details about calls to the EnvironmentMappingExists method.
		EnvironmentMappingExists []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// EnvironmentID is the environmentID argument value.
			EnvironmentID string
		}
		// GetActiveTokenByPrefix holds details about calls to the GetActiveTokenByPrefix method.
		GetActiveTokenByPrefix []struct {
			// TokenPrefix is the tokenPrefix argument value.
			TokenPrefix string
		}
		// GetActiveTokensByGatewayUUID holds details about calls to the GetActiveTokensByGatewayUUID method.
		GetActiveTokensByGatewayUUID []struct {
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
		// GetByNameAndOrgID holds details about calls to the GetByNameAndOrgID method.
		GetByNameAndOrgID []struct {
			// Name is the name argument value.
			Name string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetByOrganizationID holds details about calls to the GetByOrganizationID method.
		GetByOrganizationID []struct {
			// OrgName is the orgName argument value.
			OrgName string
		}
		// GetByUUID holds details about calls to the GetByUUID method.
		GetByUUID []struct {
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
		// GetEnvironmentMappingsByEnvironmentID holds details about calls to the GetEnvironmentMappingsByEnvironmentID method.
		GetEnvironmentMappingsByEnvironmentID []struct {
			// EnvironmentID is the environmentID argument value.
			EnvironmentID string
		}
		// GetEnvironmentMappingsByGatewayID holds details about calls to the GetEnvironmentMappingsByGatewayID method.
		GetEnvironmentMappingsByGatewayID []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetEnvironmentMappingsByGatewayIDs holds details about calls to the GetEnvironmentMappingsByGatewayIDs method.
		GetEnvironmentMappingsByGatewayIDs []struct {
			// GatewayIDs is the gatewayIDs argument value.
			GatewayIDs []string
		}
		// GetTokenByUUID holds details about calls to the GetTokenByUUID method.
		GetTokenByUUID []struct {
			// TokenId is the tokenId argument value.
			TokenId string
		}
		// HasGatewayAssociations holds details about calls to the HasGatewayAssociations method.
		HasGatewayAssociations []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// HasGatewayAssociationsOrDeployments holds details about calls to the HasGatewayAssociationsOrDeployments method.
		HasGatewayAssociationsOrDeployments []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// HasGatewayDeployments holds details about calls to the HasGatewayDeployments method.
		HasGatewayDeployments []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// OrgName is the orgName argument value.
			OrgName string
		}
		// List holds details about calls to the List method.
		List []struct {
		}
		// ListIdentityProvidersByEnvironment holds details about calls to the ListIdentityProvidersByEnvironment method.
		ListIdentityProvidersByEnvironment []struct {
			// EnvironmentID is the environmentID argument value.
			EnvironmentID string
		}
		// ListIdentityProvidersByGateway holds details about calls to the ListIdentityProvidersByGateway method.
		ListIdentityProvidersByGateway []struct {
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// ListIdentityProvidersByOrg holds details about calls to the ListIdentityProvidersByOrg method.
		ListIdentityProvidersByOrg []struct {
			// OrgName is the orgName argument value.
			OrgName string
		}
		// ListWithFilters holds details about calls to the ListWithFilters method.
		ListWithFilters []struct {
			// Filters is the filters argument value.
			Filters repositories.GatewayFilterOptions
		}
		// RevokeToken holds details about calls to the RevokeToken method.
		RevokeToken []struct {
			// TokenId is the tokenId argument value.
			TokenId string
		}
		// UpdateActiveStatus holds details about calls to the UpdateActiveStatus method.
		UpdateActiveStatus []struct {
			// GatewayId is the gatewayId argument value.
			GatewayId string
			// IsActive is the isActive argument value.
			IsActive bool
		}
		// UpdateGateway holds details about calls to the UpdateGateway method.
		UpdateGateway []struct {
			// Gateway is the gateway argument value.
			Gateway *models.Gateway
		}
		// UpsertIdentityProvider holds details about calls to the UpsertIdentityProvider method.
		UpsertIdentityProvider []struct {
			// Provider is the provider argument value.
			Provider *models.GatewayIdentityProvider
		}
	}
	lockCountActiveTokens                        sync.RWMutex
	lockCountWithFilters                         sync.RWMutex
	lockCreate                                   sync.RWMutex
	lockCreateEnvironmentMapping                 sync.RWMutex
	lockCreateToken                              sync.RWMutex
	lockDelete                                   sync.RWMutex
	lockDeleteEnvironmentMapping                 sync.RWMutex
	lockDeleteEnvironmentMappingsByEnvironmentID sync.RWMutex
	lockDeleteIdentityProvider                   sync.RWMutex
	lockEnvironmentMappingExists                 sync.RWMutex
	lockGetActiveTokenByPrefix                   sync.RWMutex
	lockGetActiveTokensByGatewayUUID             sync.RWMutex
	lockGetByNameAndOrgID                        sync.RWMutex
	lockGetByOrganizationID                      sync.RWMutex
	lockGetByUUID                                sync.RWMutex
	lockGetEnvironmentMappingsByEnvironmentID    sync.RWMutex
	lockGetEnvironmentMappingsByGatewayID        sync.RWMutex
	lockGetEnvironmentMappingsByGatewayIDs       sync.RWMutex
	lockGetTokenByUUID                           sync.RWMutex
	lockHasGatewayAssociations                   sync.RWMutex
	lockHasGatewayAssociationsOrDeployments      sync.RWMutex
	lockHasGatewayDeployments                    sync.RWMutex
	lockList                                     sync.RWMutex
	lockListIdentityProvidersByEnvironment       sync.RWMutex
	lockListIdentityProvidersByGateway           sync.RWMutex
	lockListIdentityProvidersByOrg               sync.RWMutex
	lockListWithFilters                          sync.RWMutex
	lockRevokeToken                              sync.RWMutex
	lockUpdateActiveStatus                       sync.RWMutex
	lockUpdateGateway                            sync.RWMutex
	lockUpsertIdentityProvider                   sync.RWMutex
}

// CountActiveTokens calls CountActiveTokensFunc.
func (mock *GatewayRepositoryMock) CountActiveTokens(gatewayId string) (int, error) {
	if mock.CountActiveTokensFunc == nil {
		panic("GatewayRepositoryMock.CountActiveTokensFunc: method is nil but GatewayRepository.CountActiveTokens was just called")
	}
	callInfo := struct {
		GatewayId string
	}{
		GatewayId: gatewayId,
	}
	mock.lockCountActiveTokens.Lock()
	mock.calls.CountActiveTokens = append(mock.calls.CountActiveTokens, callInfo)
	mock.lockCountActiveTokens.Unlock()
	return mock.CountActiveTokensFunc(gatewayId)
}

// CountActiveTokensCalls gets all the calls that were made to CountActiveTokens.
// Check the length with:
//
//	len(mockedGatewayRepository.CountActiveTokensCalls())
func (mock *GatewayRepositoryMock) CountActiveTokensCalls() []struct {
	GatewayId string
} {
	var calls []struct {
		GatewayId string
	}
	mock.lockCountActiveTokens.RLock()
	calls = mock.calls.CountActiveTokens
	mock.lockCountActiveTokens.RUnlock()
	return calls
}

// CountWithFilters calls CountWithFiltersFunc.
func (mock *GatewayRepositoryMock) CountWithFilters(filters repositories.GatewayFilterOptions) (int64, error) {
	if mock.CountWithFiltersFunc == nil {
		panic("GatewayRepositoryMock.CountWithFiltersFunc: method is nil but GatewayRepository.CountWithFilters was just called")
	}
	callInfo := struct {
		Filters repositories.GatewayFilterOptions
	}{
		Filters: filters,
	}
	mock.lockCountWithFilters.Lock()
	mock.calls.CountWithFilters = append(mock.calls.CountWithFilters, callInfo)
	mock.lockCountWithFilters.Unlock()
	return mock.CountWithFiltersFunc(filters)
}

// CountWithFiltersCalls gets all the calls that were made to CountWithFilters.
// Check the length with:
//
//	len(mockedGatewayRepository.CountWithFiltersCalls())
func (mock *GatewayRepositoryMock) CountWithFiltersCalls() []struct {
	Filters repositories.GatewayFilterOptions
} {
	var calls []struct {
		Filters repositories.GatewayFilterOptions
	}
	mock.lockCountWithFilters.RLock()
	calls = mock.calls.CountWithFilters
	mock.lockCountWithFilters.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *GatewayRepositoryMock) Create(gateway *models.Gateway) error {
	if mock.CreateFunc == nil {
		panic("GatewayRepositoryMock.CreateFunc: method is nil but GatewayRepository.Create was just called")
	}
	callInfo := struct {
		Gateway *models.Gateway
	}{
		Gateway: gateway,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(gateway)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedGatewayRepository.CreateCalls())
func (mock *GatewayRepositoryMock) CreateCalls() []struct {
	Gateway *models.Gateway
} {
	var calls []struct {
		Gateway *models.Gateway
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// CreateEnvironmentMapping calls CreateEnvironmentMappingFunc.
func (mock *GatewayRepositoryMock) CreateEnvironmentMapping(mapping *models.GatewayEnvironmentMapping) error {
	if mock.CreateEnvironmentMappingFunc == nil {
		panic("GatewayRepositoryMock.CreateEnvironmentMappingFunc: method is nil but GatewayRepository.CreateEnvironmentMapping was just called")
	}
	callInfo := struct {
		Mapping *models.GatewayEnvironmentMapping
	}{
		Mapping: mapping,
	}
	mock.lockCreateEnvironmentMapping.Lock()
	mock.calls.CreateEnvironmentMapping = append(mock.calls.CreateEnvironmentMapping, callInfo)
	mock.lockCreateEnvironmentMapping.Unlock()
	return mock.CreateEnvironmentMappingFunc(mapping)
}

// CreateEnvironmentMappingCalls gets all the calls that were made to CreateEnvironmentMapping.
// Check the length with:
//
//	len(mockedGatewayRepository.CreateEnvironmentMappingCalls())
func (mock *GatewayRepositoryMock) CreateEnvironmentMappingCalls() []struct {
	Mapping *models.GatewayEnvironmentMapping
} {
	var calls []struct {
		Mapping *models.GatewayEnvironmentMapping
	}
	mock.lockCreateEnvironmentMapping.RLock()
	calls = mock.calls.CreateEnvironmentMapping
	mock.lockCreateEnvironmentMapping.RUnlock()
	return calls
}

// CreateToken calls CreateTokenFunc.
func (mock *GatewayRepositoryMock) CreateToken(token *models.GatewayToken) error {
	if mock.CreateTokenFunc == nil {
		panic("GatewayRepositoryMock.CreateTokenFunc: method is nil but GatewayRepository.CreateToken was just called")
	}
	callInfo := struct {
		Token *models.GatewayToken
	}{
		Token: token,
	}
	mock.lockCreateToken.Lock()
	mock.calls.CreateToken = append(mock.calls.CreateToken, callInfo)
	mock.lockCreateToken.Unlock()
	return mock.CreateTokenFunc(token)
}

// CreateTokenCalls gets all the calls that were made to CreateToken.
// Check the length with:
//
//	len(mockedGatewayRepository.CreateTokenCalls())
func (mock *GatewayRepositoryMock) CreateTokenCalls() []struct {
	Token *models.GatewayToken
} {
	var calls []struct {
		Token *models.GatewayToken
	}
	mock.lockCreateToken.RLock()
	calls = mock.calls.CreateToken
	mock.lockCreateToken.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *GatewayRepositoryMock) Delete(gatewayID string, orgName string) error {
	if mock.DeleteFunc == nil {
		panic("GatewayRepositoryMock.DeleteFunc: method is nil but GatewayRepository.Delete was just called")
	}
	callInfo := struct {
		GatewayID string
		OrgName   string
	}{
		GatewayID: gatewayID,
		OrgName:   orgName,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(gatewayID, orgName)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedGatewayRepository.DeleteCalls())
func (mock *GatewayRepositoryMock) DeleteCalls() []struct {
	GatewayID string
	OrgName   string
} {
	var calls []struct {
		GatewayID string
		OrgName   string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteEnvironmentMapping calls DeleteEnvironmentMappingFunc.
func (mock *GatewayRepositoryMock) DeleteEnvironmentMapping(gatewayID string, environmentID string) error {
	if mock.DeleteEnvironmentMappingFunc == nil {
		panic("GatewayRepositoryMock.DeleteEnvironmentMappingFunc: method is nil but GatewayRepository.DeleteEnvironmentMapping was just called")
	}
	callInfo := struct {
		GatewayID     string
		EnvironmentID string
	}{
		GatewayID:     gatewayID,
		EnvironmentID: environmentID,
	}
	mock.lockDeleteEnvironmentMapping.Lock()
	mock.calls.DeleteEnvironmentMapping = append(mock.calls.DeleteEnvironmentMapping, callInfo)
	mock.lockDeleteEnvironmentMapping.Unlock()
	return mock.DeleteEnvironmentMappingFunc(gatewayID, environmentID)
}

// DeleteEnvironmentMappingCalls gets all the calls that were made to DeleteEnvironmentMapping.
// Check the length with:
//
//	len(mockedGatewayRepository.DeleteEnvironmentMappingCalls())
func (mock *GatewayRepositoryMock) DeleteEnvironmentMappingCalls() []struct {
	GatewayID     string
	EnvironmentID string
} {
	var calls []struct {
		GatewayID     string
		EnvironmentID string
	}
	mock.lockDeleteEnvironmentMapping.RLock()
	calls = mock.calls.DeleteEnvironmentMapping
	mock.lockDeleteEnvironmentMapping.RUnlock()
	return calls
}

// DeleteEnvironmentMappingsByEnvironmentID calls DeleteEnvironmentMappingsByEnvironmentIDFunc.
func (mock *GatewayRepositoryMock) DeleteEnvironmentMappingsByEnvironmentID(environmentID string) (int64, error) {
	if mock.DeleteEnvironmentMappingsByEnvironmentIDFunc == nil {
		panic("GatewayRepositoryMock.DeleteEnvironmentMappingsByEnvironmentIDFunc: method is nil but GatewayRepository.DeleteEnvironmentMappingsByEnvironmentID was just called")
	}
	callInfo := struct {
		EnvironmentID string
	}{
		EnvironmentID: environmentID,
	}
	mock.lockDeleteEnvironmentMappingsByEnvironmentID.Lock()
	mock.calls.DeleteEnvironmentMappingsByEnvironmentID = append(mock.calls.DeleteEnvironmentMappingsByEnvironmentID, callInfo)
	mock.lockDeleteEnvironmentMappingsByEnvironmentID.Unlock()
	return mock.DeleteEnvironmentMappingsByEnvironmentIDFunc(environmentID)
}

// DeleteEnvironmentMappingsByEnvironmentIDCalls gets all the calls that were made to DeleteEnvironmentMappingsByEnvironmentID.
// Check the length with:
//
//	len(mockedGatewayRepository.DeleteEnvironmentMappingsByEnvironmentIDCalls())
func (mock *GatewayRepositoryMock) DeleteEnvironmentMappingsByEnvironmentIDCalls() []struct {
	EnvironmentID string
} {
	var calls []struct {
		EnvironmentID string
	}
	mock.lockDeleteEnvironmentMappingsByEnvironmentID.RLock()
	calls = mock.calls.DeleteEnvironmentMappingsByEnvironmentID
	mock.lockDeleteEnvironmentMappingsByEnvironmentID.RUnlock()
	return calls
}

// DeleteIdentityProvider calls DeleteIdentityProviderFunc.
func (mock *GatewayRepositoryMock) DeleteIdentityProvider(gatewayID string, name string) error {
	if mock.DeleteIdentityProviderFunc == nil {
		panic("GatewayRepositoryMock.DeleteIdentityProviderFunc: method is nil but GatewayRepository.DeleteIdentityProvider was just called")
	}
	callInfo := struct {
		GatewayID string
		Name      string
	}{
		GatewayID: gatewayID,
		Name:      name,
	}
	mock.lockDeleteIdentityProvider.Lock()
	mock.calls.DeleteIdentityProvider = append(mock.calls.DeleteIdentityProvider, callInfo)
	mock.lockDeleteIdentityProvider.Unlock()
	return mock.DeleteIdentityProviderFunc(gatewayID, name)
}

// DeleteIdentityProviderCalls gets all the calls that were made to DeleteIdentityProvider.
// Check the length with:
//
//	len(mockedGatewayRepository.DeleteIdentityProviderCalls())
func (mock *GatewayRepositoryMock) DeleteIdentityProviderCalls() []struct {
	GatewayID string
	Name      string
} {
	var calls []struct {
		GatewayID string
		Name      string
	}
	mock.lockDeleteIdentityProvider.RLock()
	calls = mock.calls.DeleteIdentityProvider
	mock.lockDeleteIdentityProvider.RUnlock()
	return calls
}

// EnvironmentMappingExists calls EnvironmentMappingExistsFunc.
func (mock *GatewayRepositoryMock) EnvironmentMappingExists(gatewayID string, environmentID string) (bool, error) {
	if mock.EnvironmentMappingExistsFunc == nil {
		panic("GatewayRepositoryMock.EnvironmentMappingExistsFunc: method is nil but GatewayRepository.EnvironmentMappingExists was just called")
	}
	callInfo := struct {
		GatewayID     string
		EnvironmentID string
	}{
		GatewayID:     gatewayID,
		EnvironmentID: environmentID,
	}
	mock.lockEnvironmentMappingExists.Lock()
	mock.calls.EnvironmentMappingExists = append(mock.calls.EnvironmentMappingExists, callInfo)
	mock.lockEnvironmentMappingExists.Unlock()
	return mock.EnvironmentMappingExistsFunc(gatewayID, environmentID)
}

// EnvironmentMappingExistsCalls gets all the calls that were made to EnvironmentMappingExists.
// Check the length with:
//
//	len(mockedGatewayRepository.EnvironmentMappingExistsCalls())
func (mock *GatewayRepositoryMock) EnvironmentMappingExistsCalls() []struct {
	GatewayID     string
	EnvironmentID string
} {
	var calls []struct {
		GatewayID     string
		EnvironmentID string
	}
	mock.lockEnvironmentMappingExists.RLock()
	calls = mock.calls.EnvironmentMappingExists
	mock.lockEnvironmentMappingExists.RUnlock()
	return calls
}

// GetActiveTokenByPrefix calls GetActiveTokenByPrefixFunc.
func (mock *GatewayRepositoryMock) GetActiveTokenByPrefix(tokenPrefix string) (*models.GatewayToken, error) {
	if mock.GetActiveTokenByPrefixFunc == nil {
		panic("GatewayRepositoryMock.GetActiveTokenByPrefixFunc: method is nil but GatewayRepository.GetActiveTokenByPrefix was just called")
	}
	callInfo := struct {
		TokenPrefix string
	}{
		TokenPrefix: tokenPrefix,
	}
	mock.lockGetActiveTokenByPrefix.Lock()
	mock.calls.GetActiveTokenByPrefix = append(mock.calls.GetActiveTokenByPrefix, callInfo)
	mock.lockGetActiveTokenByPrefix.Unlock()
	return mock.GetActiveTokenByPrefixFunc(tokenPrefix)
}

// GetActiveTokenByPrefixCalls gets all the calls that were made to GetActiveTokenByPrefix.
// Check the length with:
//
//	len(mockedGatewayRepository.GetActiveTokenByPrefixCalls())
func (mock *GatewayRepositoryMock) GetActiveTokenByPrefixCalls() []struct {
	TokenPrefix string
} {
	var calls []struct {
		TokenPrefix string
	}
	mock.lockGetActiveTokenByPrefix.RLock()
	calls = mock.calls.GetActiveTokenByPrefix
	mock.lockGetActiveTokenByPrefix.RUnlock()
	return calls
}

// GetActiveTokensByGatewayUUID calls GetActiveTokensByGatewayUUIDFunc.
func (mock *GatewayRepositoryMock) GetActiveTokensByGatewayUUID(gatewayId string) ([]*models.GatewayToken, error) {
	if mock.GetActiveTokensByGatewayUUIDFunc == nil {
		panic("GatewayRepositoryMock.GetActiveTokensByGatewayUUIDFunc: method is nil but GatewayRepository.GetActiveTokensByGatewayUUID was just called")
	}
	callInfo := struct {
		GatewayId string
	}{
		GatewayId: gatewayId,
	}
	mock.lockGetActiveTokensByGatewayUUID.Lock()
	mock.calls.GetActiveTokensByGatewayUUID = append(mock.calls.GetActiveTokensByGatewayUUID, callInfo)
	mock.lockGetActiveTokensByGatewayUUID.Unlock()
	return mock.GetActiveTokensByGatewayUUIDFunc(gatewayId)
}

// GetActiveTokensByGatewayUUIDCalls gets all the calls that were made to GetActiveTokensByGatewayUUID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetActiveTokensByGatewayUUIDCalls())
func (mock *GatewayRepositoryMock) GetActiveTokensByGatewayUUIDCalls() []struct {
	GatewayId string
} {
	var calls []struct {
		GatewayId string
	}
	mock.lockGetActiveTokensByGatewayUUID.RLock()
	calls = mock.calls.GetActiveTokensByGatewayUUID
	mock.lockGetActiveTokensByGatewayUUID.RUnlock()
	return calls
}

// GetByNameAndOrgID calls GetByNameAndOrgIDFunc.
func (mock *GatewayRepositoryMock) GetByNameAndOrgID(name string, orgName string) (*models.Gateway, error) {
	if mock.GetByNameAndOrgIDFunc == nil {
		panic("GatewayRepositoryMock.GetByNameAndOrgIDFunc: method is nil but GatewayRepository.GetByNameAndOrgID was just called")
	}
	callInfo := struct {
		Name    string
		OrgName string
	}{
		Name:    name,
		OrgName: orgName,
	}
	mock.lockGetByNameAndOrgID.Lock()
	mock.calls.GetByNameAndOrgID = append(mock.calls.GetByNameAndOrgID, callInfo)
	mock.lockGetByNameAndOrgID.Unlock()
	return mock.GetByNameAndOrgIDFunc(name, orgName)
}

// GetByNameAndOrgIDCalls gets all the calls that were made to GetByNameAndOrgID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetByNameAndOrgIDCalls())
func (mock *GatewayRepositoryMock) GetByNameAndOrgIDCalls() []struct {
	Name    string
	OrgName string
} {
	var calls []struct {
		Name    string
		OrgName string
	}
	mock.lockGetByNameAndOrgID.RLock()
	calls = mock.calls.GetByNameAndOrgID
	mock.lockGetByNameAndOrgID.RUnlock()
	return calls
}

// GetByOrganizationID calls GetByOrganizationIDFunc.
func (mock *GatewayRepositoryMock) GetByOrganizationID(orgName string) ([]*models.Gateway, error) {
	if mock.GetByOrganizationIDFunc == nil {
		panic("GatewayRepositoryMock.GetByOrganizationIDFunc: method is nil but GatewayRepository.GetByOrganizationID was just called")
	}
	callInfo := struct {
		OrgName string
	}{
		OrgName: orgName,
	}
	mock.lockGetByOrganizationID.Lock()
	mock.calls.GetByOrganizationID = append(mock.calls.GetByOrganizationID, callInfo)
	mock.lockGetByOrganizationID.Unlock()
	return mock.GetByOrganizationIDFunc(orgName)
}

// GetByOrganizationIDCalls gets all the calls that were made to GetByOrganizationID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetByOrganizationIDCalls())
func (mock *GatewayRepositoryMock) GetByOrganizationIDCalls() []struct {
	OrgName string
} {
	var calls []struct {
		OrgName string
	}
	mock.lockGetByOrganizationID.RLock()
	calls = mock.calls.GetByOrganizationID
	mock.lockGetByOrganizationID.RUnlock()
	return calls
}

// GetByUUID calls GetByUUIDFunc.
func (mock *GatewayRepositoryMock) GetByUUID(gatewayId string) (*models.Gateway, error) {
	if mock.GetByUUIDFunc == nil {
		panic("GatewayRepositoryMock.GetByUUIDFunc: method is nil but GatewayRepository.GetByUUID was just called")
	}
	callInfo := struct {
		GatewayId string
	}{
		GatewayId: gatewayId,
	}
	mock.lockGetByUUID.Lock()
	mock.calls.GetByUUID = append(mock.calls.GetByUUID, callInfo)
	mock.lockGetByUUID.Unlock()
	return mock.GetByUUIDFunc(gatewayId)
}

// GetByUUIDCalls gets all the calls that were made to GetByUUID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetByUUIDCalls())
func (mock *GatewayRepositoryMock) GetByUUIDCalls() []struct {
	GatewayId string
} {
	var calls []struct {
		GatewayId string
	}
	mock.lockGetByUUID.RLock()
	calls = mock.calls.GetByUUID
	mock.lockGetByUUID.RUnlock()
	return calls
}

// GetEnvironmentMappingsByEnvironmentID calls GetEnvironmentMappingsByEnvironmentIDFunc.
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByEnvironmentID(environmentID string) ([]models.GatewayEnvironmentMapping, error) {
	if mock.GetEnvironmentMappingsByEnvironmentIDFunc == nil {
		panic("GatewayRepositoryMock.GetEnvironmentMappingsByEnvironmentIDFunc: method is nil but GatewayRepository.GetEnvironmentMappingsByEnvironmentID was just called")
	}
	callInfo := struct {
		EnvironmentID string
	}{
		EnvironmentID: environmentID,
	}
	mock.lockGetEnvironmentMappingsByEnvironmentID.Lock()
	mock.calls.GetEnvironmentMappingsByEnvironmentID = append(mock.calls.GetEnvironmentMappingsByEnvironmentID, callInfo)
	mock.lockGetEnvironmentMappingsByEnvironmentID.Unlock()
	return mock.GetEnvironmentMappingsByEnvironmentIDFunc(environmentID)
}

// GetEnvironmentMappingsByEnvironmentIDCalls gets all the calls that were made to GetEnvironmentMappingsByEnvironmentID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetEnvironmentMappingsByEnvironmentIDCalls())
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByEnvironmentIDCalls() []struct {
	EnvironmentID string
} {
	var calls []struct {
		EnvironmentID string
	}
	mock.lockGetEnvironmentMappingsByEnvironmentID.RLock()
	calls = mock.calls.GetEnvironmentMappingsByEnvironmentID
	mock.lockGetEnvironmentMappingsByEnvironmentID.RUnlock()
	return calls
}

// GetEnvironmentMappingsByGatewayID calls GetEnvironmentMappingsByGatewayIDFunc.
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByGatewayID(gatewayID string) ([]models.GatewayEnvironmentMapping, error) {
	if mock.GetEnvironmentMappingsByGatewayIDFunc == nil {
		panic("GatewayRepositoryMock.GetEnvironmentMappingsByGatewayIDFunc: method is nil but GatewayRepository.GetEnvironmentMappingsByGatewayID was just called")
	}
	callInfo := struct {
		GatewayID string
	}{
		GatewayID: gatewayID,
	}
	mock.lockGetEnvironmentMappingsByGatewayID.Lock()
	mock.calls.GetEnvironmentMappingsByGatewayID = append(mock.calls.GetEnvironmentMappingsByGatewayID, callInfo)
	mock.lockGetEnvironmentMappingsByGatewayID.Unlock()
	return mock.GetEnvironmentMappingsByGatewayIDFunc(gatewayID)
}

// GetEnvironmentMappingsByGatewayIDCalls gets all the calls that were made to GetEnvironmentMappingsByGatewayID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetEnvironmentMappingsByGatewayIDCalls())
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByGatewayIDCalls() []struct {
	GatewayID string
} {
	var calls []struct {
		GatewayID string
	}
	mock.lockGetEnvironmentMappingsByGatewayID.RLock()
	calls = mock.calls.GetEnvironmentMappingsByGatewayID
	mock.lockGetEnvironmentMappingsByGatewayID.RUnlock()
	return calls
}

// GetEnvironmentMappingsByGatewayIDs calls GetEnvironmentMappingsByGatewayIDsFunc.
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByGatewayIDs(gatewayIDs []string) (map[string][]models.GatewayEnvironmentMapping, error) {
	if mock.GetEnvironmentMappingsByGatewayIDsFunc == nil {
		panic("GatewayRepositoryMock.GetEnvironmentMappingsByGatewayIDsFunc: method is nil but GatewayRepository.GetEnvironmentMappingsByGatewayIDs was just called")
	}
	callInfo := struct {
		GatewayIDs []string
	}{
		GatewayIDs: gatewayIDs,
	}
	mock.lockGetEnvironmentMappingsByGatewayIDs.Lock()
	mock.calls.GetEnvironmentMappingsByGatewayIDs = append(mock.calls.GetEnvironmentMappingsByGatewayIDs, callInfo)
	mock.lockGetEnvironmentMappingsByGatewayIDs.Unlock()
	return mock.GetEnvironmentMappingsByGatewayIDsFunc(gatewayIDs)
}

// GetEnvironmentMappingsByGatewayIDsCalls gets all the calls that were made to GetEnvironmentMappingsByGatewayIDs.
// Check the length with:
//
//	len(mockedGatewayRepository.GetEnvironmentMappingsByGatewayIDsCalls())
func (mock *GatewayRepositoryMock) GetEnvironmentMappingsByGatewayIDsCalls() []struct {
	GatewayIDs []string
} {
	var calls []struct {
		GatewayIDs []string
	}
	mock.lockGetEnvironmentMappingsByGatewayIDs.RLock()
	calls = mock.calls.GetEnvironmentMappingsByGatewayIDs
	mock.lockGetEnvironmentMappingsByGatewayIDs.RUnlock()
	return calls
}

// GetTokenByUUID calls GetTokenByUUIDFunc.
func (mock *GatewayRepositoryMock) GetTokenByUUID(tokenId string) (*models.GatewayToken, error) {
	if mock.GetTokenByUUIDFunc == nil {
		panic("GatewayRepositoryMock.GetTokenByUUIDFunc: method is nil but GatewayRepository.GetTokenByUUID was just called")
	}
	callInfo := struct {
		TokenId string
	}{
		TokenId: tokenId,
	}
	mock.lockGetTokenByUUID.Lock()
	mock.calls.GetTokenByUUID = append(mock.calls.GetTokenByUUID, callInfo)
	mock.lockGetTokenByUUID.Unlock()
	return mock.GetTokenByUUIDFunc(tokenId)
}

// GetTokenByUUIDCalls gets all the calls that were made to GetTokenByUUID.
// Check the length with:
//
//	len(mockedGatewayRepository.GetTokenByUUIDCalls())
func (mock *GatewayRepositoryMock) GetTokenByUUIDCalls() []struct {
	TokenId string
} {
	var calls []struct {
		TokenId string
	}
	mock.lockGetTokenByUUID.RLock()
	calls = mock.calls.GetTokenByUUID
	mock.lockGetTokenByUUID.RUnlock()
	return calls
}

// HasGatewayAssociations calls HasGatewayAssociationsFunc.
func (mock *GatewayRepositoryMock) HasGatewayAssociations(gatewayID string, orgName string) (bool, error) {
	if mock.HasGatewayAssociationsFunc == nil {
		panic("GatewayRepositoryMock.HasGatewayAssociationsFunc: method is nil but GatewayRepository.HasGatewayAssociations was just called")
	}
	callInfo := struct {
		GatewayID string
		OrgName   string
	}{
		GatewayID: gatewayID,
		OrgName:   orgName,
	}
	mock.lockHasGatewayAssociations.Lock()
	mock.calls.HasGatewayAssociations = append(mock.calls.HasGatewayAssociations, callInfo)
	mock.lockHasGatewayAssociations.Unlock()
	return mock.HasGatewayAssociationsFunc(gatewayID, orgName)
}

// HasGatewayAssociationsCalls gets all the calls that were made to HasGatewayAssociations.
// Check the length with:
//
//	len(mockedGatewayRepository.HasGatewayAssociationsCalls())
func (mock *GatewayRepositoryMock) HasGatewayAssociationsCalls() []struct {
	GatewayID string
	OrgName   string
} {
	var calls []struct {
		GatewayID string
		OrgName   string
	}
	mock.lockHasGatewayAssociations.RLock()
	calls = mock.calls.HasGatewayAssociations
	mock.lockHasGatewayAssociations.RUnlock()
	return calls
}

// HasGatewayAssociationsOrDeployments calls HasGatewayAssociationsOrDeploymentsFunc.
func (mock *GatewayRepositoryMock) HasGatewayAssociationsOrDeployments(gatewayID string, orgName string) (bool, error) {
	if mock.HasGatewayAssociationsOrDeploymentsFunc == nil {
		panic("GatewayRepositoryMock.HasGatewayAssociationsOrDeploymentsFunc: method is nil but GatewayRepository.HasGatewayAssociationsOrDeployments was just called")
	}
	callInfo := struct {
		GatewayID string
		OrgName   string
	}{
		GatewayID: gatewayID,
		OrgName:   orgName,
	}
	mock.lockHasGatewayAssociationsOrDeployments.Lock()
	mock.calls.HasGatewayAssociationsOrDeployments = append(mock.calls.HasGatewayAssociationsOrDeployments, callInfo)
	mock.lockHasGatewayAssociationsOrDeployments.Unlock()
	return mock.HasGatewayAssociationsOrDeploymentsFunc(gatewayID, orgName)
}

// HasGatewayAssociationsOrDeploymentsCalls gets all the calls that were made to HasGatewayAssociationsOrDeployments.
// Check the length with:
//
//	len(mockedGatewayRepository.HasGatewayAssociationsOrDeploymentsCalls())
func (mock *GatewayRepositoryMock) HasGatewayAssociationsOrDeploymentsCalls() []struct {
	GatewayID string
	OrgName   string
} {
	var calls []struct {
		GatewayID string
		OrgName   string
	}
	mock.lockHasGatewayAssociationsOrDeployments.RLock()
	calls = mock.calls.HasGatewayAssociationsOrDeployments
	mock.lockHasGatewayAssociationsOrDeployments.RUnlock()
	return calls
}

// HasGatewayDeployments calls HasGatewayDeploymentsFunc.
func (mock *GatewayRepositoryMock) HasGatewayDeployments(gatewayID string, orgName string) (bool, error) {
	if mock.HasGatewayDeploymentsFunc == nil {
		panic("GatewayRepositoryMock.HasGatewayDeploymentsFunc: method is nil but GatewayRepository.HasGatewayDeployments was just called")
	}
	callInfo := struct {
		GatewayID string
		OrgName   string
	}{
		GatewayID: gatewayID,
		OrgName:   orgName,
	}
	mock.lockHasGatewayDeployments.Lock()
	mock.calls.HasGatewayDeployments = append(mock.calls.HasGatewayDeployments, callInfo)
	mock.lockHasGatewayDeployments.Unlock()
	return mock.HasGatewayDeploymentsFunc(gatewayID, orgName)
}

// HasGatewayDeploymentsCalls gets all the calls that were made to HasGatewayDeployments.
// Check the length with:
//
//	len(mockedGatewayRepository.HasGatewayDeploymentsCalls())
func (mock *GatewayRepositoryMock) HasGatewayDeploymentsCalls() []struct {
	GatewayID string
	OrgName   string
} {
	var calls []struct {
		GatewayID string
		OrgName   string
	}
	mock.lockHasGatewayDeployments.RLock()
	calls = mock.calls.HasGatewayDeployments
	mock.lockHasGatewayDeployments.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *GatewayRepositoryMock) List() ([]*models.Gateway, error) {
	if mock.ListFunc == nil {
		panic("GatewayRepositoryMock.ListFunc: method is nil but GatewayRepository.List was just called")
	}
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedGatewayRepository.ListCalls())
func (mock *GatewayRepositoryMock) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListIdentityProvidersByEnvironment calls ListIdentityProvidersByEnvironmentFunc.
func (mock *GatewayRepositoryMock) ListIdentityProvidersByEnvironment(environmentID string) ([]models.GatewayIdentityProvider, error) {
	if mock.ListIdentityProvidersByEnvironmentFunc == nil {
		panic("GatewayRepositoryMock.ListIdentityProvidersByEnvironmentFunc: method is nil but GatewayRepository.ListIdentityProvidersByEnvironment was just called")
	}
	callInfo := struct {
		EnvironmentID string
	}{
		EnvironmentID: environmentID,
	}
	mock.lockListIdentityProvidersByEnvironment.Lock()
	mock.calls.ListIdentityProvidersByEnvironment = append(mock.calls.ListIdentityProvidersByEnvironment, callInfo)
	mock.lockListIdentityProvidersByEnvironment.Unlock()
	return mock.ListIdentityProvidersByEnvironmentFunc(environmentID)
}

// ListIdentityProvidersByEnvironmentCalls gets all the calls that were made to ListIdentityProvidersByEnvironment.
// Check the length with:
//
//	len(mockedGatewayRepository.ListIdentityProvidersByEnvironmentCalls())
func (mock *GatewayRepositoryMock) ListIdentityProvidersByEnvironmentCalls() []struct {
	EnvironmentID string
} {
	var calls []struct {
		EnvironmentID string
	}
	mock.lockListIdentityProvidersByEnvironment.RLock()
	calls = mock.calls.ListIdentityProvidersByEnvironment
	mock.lockListIdentityProvidersByEnvironment.RUnlock()
	return calls
}

// ListIdentityProvidersByGateway calls ListIdentityProvidersByGatewayFunc.
func (mock *GatewayRepositoryMock) ListIdentityProvidersByGateway(gatewayID string) ([]models.GatewayIdentityProvider, error) {
	if mock.ListIdentityProvidersByGatewayFunc == nil {
		panic("GatewayRepositoryMock.ListIdentityProvidersByGatewayFunc: method is nil but GatewayRepository.ListIdentityProvidersByGateway was just called")
	}
	callInfo := struct {
		GatewayID string
	}{
		GatewayID: gatewayID,
	}
	mock.lockListIdentityProvidersByGateway.Lock()
	mock.calls.ListIdentityProvidersByGateway = append(mock.calls.ListIdentityProvidersByGateway, callInfo)
	mock.lockListIdentityProvidersByGateway.Unlock()
	return mock.ListIdentityProvidersByGatewayFunc(gatewayID)
}

// ListIdentityProvidersByGatewayCalls gets all the calls that were made to ListIdentityProvidersByGateway.
// Check the length with:
//
//	len(mockedGatewayRepository.ListIdentityProvidersByGatewayCalls())
func (mock *GatewayRepositoryMock) ListIdentityProvidersByGatewayCalls() []struct {
	GatewayID string
} {
	var calls []struct {
		GatewayID string
	}
	mock.lockListIdentityProvidersByGateway.RLock()
	calls = mock.calls.ListIdentityProvidersByGateway
	mock.lockListIdentityProvidersByGateway.RUnlock()
	return calls
}

// ListIdentityProvidersByOrg calls ListIdentityProvidersByOrgFunc.
func (mock *GatewayRepositoryMock) ListIdentityProvidersByOrg(orgName string) ([]repositories.IdentityProviderWithContext, error) {
	if mock.ListIdentityProvidersByOrgFunc == nil {
		panic("GatewayRepositoryMock.ListIdentityProvidersByOrgFunc: method is nil but GatewayRepository.ListIdentityProvidersByOrg was just called")
	}
	callInfo := struct {
		OrgName string
	}{
		OrgName: orgName,
	}
	mock.lockListIdentityProvidersByOrg.Lock()
	mock.calls.ListIdentityProvidersByOrg = append(mock.calls.ListIdentityProvidersByOrg, callInfo)
	mock.lockListIdentityProvidersByOrg.Unlock()
	return mock.ListIdentityProvidersByOrgFunc(orgName)
}

// ListIdentityProvidersByOrgCalls gets all the calls that were made to ListIdentityProvidersByOrg.
// Check the length with:
//
//	len(mockedGatewayRepository.ListIdentityProvidersByOrgCalls())
func (mock *GatewayRepositoryMock) ListIdentityProvidersByOrgCalls() []struct {
	OrgName string
} {
	var calls []struct {
		OrgName string
	}
	mock.lockListIdentityProvidersByOrg.RLock()
	calls = mock.calls.ListIdentityProvidersByOrg
	mock.lockListIdentityProvidersByOrg.RUnlock()
	return calls
}

// ListWithFilters calls ListWithFiltersFunc.
func (mock *GatewayRepositoryMock) ListWithFilters(filters repositories.GatewayFilterOptions) ([]*models.Gateway, error) {
	if mock.ListWithFiltersFunc == nil {
		panic("GatewayRepositoryMock.ListWithFiltersFunc: method is nil but GatewayRepository.ListWithFilters was just called")
	}
	callInfo := struct {
		Filters repositories.GatewayFilterOptions
	}{
		Filters: filters,
	}
	mock.lockListWithFilters.Lock()
	mock.calls.ListWithFilters = append(mock.calls.ListWithFilters, callInfo)
	mock.lockListWithFilters.Unlock()
	return mock.ListWithFiltersFunc(filters)
}

// ListWithFiltersCalls gets all the calls that were made to ListWithFilters.
// Check the length with:
//
//	len(mockedGatewayRepository.ListWithFiltersCalls())
func (mock *GatewayRepositoryMock) ListWithFiltersCalls() []struct {
	Filters repositories.GatewayFilterOptions
} {
	var calls []struct {
		Filters repositories.GatewayFilterOptions
	}
	mock.lockListWithFilters.RLock()
	calls = mock.calls.ListWithFilters
	mock.lockListWithFilters.RUnlock()
	return calls
}

// RevokeToken calls RevokeTokenFunc.
func (mock *GatewayRepositoryMock) RevokeToken(tokenId string) error {
	if mock.RevokeTokenFunc == nil {
		panic("GatewayRepositoryMock.RevokeTokenFunc: method is nil but GatewayRepository.RevokeToken was just called")
	}
	callInfo := struct {
		TokenId string
	}{
		TokenId: tokenId,
	}
	mock.lockRevokeToken.Lock()
	mock.calls.RevokeToken = append(mock.calls.RevokeToken, callInfo)
	mock.lockRevokeToken.Unlock()
	return mock.RevokeTokenFunc(tokenId)
}

// RevokeTokenCalls gets all the calls that were made to RevokeToken.
// Check the length with:
//
//	len(mockedGatewayRepository.RevokeTokenCalls())
func (mock *GatewayRepositoryMock) RevokeTokenCalls() []struct {
	TokenId string
} {
	var calls []struct {
		TokenId string
	}
	mock.lockRevokeToken.RLock()
	calls = mock.calls.RevokeToken
	mock.lockRevokeToken.RUnlock()
	return calls
}

// UpdateActiveStatus calls UpdateActiveStatusFunc.
func (mock *GatewayRepositoryMock) UpdateActiveStatus(gatewayId string, isActive bool) error {
	if mock.UpdateActiveStatusFunc == nil {
		panic("GatewayRepositoryMock.UpdateActiveStatusFunc: method is nil but GatewayRepository.UpdateActiveStatus was just called")
	}
	callInfo := struct {
		GatewayId string
		IsActive  bool
	}{
		GatewayId: gatewayId,
		IsActive:  isActive,
	}
	mock.lockUpdateActiveStatus.Lock()
	mock.calls.UpdateActiveStatus = append(mock.calls.UpdateActiveStatus, callInfo)
	mock.lockUpdateActiveStatus.Unlock()
	return mock.UpdateActiveStatusFunc(gatewayId, isActive)
}

// UpdateActiveStatusCalls gets all the calls that were made to UpdateActiveStatus.
// Check the length with:
//
//	len(mockedGatewayRepository.UpdateActiveStatusCalls())
func (mock *GatewayRepositoryMock) UpdateActiveStatusCalls() []struct {
	GatewayId string
	IsActive  bool
} {
	var calls []struct {
		GatewayId string
		IsActive  bool
	}
	mock.lockUpdateActiveStatus.RLock()
	calls = mock.calls.UpdateActiveStatus
	mock.lockUpdateActiveStatus.RUnlock()
	return calls
}

// UpdateGateway calls UpdateGatewayFunc.
func (mock *GatewayRepositoryMock) UpdateGateway(gateway *models.Gateway) error {
	if mock.UpdateGatewayFunc == nil {
		panic("GatewayRepositoryMock.UpdateGatewayFunc: method is nil but GatewayRepository.UpdateGateway was just called")
	}
	callInfo := struct {
		Gateway *models.Gateway
	}{
		Gateway: gateway,
	}
	mock.lockUpdateGateway.Lock()
	mock.calls.UpdateGateway = append(mock.calls.UpdateGateway, callInfo)
	mock.lockUpdateGateway.Unlock()
	return mock.UpdateGatewayFunc(gateway)
}

// UpdateGatewayCalls gets all the calls that were made to UpdateGateway.
// Check the length with:
//
//	len(mockedGatewayRepository.UpdateGatewayCalls())
func (mock *GatewayRepositoryMock) UpdateGatewayCalls() []struct {
	Gateway *models.Gateway
} {
	var calls []struct {
		Gateway *models.Gateway
	}
	mock.lockUpdateGateway.RLock()
	calls = mock.calls.UpdateGateway
	mock.lockUpdateGateway.RUnlock()
	return calls
}

// UpsertIdentityProvider calls UpsertIdentityProviderFunc.
func (mock *GatewayRepositoryMock) UpsertIdentityProvider(provider *models.GatewayIdentityProvider) error {
	if mock.UpsertIdentityProviderFunc == nil {
		panic("GatewayRepositoryMock.UpsertIdentityProviderFunc: method is nil but GatewayRepository.UpsertIdentityProvider was just called")
	}
	callInfo := struct {
		Provider *models.GatewayIdentityProvider
	}{
		Provider: provider,
	}
	mock.lockUpsertIdentityProvider.Lock()
	mock.calls.UpsertIdentityProvider = append(mock.calls.UpsertIdentityProvider, callInfo)
	mock.lockUpsertIdentityProvider.Unlock()
	return mock.UpsertIdentityProviderFunc(provider)
}

// UpsertIdentityProviderCalls gets all the calls that were made to UpsertIdentityProvider.
// Check the length with:
//
//	len(mockedGatewayRepository.UpsertIdentityProviderCalls())
func (mock *GatewayRepositoryMock) UpsertIdentityProviderCalls() []struct {
	Provider *models.GatewayIdentityProvider
} {
	var calls []struct {
		Provider *models.GatewayIdentityProvider
	}
	mock.lockUpsertIdentityProvider.RLock()
	calls = mock.calls.UpsertIdentityProvider
	mock.lockUpsertIdentityProvider.RUnlock()
	return calls
}
