// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// LLMProviderTemplateRepositoryMock is a mock implementation of repositories.LLMProviderTemplateRepository.
//
//	func TestSomethingThatUsesLLMProviderTemplateRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.LLMProviderTemplateRepository
//		mockedLLMProviderTemplateRepository := &LLMProviderTemplateRepositoryMock{
//			CountFunc: func(orgUUID string) (int, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(t *models.LLMProviderTemplate) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(templateID string, orgUUID string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(templateID string, orgUUID string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetByHandleFunc: func(templateHandle string, orgUUID string) (*models.LLMProviderTemplate, error) {
//				panic("mock out the GetByHandle method")
//			},
//			GetByUUIDFunc: func(uuid string, orgUUID string) (*models.LLMProviderTemplate, error) {
//				panic("mock out the GetByUUID method")
//			},
//			ListFunc: func(orgUUID string, limit int, offset int) ([]*models.LLMProviderTemplate, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(t *models.LLMProviderTemplate) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedLLMProviderTemplateRepository in code that requires repositories.LLMProviderTemplateRepository
//		// and then make assertions.
//
//	}
type LLMProviderTemplateRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(orgUUID string) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(t *models.LLMProviderTemplate) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(templateID string, orgUUID string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(templateID string, orgUUID string) (bool, error)

	// GetByHandleFunc mocks the GetByHandle method.
	GetByHandleFunc func(templateHandle string, orgUUID string) (*models.LLMProviderTemplate, error)

	// GetByUUIDFunc mocks the GetByUUID method.
	GetByUUIDFunc func(uuid string, orgUUID string) (*models.LLMProviderTemplate, error)

	// ListFunc mocks the List method.
	ListFunc func(orgUUID string, limit int, offset int) ([]*models.LLMProviderTemplate, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(t *models.LLMProviderTemplate) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// T is the t argument value.
			T *models.LLMProviderTemplate
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// TemplateID is the templateID argument value.
			TemplateID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// TemplateID is the templateID argument value.
			TemplateID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByHandle holds details about calls to the GetByHandle method.
		GetByHandle []struct {
			// TemplateHandle is the templateHandle argument value.
			TemplateHandle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByUUID holds details about calls to the GetByUUID method.
		GetByUUID []struct {
			// UUID is the uuid argument value.
			UUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// T is the t argument value.
			T *models.LLMProviderTemplate
		}
	}
	lockCount       sync.RWMutex
	lockCreate      sync.RWMutex
	lockDelete      sync.RWMutex
	lockExists      sync.RWMutex
	lockGetByHandle sync.RWMutex
	lockGetByUUID   sync.RWMutex
	lockList        sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Count calls CountFunc.
func (mock *LLMProviderTemplateRepositoryMock) Count(orgUUID string) (int, error) {
	if mock.CountFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.CountFunc: method is nil but LLMProviderTemplateRepository.Count was just called")
	}
	callInfo := struct {
		OrgUUID string
	}{
		OrgUUID: orgUUID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(orgUUID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.CountCalls())
func (mock *LLMProviderTemplateRepositoryMock) CountCalls() []struct {
	OrgUUID string
} {
	var calls []struct {
		OrgUUID string
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *LLMProviderTemplateRepositoryMock) Create(t *models.LLMProviderTemplate) error {
	if mock.CreateFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.CreateFunc: method is nil but LLMProviderTemplateRepository.Create was just called")
	}
	callInfo := struct {
		T *models.LLMProviderTemplate
	}{
		T: t,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(t)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.CreateCalls())
func (mock *LLMProviderTemplateRepositoryMock) CreateCalls() []struct {
	T *models.LLMProviderTemplate
} {
	var calls []struct {
		T *models.LLMProviderTemplate
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *LLMProviderTemplateRepositoryMock) Delete(templateID string, orgUUID string) error {
	if mock.DeleteFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.DeleteFunc: method is nil but LLMProviderTemplateRepository.Delete was just called")
	}
	callInfo := struct {
		TemplateID string
		OrgUUID    string
	}{
		TemplateID: templateID,
		OrgUUID:    orgUUID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(templateID, orgUUID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.DeleteCalls())
func (mock *LLMProviderTemplateRepositoryMock) DeleteCalls() []struct {
	TemplateID string
	OrgUUID    string
} {
	var calls []struct {
		TemplateID string
		OrgUUID    string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *LLMProviderTemplateRepositoryMock) Exists(templateID string, orgUUID string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.ExistsFunc: method is nil but LLMProviderTemplateRepository.Exists was just called")
	}
	callInfo := struct {
		TemplateID string
		OrgUUID    string
	}{
		TemplateID: templateID,
		OrgUUID:    orgUUID,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(templateID, orgUUID)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.ExistsCalls())
func (mock *LLMProviderTemplateRepositoryMock) ExistsCalls() []struct {
	TemplateID string
	OrgUUID    string
} {
	var calls []struct {
		TemplateID string
		OrgUUID    string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetByHandle calls GetByHandleFunc.
func (mock *LLMProviderTemplateRepositoryMock) GetByHandle(templateHandle string, orgUUID string) (*models.LLMProviderTemplate, error) {
	if mock.GetByHandleFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.GetByHandleFunc: method is nil but LLMProviderTemplateRepository.GetByHandle was just called")
	}
	callInfo := struct {
		TemplateHandle string
		OrgUUID        string
	}{
		TemplateHandle: templateHandle,
		OrgUUID:        orgUUID,
	}
	mock.lockGetByHandle.Lock()
	mock.calls.GetByHandle = append(mock.calls.GetByHandle, callInfo)
	mock.lockGetByHandle.Unlock()
	return mock.GetByHandleFunc(templateHandle, orgUUID)
}

// GetByHandleCalls gets all the calls that were made to GetByHandle.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.GetByHandleCalls())
func (mock *LLMProviderTemplateRepositoryMock) GetByHandleCalls() []struct {
	TemplateHandle string
	OrgUUID        string
} {
	var calls []struct {
		TemplateHandle string
		OrgUUID        string
	}
	mock.lockGetByHandle.RLock()
	calls = mock.calls.GetByHandle
	mock.lockGetByHandle.RUnlock()
	return calls
}

// GetByUUID calls GetByUUIDFunc.
func (mock *LLMProviderTemplateRepositoryMock) GetByUUID(uuid string, orgUUID string) (*models.LLMProviderTemplate, error) {
	if mock.GetByUUIDFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.GetByUUIDFunc: method is nil but LLMProviderTemplateRepository.GetByUUID was just called")
	}
	callInfo := struct {
		UUID    string
		OrgUUID string
	}{
		UUID:    uuid,
		OrgUUID: orgUUID,
	}
	mock.lockGetByUUID.Lock()
	mock.calls.GetByUUID = append(mock.calls.GetByUUID, callInfo)
	mock.lockGetByUUID.Unlock()
	return mock.GetByUUIDFunc(uuid, orgUUID)
}

// GetByUUIDCalls gets all the calls that were made to GetByUUID.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.GetByUUIDCalls())
func (mock *LLMProviderTemplateRepositoryMock) GetByUUIDCalls() []struct {
	UUID    string
	OrgUUID string
} {
	var calls []struct {
		UUID    string
		OrgUUID string
	}
	mock.lockGetByUUID.RLock()
	calls = mock.calls.GetByUUID
	mock.lockGetByUUID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *LLMProviderTemplateRepositoryMock) List(orgUUID string, limit int, offset int) ([]*models.LLMProviderTemplate, error) {
	if mock.ListFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.ListFunc: method is nil but LLMProviderTemplateRepository.List was just called")
	}
	callInfo := struct {
		OrgUUID string
		Limit   int
		Offset  int
	}{
		OrgUUID: orgUUID,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(orgUUID, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.ListCalls())
func (mock *LLMProviderTemplateRepositoryMock) ListCalls() []struct {
	OrgUUID string
	Limit   int
	Offset  int
} {
	var calls []struct {
		OrgUUID string
		Limit   int
		Offset  int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *LLMProviderTemplateRepositoryMock) Update(t *models.LLMProviderTemplate) error {
	if mock.UpdateFunc == nil {
		panic("LLMProviderTemplateRepositoryMock.UpdateFunc: method is nil but LLMProviderTemplateRepository.Update was just called")
	}
	callInfo := struct {
		T *models.LLMProviderTemplate
	}{
		T: t,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(t)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedLLMProviderTemplateRepository.UpdateCalls())
func (mock *LLMProviderTemplateRepositoryMock) UpdateCalls() []struct {
	T *models.LLMProviderTemplate
} {
	var calls []struct {
		T *models.LLMProviderTemplate
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
