// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// MCPProxyRepositoryMock is a mock implementation of repositories.MCPProxyRepository.
//
//	func TestSomethingThatUsesMCPProxyRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.MCPProxyRepository
//		mockedMCPProxyRepository := &MCPProxyRepositoryMock{
//			CountFunc: func(ctx context.Context, orgUUID string) (int, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, handle string, name string, version string, orgUUID string) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, handle string, orgUUID string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsFunc: func(ctx context.Context, handle string, orgUUID string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetByHandleFunc: func(ctx context.Context, handle string, orgUUID string) (*models.MCPProxy, error) {
//				panic("mock out the GetByHandle method")
//			},
//			GetByHandleForUpdateFunc: func(ctx context.Context, tx *gorm.DB, handle string, orgUUID string) (*models.MCPProxy, error) {
//				panic("mock out the GetByHandleForUpdate method")
//			},
//			GetByUUIDFunc: func(ctx context.Context, proxyUUID string, orgUUID string) (*models.MCPProxy, error) {
//				panic("mock out the GetByUUID method")
//			},
//			ListFunc: func(ctx context.Context, orgUUID string, limit int, offset int) ([]*models.MCPProxy, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, orgUUID string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedMCPProxyRepository in code that requires repositories.MCPProxyRepository
//		// and then make assertions.
//
//	}
type MCPProxyRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, orgUUID string) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, handle string, name string, version string, orgUUID string) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, handle string, orgUUID string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, handle string, orgUUID string) (bool, error)

	// GetByHandleFunc mocks the GetByHandle method.
	GetByHandleFunc func(ctx context.Context, handle string, orgUUID string) (*models.MCPProxy, error)

	// GetByHandleForUpdateFunc mocks the GetByHandleForUpdate method.
	GetByHandleForUpdateFunc func(ctx context.Context, tx *gorm.DB, handle string, orgUUID string) (*models.MCPProxy, error)

	// GetByUUIDFunc mocks the GetByUUID method.
	GetByUUIDFunc func(ctx context.Context, proxyUUID string, orgUUID string) (*models.MCPProxy, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, orgUUID string, limit int, offset int) ([]*models.MCPProxy, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, orgUUID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// P is the p argument value.
			P *models.MCPProxy
			// Handle is the handle argument value.
			Handle string
			// Name is the name argument value.
			Name string
			// Version is the version argument value.
			Version string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByHandle holds details about calls to the GetByHandle method.
		GetByHandle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByHandleForUpdate holds details about calls to the GetByHandleForUpdate method.
		GetByHandleForUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Handle is the handle argument value.
			Handle string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetByUUID holds details about calls to the GetByUUID method.
		GetByUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProxyUUID is the proxyUUID argument value.
			ProxyUUID string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// P is the p argument value.
			P *models.MCPProxy
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
	}
	lockCount                sync.RWMutex
	lockCreate               sync.RWMutex
	lockDelete               sync.RWMutex
	lockExists               sync.RWMutex
	lockGetByHandle          sync.RWMutex
	lockGetByHandleForUpdate sync.RWMutex
	lockGetByUUID            sync.RWMutex
	lockList                 sync.RWMutex
	lockUpdate               sync.RWMutex
}

// Count calls CountFunc.
func (mock *MCPProxyRepositoryMock) Count(ctx context.Context, orgUUID string) (int, error) {
	if mock.CountFunc == nil {
		panic("MCPProxyRepositoryMock.CountFunc: method is nil but MCPProxyRepository.Count was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgUUID string
	}{
		Ctx:     ctx,
		OrgUUID: orgUUID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, orgUUID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedMCPProxyRepository.CountCalls())
func (mock *MCPProxyRepositoryMock) CountCalls() []struct {
	Ctx     context.Context
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		OrgUUID string
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *MCPProxyRepositoryMock) Create(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, handle string, name string, version string, orgUUID string) error {
	if mock.CreateFunc == nil {
		panic("MCPProxyRepositoryMock.CreateFunc: method is nil but MCPProxyRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		P       *models.MCPProxy
		Handle  string
		Name    string
		Version string
		OrgUUID string
	}{
		Ctx:     ctx,
		Tx:      tx,
		P:       p,
		Handle:  handle,
		Name:    name,
		Version: version,
		OrgUUID: orgUUID,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, p, handle, name, version, orgUUID)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedMCPProxyRepository.CreateCalls())
func (mock *MCPProxyRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	P       *models.MCPProxy
	Handle  string
	Name    string
	Version string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		P       *models.MCPProxy
		Handle  string
		Name    string
		Version string
		OrgUUID string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *MCPProxyRepositoryMock) Delete(ctx context.Context, handle string, orgUUID string) error {
	if mock.DeleteFunc == nil {
		panic("MCPProxyRepositoryMock.DeleteFunc: method is nil but MCPProxyRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}{
		Ctx:     ctx,
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, handle, orgUUID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedMCPProxyRepository.DeleteCalls())
func (mock *MCPProxyRepositoryMock) DeleteCalls() []struct {
	Ctx     context.Context
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *MCPProxyRepositoryMock) Exists(ctx context.Context, handle string, orgUUID string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("MCPProxyRepositoryMock.ExistsFunc: method is nil but MCPProxyRepository.Exists was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}{
		Ctx:     ctx,
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, handle, orgUUID)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedMCPProxyRepository.ExistsCalls())
func (mock *MCPProxyRepositoryMock) ExistsCalls() []struct {
	Ctx     context.Context
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetByHandle calls GetByHandleFunc.
func (mock *MCPProxyRepositoryMock) GetByHandle(ctx context.Context, handle string, orgUUID string) (*models.MCPProxy, error) {
	if mock.GetByHandleFunc == nil {
		panic("MCPProxyRepositoryMock.GetByHandleFunc: method is nil but MCPProxyRepository.GetByHandle was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}{
		Ctx:     ctx,
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockGetByHandle.Lock()
	mock.calls.GetByHandle = append(mock.calls.GetByHandle, callInfo)
	mock.lockGetByHandle.Unlock()
	return mock.GetByHandleFunc(ctx, handle, orgUUID)
}

// GetByHandleCalls gets all the calls that were made to GetByHandle.
// Check the length with:
//
//	len(mockedMCPProxyRepository.GetByHandleCalls())
func (mock *MCPProxyRepositoryMock) GetByHandleCalls() []struct {
	Ctx     context.Context
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Handle  string
		OrgUUID string
	}
	mock.lockGetByHandle.RLock()
	calls = mock.calls.GetByHandle
	mock.lockGetByHandle.RUnlock()
	return calls
}

// GetByHandleForUpdate calls GetByHandleForUpdateFunc.
func (mock *MCPProxyRepositoryMock) GetByHandleForUpdate(ctx context.Context, tx *gorm.DB, handle string, orgUUID string) (*models.MCPProxy, error) {
	if mock.GetByHandleForUpdateFunc == nil {
		panic("MCPProxyRepositoryMock.GetByHandleForUpdateFunc: method is nil but MCPProxyRepository.GetByHandleForUpdate was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Handle  string
		OrgUUID string
	}{
		Ctx:     ctx,
		Tx:      tx,
		Handle:  handle,
		OrgUUID: orgUUID,
	}
	mock.lockGetByHandleForUpdate.Lock()
	mock.calls.GetByHandleForUpdate = append(mock.calls.GetByHandleForUpdate, callInfo)
	mock.lockGetByHandleForUpdate.Unlock()
	return mock.GetByHandleForUpdateFunc(ctx, tx, handle, orgUUID)
}

// GetByHandleForUpdateCalls gets all the calls that were made to GetByHandleForUpdate.
// Check the length with:
//
//	len(mockedMCPProxyRepository.GetByHandleForUpdateCalls())
func (mock *MCPProxyRepositoryMock) GetByHandleForUpdateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Handle  string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Handle  string
		OrgUUID string
	}
	mock.lockGetByHandleForUpdate.RLock()
	calls = mock.calls.GetByHandleForUpdate
	mock.lockGetByHandleForUpdate.RUnlock()
	return calls
}

// GetByUUID calls GetByUUIDFunc.
func (mock *MCPProxyRepositoryMock) GetByUUID(ctx context.Context, proxyUUID string, orgUUID string) (*models.MCPProxy, error) {
	if mock.GetByUUIDFunc == nil {
		panic("MCPProxyRepositoryMock.GetByUUIDFunc: method is nil but MCPProxyRepository.GetByUUID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ProxyUUID string
		OrgUUID   string
	}{
		Ctx:       ctx,
		ProxyUUID: proxyUUID,
		OrgUUID:   orgUUID,
	}
	mock.lockGetByUUID.Lock()
	mock.calls.GetByUUID = append(mock.calls.GetByUUID, callInfo)
	mock.lockGetByUUID.Unlock()
	return mock.GetByUUIDFunc(ctx, proxyUUID, orgUUID)
}

// GetByUUIDCalls gets all the calls that were made to GetByUUID.
// Check the length with:
//
//	len(mockedMCPProxyRepository.GetByUUIDCalls())
func (mock *MCPProxyRepositoryMock) GetByUUIDCalls() []struct {
	Ctx       context.Context
	ProxyUUID string
	OrgUUID   string
} {
	var calls []struct {
		Ctx       context.Context
		ProxyUUID string
		OrgUUID   string
	}
	mock.lockGetByUUID.RLock()
	calls = mock.calls.GetByUUID
	mock.lockGetByUUID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *MCPProxyRepositoryMock) List(ctx context.Context, orgUUID string, limit int, offset int) ([]*models.MCPProxy, error) {
	if mock.ListFunc == nil {
		panic("MCPProxyRepositoryMock.ListFunc: method is nil but MCPProxyRepository.List was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgUUID string
		Limit   int
		Offset  int
	}{
		Ctx:     ctx,
		OrgUUID: orgUUID,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, orgUUID, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedMCPProxyRepository.ListCalls())
func (mock *MCPProxyRepositoryMock) ListCalls() []struct {
	Ctx     context.Context
	OrgUUID string
	Limit   int
	Offset  int
} {
	var calls []struct {
		Ctx     context.Context
		OrgUUID string
		Limit   int
		Offset  int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *MCPProxyRepositoryMock) Update(ctx context.Context, tx *gorm.DB, p *models.MCPProxy, orgUUID string) error {
	if mock.UpdateFunc == nil {
		panic("MCPProxyRepositoryMock.UpdateFunc: method is nil but MCPProxyRepository.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		P       *models.MCPProxy
		OrgUUID string
	}{
		Ctx:     ctx,
		Tx:      tx,
		P:       p,
		OrgUUID: orgUUID,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, tx, p, orgUUID)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedMCPProxyRepository.UpdateCalls())
func (mock *MCPProxyRepositoryMock) UpdateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	P       *models.MCPProxy
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		P       *models.MCPProxy
		OrgUUID string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
