// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"github.com/wso2/agent-manager/agent-manager-service/repositories"
	"gorm.io/gorm"
)

// MonitorRepositoryMock is a mock implementation of repositories.MonitorRepository.
//
//	func TestSomethingThatUsesMonitorRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.MonitorRepository
//		mockedMonitorRepository := &MonitorRepositoryMock{
//			CountMonitorRunsFunc: func(monitorID uuid.UUID) (int64, error) {
//				panic("mock out the CountMonitorRuns method")
//			},
//			CreateMonitorFunc: func(monitor *models.Monitor) error {
//				panic("mock out the CreateMonitor method")
//			},
//			CreateMonitorRunFunc: func(run *models.MonitorRun) error {
//				panic("mock out the CreateMonitorRun method")
//			},
//			DeleteMonitorFunc: func(monitor *models.Monitor) error {
//				panic("mock out the DeleteMonitor method")
//			},
//			FindActiveMonitorsByEvaluatorIdentifierFunc: func(orgName string, identifier string) ([]models.Monitor, error) {
//				panic("mock out the FindActiveMonitorsByEvaluatorIdentifier method")
//			},
//			GetLatestMonitorRunFunc: func(monitorID uuid.UUID) (*models.MonitorRun, error) {
//				panic("mock out the GetLatestMonitorRun method")
//			},
//			GetLatestMonitorRunsFunc: func(monitorIDs []uuid.UUID) (map[uuid.UUID]models.MonitorRun, error) {
//				panic("mock out the GetLatestMonitorRuns method")
//			},
//			GetMonitorByIDFunc: func(monitorID uuid.UUID) (*models.Monitor, error) {
//				panic("mock out the GetMonitorByID method")
//			},
//			GetMonitorByNameFunc: func(orgName string, projectName string, agentName string, monitorName string) (*models.Monitor, error) {
//				panic("mock out the GetMonitorByName method")
//			},
//			GetMonitorRunByIDFunc: func(runID uuid.UUID, monitorID uuid.UUID) (*models.MonitorRun, error) {
//				panic("mock out the GetMonitorRunByID method")
//			},
//			GetMonitorRunsByMonitorIDFunc: func(monitorID uuid.UUID) ([]models.MonitorRun, error) {
//				panic("mock out the GetMonitorRunsByMonitorID method")
//			},
//			ListDueMonitorsFunc: func(monitorType string, dueBy time.Time) ([]models.Monitor, error) {
//				panic("mock out the ListDueMonitors method")
//			},
//			ListMonitorRunsFunc: func(monitorID uuid.UUID, limit int, offset int) ([]models.MonitorRun, error) {
//				panic("mock out the ListMonitorRuns method")
//			},
//			ListMonitorsByAgentFunc: func(orgName string, projectName string, agentName string) ([]models.Monitor, error) {
//				panic("mock out the ListMonitorsByAgent method")
//			},
//			ListMonitorsByAgentEnvironmentFunc: func(orgName string, projectName string, agentName string, environmentName string) ([]models.Monitor, error) {
//				panic("mock out the ListMonitorsByAgentEnvironment method")
//			},
//			ListPendingOrRunningRunsFunc: func(limit int) ([]models.MonitorRun, error) {
//				panic("mock out the ListPendingOrRunningRuns method")
//			},
//			RunInTransactionFunc: func(fn func(txRepo repositories.MonitorRepository) error) error {
//				panic("mock out the RunInTransaction method")
//			},
//			UpdateMonitorFunc: func(monitor *models.Monitor) error {
//				panic("mock out the UpdateMonitor method")
//			},
//			UpdateMonitorRunFunc: func(run *models.MonitorRun, updates map[string]interface{}) error {
//				panic("mock out the UpdateMonitorRun method")
//			},
//			UpdateNextRunTimeFunc: func(monitorID uuid.UUID, nextRunTime *time.Time) error {
//				panic("mock out the UpdateNextRunTime method")
//			},
//			WithTxFunc: func(tx *gorm.DB) repositories.MonitorRepository {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedMonitorRepository in code that requires repositories.MonitorRepository
//		// and then make assertions.
//
//	}
type MonitorRepositoryMock struct {
	// CountMonitorRunsFunc mocks the CountMonitorRuns method.
	CountMonitorRunsFunc func(monitorID uuid.UUID) (int64, error)

	// CreateMonitorFunc mocks the CreateMonitor method.
	CreateMonitorFunc func(monitor *models.Monitor) error

	// CreateMonitorRunFunc mocks the CreateMonitorRun method.
	CreateMonitorRunFunc func(run *models.MonitorRun) error

	// DeleteMonitorFunc mocks the DeleteMonitor method.
	DeleteMonitorFunc func(monitor *models.Monitor) error

	// FindActiveMonitorsByEvaluatorIdentifierFunc mocks the FindActiveMonitorsByEvaluatorIdentifier method.
	FindActiveMonitorsByEvaluatorIdentifierFunc func(orgName string, identifier string) ([]models.Monitor, error)

	// GetLatestMonitorRunFunc mocks the GetLatestMonitorRun method.
	GetLatestMonitorRunFunc func(monitorID uuid.UUID) (*models.MonitorRun, error)

	// GetLatestMonitorRunsFunc mocks the GetLatestMonitorRuns method.
	GetLatestMonitorRunsFunc func(monitorIDs []uuid.UUID) (map[uuid.UUID]models.MonitorRun, error)

	// GetMonitorByIDFunc mocks the GetMonitorByID method.
	GetMonitorByIDFunc func(monitorID uuid.UUID) (*models.Monitor, error)

	// GetMonitorByNameFunc mocks the GetMonitorByName method.
	GetMonitorByNameFunc func(orgName string, projectName string, agentName string, monitorName string) (*models.Monitor, error)

	// GetMonitorRunByIDFunc mocks the GetMonitorRunByID method.
	GetMonitorRunByIDFunc func(runID uuid.UUID, monitorID uuid.UUID) (*models.MonitorRun, error)

	// GetMonitorRunsByMonitorIDFunc mocks the GetMonitorRunsByMonitorID method.
	GetMonitorRunsByMonitorIDFunc func(monitorID uuid.UUID) ([]models.MonitorRun, error)

	// ListDueMonitorsFunc mocks the ListDueMonitors method.
	ListDueMonitorsFunc func(monitorType string, dueBy time.Time) ([]models.Monitor, error)

	// ListMonitorRunsFunc mocks the ListMonitorRuns method.
	ListMonitorRunsFunc func(monitorID uuid.UUID, limit int, offset int) ([]models.MonitorRun, error)

	// ListMonitorsByAgentFunc mocks the ListMonitorsByAgent method.
	ListMonitorsByAgentFunc func(orgName string, projectName string, agentName string) ([]models.Monitor, error)

	// ListMonitorsByAgentEnvironmentFunc mocks the ListMonitorsByAgentEnvironment method.
	ListMonitorsByAgentEnvironmentFunc func(orgName string, projectName string, agentName string, environmentName string) ([]models.Monitor, error)

	// ListPendingOrRunningRunsFunc mocks the ListPendingOrRunningRuns method.
	ListPendingOrRunningRunsFunc func(limit int) ([]models.MonitorRun, error)

	// RunInTransactionFunc mocks the RunInTransaction method.
	RunInTransactionFunc func(fn func(txRepo repositories.MonitorRepository) error) error

	// UpdateMonitorFunc mocks the UpdateMonitor method.
	UpdateMonitorFunc func(monitor *models.Monitor) error

	// UpdateMonitorRunFunc mocks the UpdateMonitorRun method.
	UpdateMonitorRunFunc func(run *models.MonitorRun, updates map[string]interface{}) error

	// UpdateNextRunTimeFunc mocks the UpdateNextRunTime method.
	UpdateNextRunTimeFunc func(monitorID uuid.UUID, nextRunTime *time.Time) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(tx *gorm.DB) repositories.MonitorRepository

	// calls tracks calls to the methods.
	calls struct {
		// CountMonitorRuns holds details about calls to the CountMonitorRuns method.
		CountMonitorRuns []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// CreateMonitor holds details about calls to the CreateMonitor method.
		CreateMonitor []struct {
			// Monitor is the monitor argument value.
			Monitor *models.Monitor
		}
		// CreateMonitorRun holds details about calls to the CreateMonitorRun method.
		CreateMonitorRun []struct {
			// Run is the run argument value.
			Run *models.MonitorRun
		}
		// DeleteMonitor holds details about calls to the DeleteMonitor method.
		DeleteMonitor []struct {
			// Monitor is the monitor argument value.
			Monitor *models.Monitor
		}
		// FindActiveMonitorsByEvaluatorIdentifier holds details about calls to the FindActiveMonitorsByEvaluatorIdentifier method.
		FindActiveMonitorsByEvaluatorIdentifier []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// Identifier is the identifier argument value.
			Identifier string
		}
		// GetLatestMonitorRun holds details about calls to the GetLatestMonitorRun method.
		GetLatestMonitorRun []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// GetLatestMonitorRuns holds details about calls to the GetLatestMonitorRuns method.
		GetLatestMonitorRuns []struct {
			// MonitorIDs is the monitorIDs argument value.
			MonitorIDs []uuid.UUID
		}
		// GetMonitorByID holds details about calls to the GetMonitorByID method.
		GetMonitorByID []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// GetMonitorByName holds details about calls to the GetMonitorByName method.
		GetMonitorByName []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// MonitorName is the monitorName argument value.
			MonitorName string
		}
		// GetMonitorRunByID holds details about calls to the GetMonitorRunByID method.
		GetMonitorRunByID []struct {
			// RunID is the runID argument value.
			RunID uuid.UUID
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// GetMonitorRunsByMonitorID holds details about calls to the GetMonitorRunsByMonitorID method.
		GetMonitorRunsByMonitorID []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// ListDueMonitors holds details about calls to the ListDueMonitors method.
		ListDueMonitors []struct {
			// MonitorType is the monitorType argument value.
			MonitorType string
			// DueBy is the dueBy argument value.
			DueBy time.Time
		}
		// ListMonitorRuns holds details about calls to the ListMonitorRuns method.
		ListMonitorRuns []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListMonitorsByAgent holds details about calls to the ListMonitorsByAgent method.
		ListMonitorsByAgent []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// ListMonitorsByAgentEnvironment holds details about calls to the ListMonitorsByAgentEnvironment method.
		ListMonitorsByAgentEnvironment []struct {
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// EnvironmentName is the environmentName argument value.
			EnvironmentName string
		}
		// ListPendingOrRunningRuns holds details about calls to the ListPendingOrRunningRuns method.
		ListPendingOrRunningRuns []struct {
			// Limit is the limit argument value.
			Limit int
		}
		// RunInTransaction holds details about calls to the RunInTransaction method.
		RunInTransaction []struct {
			// Fn is the fn argument value.
			Fn func(txRepo repositories.MonitorRepository) error
		}
		// UpdateMonitor holds details about calls to the UpdateMonitor method.
		UpdateMonitor []struct {
			// Monitor is the monitor argument value.
			Monitor *models.Monitor
		}
		// UpdateMonitorRun holds details about calls to the UpdateMonitorRun method.
		UpdateMonitorRun []struct {
			// Run is the run argument value.
			Run *models.MonitorRun
			// Updates is the updates argument value.
			Updates map[string]interface{}
		}
		// UpdateNextRunTime holds details about calls to the UpdateNextRunTime method.
		UpdateNextRunTime []struct {
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
			// NextRunTime is the nextRunTime argument value.
			NextRunTime *time.Time
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Tx is the tx argument value.
			Tx *gorm.DB
		}
	}
	lockCountMonitorRuns                        sync.RWMutex
	lockCreateMonitor                           sync.RWMutex
	lockCreateMonitorRun                        sync.RWMutex
	lockDeleteMonitor                           sync.RWMutex
	lockFindActiveMonitorsByEvaluatorIdentifier sync.RWMutex
	lockGetLatestMonitorRun                     sync.RWMutex
	lockGetLatestMonitorRuns                    sync.RWMutex
	lockGetMonitorByID                          sync.RWMutex
	lockGetMonitorByName                        sync.RWMutex
	lockGetMonitorRunByID                       sync.RWMutex
	lockGetMonitorRunsByMonitorID               sync.RWMutex
	lockListDueMonitors                         sync.RWMutex
	lockListMonitorRuns                         sync.RWMutex
	lockListMonitorsByAgent                     sync.RWMutex
	lockListMonitorsByAgentEnvironment          sync.RWMutex
	lockListPendingOrRunningRuns                sync.RWMutex
	lockRunInTransaction                        sync.RWMutex
	lockUpdateMonitor                           sync.RWMutex
	lockUpdateMonitorRun                        sync.RWMutex
	lockUpdateNextRunTime                       sync.RWMutex
	lockWithTx                                  sync.RWMutex
}

// CountMonitorRuns calls CountMonitorRunsFunc.
func (mock *MonitorRepositoryMock) CountMonitorRuns(monitorID uuid.UUID) (int64, error) {
	if mock.CountMonitorRunsFunc == nil {
		panic("MonitorRepositoryMock.CountMonitorRunsFunc: method is nil but MonitorRepository.CountMonitorRuns was just called")
	}
	callInfo := struct {
		MonitorID uuid.UUID
	}{
		MonitorID: monitorID,
	}
	mock.lockCountMonitorRuns.Lock()
	mock.calls.CountMonitorRuns = append(mock.calls.CountMonitorRuns, callInfo)
	mock.lockCountMonitorRuns.Unlock()
	return mock.CountMonitorRunsFunc(monitorID)
}

// CountMonitorRunsCalls gets all the calls that were made to CountMonitorRuns.
// Check the length with:
//
//	len(mockedMonitorRepository.CountMonitorRunsCalls())
func (mock *MonitorRepositoryMock) CountMonitorRunsCalls() []struct {
	MonitorID uuid.UUID
} {
	var calls []struct {
		MonitorID uuid.UUID
	}
	mock.lockCountMonitorRuns.RLock()
	calls = mock.calls.CountMonitorRuns
	mock.lockCountMonitorRuns.RUnlock()
	return calls
}

// CreateMonitor calls CreateMonitorFunc.
func (mock *MonitorRepositoryMock) CreateMonitor(monitor *models.Monitor) error {
	if mock.CreateMonitorFunc == nil {
		panic("MonitorRepositoryMock.CreateMonitorFunc: method is nil but MonitorRepository.CreateMonitor was just called")
	}
	callInfo := struct {
		Monitor *models.Monitor
	}{
		Monitor: monitor,
	}
	mock.lockCreateMonitor.Lock()
	mock.calls.CreateMonitor = append(mock.calls.CreateMonitor, callInfo)
	mock.lockCreateMonitor.Unlock()
	return mock.CreateMonitorFunc(monitor)
}

// CreateMonitorCalls gets all the calls that were made to CreateMonitor.
// Check the length with:
//
//	len(mockedMonitorRepository.CreateMonitorCalls())
func (mock *MonitorRepositoryMock) CreateMonitorCalls() []struct {
	Monitor *models.Monitor
} {
	var calls []struct {
		Monitor *models.Monitor
	}
	mock.lockCreateMonitor.RLock()
	calls = mock.calls.CreateMonitor
	mock.lockCreateMonitor.RUnlock()
	return calls
}

// CreateMonitorRun calls CreateMonitorRunFunc.
func (mock *MonitorRepositoryMock) CreateMonitorRun(run *models.MonitorRun) error {
	if mock.CreateMonitorRunFunc == nil {
		panic("MonitorRepositoryMock.CreateMonitorRunFunc: method is nil but MonitorRepository.CreateMonitorRun was just called")
	}
	callInfo := struct {
		Run *models.MonitorRun
	}{
		Run: run,
	}
	mock.lockCreateMonitorRun.Lock()
	mock.calls.CreateMonitorRun = append(mock.calls.CreateMonitorRun, callInfo)
	mock.lockCreateMonitorRun.Unlock()
	return mock.CreateMonitorRunFunc(run)
}

// CreateMonitorRunCalls gets all the calls that were made to CreateMonitorRun.
// Check the length with:
//
//	len(mockedMonitorRepository.CreateMonitorRunCalls())
func (mock *MonitorRepositoryMock) CreateMonitorRunCalls() []struct {
	Run *models.MonitorRun
} {
	var calls []struct {
		Run *models.MonitorRun
	}
	mock.lockCreateMonitorRun.RLock()
	calls = mock.calls.CreateMonitorRun
	mock.lockCreateMonitorRun.RUnlock()
	return calls
}

// DeleteMonitor calls DeleteMonitorFunc.
func (mock *MonitorRepositoryMock) DeleteMonitor(monitor *models.Monitor) error {
	if mock.DeleteMonitorFunc == nil {
		panic("MonitorRepositoryMock.DeleteMonitorFunc: method is nil but MonitorRepository.DeleteMonitor was just called")
	}
	callInfo := struct {
		Monitor *models.Monitor
	}{
		Monitor: monitor,
	}
	mock.lockDeleteMonitor.Lock()
	mock.calls.DeleteMonitor = append(mock.calls.DeleteMonitor, callInfo)
	mock.lockDeleteMonitor.Unlock()
	return mock.DeleteMonitorFunc(monitor)
}

// DeleteMonitorCalls gets all the calls that were made to DeleteMonitor.
// Check the length with:
//
//	len(mockedMonitorRepository.DeleteMonitorCalls())
func (mock *MonitorRepositoryMock) DeleteMonitorCalls() []struct {
	Monitor *models.Monitor
} {
	var calls []struct {
		Monitor *models.Monitor
	}
	mock.lockDeleteMonitor.RLock()
	calls = mock.calls.DeleteMonitor
	mock.lockDeleteMonitor.RUnlock()
	return calls
}

// FindActiveMonitorsByEvaluatorIdentifier calls FindActiveMonitorsByEvaluatorIdentifierFunc.
func (mock *MonitorRepositoryMock) FindActiveMonitorsByEvaluatorIdentifier(orgName string, identifier string) ([]models.Monitor, error) {
	if mock.FindActiveMonitorsByEvaluatorIdentifierFunc == nil {
		panic("MonitorRepositoryMock.FindActiveMonitorsByEvaluatorIdentifierFunc: method is nil but MonitorRepository.FindActiveMonitorsByEvaluatorIdentifier was just called")
	}
	callInfo := struct {
		OrgName    string
		Identifier string
	}{
		OrgName:    orgName,
		Identifier: identifier,
	}
	mock.lockFindActiveMonitorsByEvaluatorIdentifier.Lock()
	mock.calls.FindActiveMonitorsByEvaluatorIdentifier = append(mock.calls.FindActiveMonitorsByEvaluatorIdentifier, callInfo)
	mock.lockFindActiveMonitorsByEvaluatorIdentifier.Unlock()
	return mock.FindActiveMonitorsByEvaluatorIdentifierFunc(orgName, identifier)
}

// FindActiveMonitorsByEvaluatorIdentifierCalls gets all the calls that were made to FindActiveMonitorsByEvaluatorIdentifier.
// Check the length with:
//
//	len(mockedMonitorRepository.FindActiveMonitorsByEvaluatorIdentifierCalls())
func (mock *MonitorRepositoryMock) FindActiveMonitorsByEvaluatorIdentifierCalls() []struct {
	OrgName    string
	Identifier string
} {
	var calls []struct {
		OrgName    string
		Identifier string
	}
	mock.lockFindActiveMonitorsByEvaluatorIdentifier.RLock()
	calls = mock.calls.FindActiveMonitorsByEvaluatorIdentifier
	mock.lockFindActiveMonitorsByEvaluatorIdentifier.RUnlock()
	return calls
}

// GetLatestMonitorRun calls GetLatestMonitorRunFunc.
func (mock *MonitorRepositoryMock) GetLatestMonitorRun(monitorID uuid.UUID) (*models.MonitorRun, error) {
	if mock.GetLatestMonitorRunFunc == nil {
		panic("MonitorRepositoryMock.GetLatestMonitorRunFunc: method is nil but MonitorRepository.GetLatestMonitorRun was just called")
	}
	callInfo := struct {
		MonitorID uuid.UUID
	}{
		MonitorID: monitorID,
	}
	mock.lockGetLatestMonitorRun.Lock()
	mock.calls.GetLatestMonitorRun = append(mock.calls.GetLatestMonitorRun, callInfo)
	mock.lockGetLatestMonitorRun.Unlock()
	return mock.GetLatestMonitorRunFunc(monitorID)
}

// GetLatestMonitorRunCalls gets all the calls that were made to GetLatestMonitorRun.
// Check the length with:
//
//	len(mockedMonitorRepository.GetLatestMonitorRunCalls())
func (mock *MonitorRepositoryMock) GetLatestMonitorRunCalls() []struct {
	MonitorID uuid.UUID
} {
	var calls []struct {
		MonitorID uuid.UUID
	}
	mock.lockGetLatestMonitorRun.RLock()
	calls = mock.calls.GetLatestMonitorRun
	mock.lockGetLatestMonitorRun.RUnlock()
	return calls
}

// GetLatestMonitorRuns calls GetLatestMonitorRunsFunc.
func (mock *MonitorRepositoryMock) GetLatestMonitorRuns(monitorIDs []uuid.UUID) (map[uuid.UUID]models.MonitorRun, error) {
	if mock.GetLatestMonitorRunsFunc == nil {
		panic("MonitorRepositoryMock.GetLatestMonitorRunsFunc: method is nil but MonitorRepository.GetLatestMonitorRuns was just called")
	}
	callInfo := struct {
		MonitorIDs []uuid.UUID
	}{
		MonitorIDs: monitorIDs,
	}
	mock.lockGetLatestMonitorRuns.Lock()
	mock.calls.GetLatestMonitorRuns = append(mock.calls.GetLatestMonitorRuns, callInfo)
	mock.lockGetLatestMonitorRuns.Unlock()
	return mock.GetLatestMonitorRunsFunc(monitorIDs)
}

// GetLatestMonitorRunsCalls gets all the calls that were made to GetLatestMonitorRuns.
// Check the length with:
//
//	len(mockedMonitorRepository.GetLatestMonitorRunsCalls())
func (mock *MonitorRepositoryMock) GetLatestMonitorRunsCalls() []struct {
	MonitorIDs []uuid.UUID
} {
	var calls []struct {
		MonitorIDs []uuid.UUID
	}
	mock.lockGetLatestMonitorRuns.RLock()
	calls = mock.calls.GetLatestMonitorRuns
	mock.lockGetLatestMonitorRuns.RUnlock()
	return calls
}

// GetMonitorByID calls GetMonitorByIDFunc.
func (mock *MonitorRepositoryMock) GetMonitorByID(monitorID uuid.UUID) (*models.Monitor, error) {
	if mock.GetMonitorByIDFunc == nil {
		panic("MonitorRepositoryMock.GetMonitorByIDFunc: method is nil but MonitorRepository.GetMonitorByID was just called")
	}
	callInfo := struct {
		MonitorID uuid.UUID
	}{
		MonitorID: monitorID,
	}
	mock.lockGetMonitorByID.Lock()
	mock.calls.GetMonitorByID = append(mock.calls.GetMonitorByID, callInfo)
	mock.lockGetMonitorByID.Unlock()
	return mock.GetMonitorByIDFunc(monitorID)
}

// GetMonitorByIDCalls gets all the calls that were made to GetMonitorByID.
// Check the length with:
//
//	len(mockedMonitorRepository.GetMonitorByIDCalls())
func (mock *MonitorRepositoryMock) GetMonitorByIDCalls() []struct {
	MonitorID uuid.UUID
} {
	var calls []struct {
		MonitorID uuid.UUID
	}
	mock.lockGetMonitorByID.RLock()
	calls = mock.calls.GetMonitorByID
	mock.lockGetMonitorByID.RUnlock()
	return calls
}

// GetMonitorByName calls GetMonitorByNameFunc.
func (mock *MonitorRepositoryMock) GetMonitorByName(orgName string, projectName string, agentName string, monitorName string) (*models.Monitor, error) {
	if mock.GetMonitorByNameFunc == nil {
		panic("MonitorRepositoryMock.GetMonitorByNameFunc: method is nil but MonitorRepository.GetMonitorByName was just called")
	}
	callInfo := struct {
		OrgName     string
		ProjectName string
		AgentName   string
		MonitorName string
	}{
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
		MonitorName: monitorName,
	}
	mock.lockGetMonitorByName.Lock()
	mock.calls.GetMonitorByName = append(mock.calls.GetMonitorByName, callInfo)
	mock.lockGetMonitorByName.Unlock()
	return mock.GetMonitorByNameFunc(orgName, projectName, agentName, monitorName)
}

// GetMonitorByNameCalls gets all the calls that were made to GetMonitorByName.
// Check the length with:
//
//	len(mockedMonitorRepository.GetMonitorByNameCalls())
func (mock *MonitorRepositoryMock) GetMonitorByNameCalls() []struct {
	OrgName     string
	ProjectName string
	AgentName   string
	MonitorName string
} {
	var calls []struct {
		OrgName     string
		ProjectName string
		AgentName   string
		MonitorName string
	}
	mock.lockGetMonitorByName.RLock()
	calls = mock.calls.GetMonitorByName
	mock.lockGetMonitorByName.RUnlock()
	return calls
}

// GetMonitorRunByID calls GetMonitorRunByIDFunc.
func (mock *MonitorRepositoryMock) GetMonitorRunByID(runID uuid.UUID, monitorID uuid.UUID) (*models.MonitorRun, error) {
	if mock.GetMonitorRunByIDFunc == nil {
		panic("MonitorRepositoryMock.GetMonitorRunByIDFunc: method is nil but MonitorRepository.GetMonitorRunByID was just called")
	}
	callInfo := struct {
		RunID     uuid.UUID
		MonitorID uuid.UUID
	}{
		RunID:     runID,
		MonitorID: monitorID,
	}
	mock.lockGetMonitorRunByID.Lock()
	mock.calls.GetMonitorRunByID = append(mock.calls.GetMonitorRunByID, callInfo)
	mock.lockGetMonitorRunByID.Unlock()
	return mock.GetMonitorRunByIDFunc(runID, monitorID)
}

// GetMonitorRunByIDCalls gets all the calls that were made to GetMonitorRunByID.
// Check the length with:
//
//	len(mockedMonitorRepository.GetMonitorRunByIDCalls())
func (mock *MonitorRepositoryMock) GetMonitorRunByIDCalls() []struct {
	RunID     uuid.UUID
	MonitorID uuid.UUID
} {
	var calls []struct {
		RunID     uuid.UUID
		MonitorID uuid.UUID
	}
	mock.lockGetMonitorRunByID.RLock()
	calls = mock.calls.GetMonitorRunByID
	mock.lockGetMonitorRunByID.RUnlock()
	return calls
}

// GetMonitorRunsByMonitorID calls GetMonitorRunsByMonitorIDFunc.
func (mock *MonitorRepositoryMock) GetMonitorRunsByMonitorID(monitorID uuid.UUID) ([]models.MonitorRun, error) {
	if mock.GetMonitorRunsByMonitorIDFunc == nil {
		panic("MonitorRepositoryMock.GetMonitorRunsByMonitorIDFunc: method is nil but MonitorRepository.GetMonitorRunsByMonitorID was just called")
	}
	callInfo := struct {
		MonitorID uuid.UUID
	}{
		MonitorID: monitorID,
	}
	mock.lockGetMonitorRunsByMonitorID.Lock()
	mock.calls.GetMonitorRunsByMonitorID = append(mock.calls.GetMonitorRunsByMonitorID, callInfo)
	mock.lockGetMonitorRunsByMonitorID.Unlock()
	return mock.GetMonitorRunsByMonitorIDFunc(monitorID)
}

// GetMonitorRunsByMonitorIDCalls gets all the calls that were made to GetMonitorRunsByMonitorID.
// Check the length with:
//
//	len(mockedMonitorRepository.GetMonitorRunsByMonitorIDCalls())
func (mock *MonitorRepositoryMock) GetMonitorRunsByMonitorIDCalls() []struct {
	MonitorID uuid.UUID
} {
	var calls []struct {
		MonitorID uuid.UUID
	}
	mock.lockGetMonitorRunsByMonitorID.RLock()
	calls = mock.calls.GetMonitorRunsByMonitorID
	mock.lockGetMonitorRunsByMonitorID.RUnlock()
	return calls
}

// ListDueMonitors calls ListDueMonitorsFunc.
func (mock *MonitorRepositoryMock) ListDueMonitors(monitorType string, dueBy time.Time) ([]models.Monitor, error) {
	if mock.ListDueMonitorsFunc == nil {
		panic("MonitorRepositoryMock.ListDueMonitorsFunc: method is nil but MonitorRepository.ListDueMonitors was just called")
	}
	callInfo := struct {
		MonitorType string
		DueBy       time.Time
	}{
		MonitorType: monitorType,
		DueBy:       dueBy,
	}
	mock.lockListDueMonitors.Lock()
	mock.calls.ListDueMonitors = append(mock.calls.ListDueMonitors, callInfo)
	mock.lockListDueMonitors.Unlock()
	return mock.ListDueMonitorsFunc(monitorType, dueBy)
}

// ListDueMonitorsCalls gets all the calls that were made to ListDueMonitors.
// Check the length with:
//
//	len(mockedMonitorRepository.ListDueMonitorsCalls())
func (mock *MonitorRepositoryMock) ListDueMonitorsCalls() []struct {
	MonitorType string
	DueBy       time.Time
} {
	var calls []struct {
		MonitorType string
		DueBy       time.Time
	}
	mock.lockListDueMonitors.RLock()
	calls = mock.calls.ListDueMonitors
	mock.lockListDueMonitors.RUnlock()
	return calls
}

// ListMonitorRuns calls ListMonitorRunsFunc.
func (mock *MonitorRepositoryMock) ListMonitorRuns(monitorID uuid.UUID, limit int, offset int) ([]models.MonitorRun, error) {
	if mock.ListMonitorRunsFunc == nil {
		panic("MonitorRepositoryMock.ListMonitorRunsFunc: method is nil but MonitorRepository.ListMonitorRuns was just called")
	}
	callInfo := struct {
		MonitorID uuid.UUID
		Limit     int
		Offset    int
	}{
		MonitorID: monitorID,
		Limit:     limit,
		Offset:    offset,
	}
	mock.lockListMonitorRuns.Lock()
	mock.calls.ListMonitorRuns = append(mock.calls.ListMonitorRuns, callInfo)
	mock.lockListMonitorRuns.Unlock()
	return mock.ListMonitorRunsFunc(monitorID, limit, offset)
}

// ListMonitorRunsCalls gets all the calls that were made to ListMonitorRuns.
// Check the length with:
//
//	len(mockedMonitorRepository.ListMonitorRunsCalls())
func (mock *MonitorRepositoryMock) ListMonitorRunsCalls() []struct {
	MonitorID uuid.UUID
	Limit     int
	Offset    int
} {
	var calls []struct {
		MonitorID uuid.UUID
		Limit     int
		Offset    int
	}
	mock.lockListMonitorRuns.RLock()
	calls = mock.calls.ListMonitorRuns
	mock.lockListMonitorRuns.RUnlock()
	return calls
}

// ListMonitorsByAgent calls ListMonitorsByAgentFunc.
func (mock *MonitorRepositoryMock) ListMonitorsByAgent(orgName string, projectName string, agentName string) ([]models.Monitor, error) {
	if mock.ListMonitorsByAgentFunc == nil {
		panic("MonitorRepositoryMock.ListMonitorsByAgentFunc: method is nil but MonitorRepository.ListMonitorsByAgent was just called")
	}
	callInfo := struct {
		OrgName     string
		ProjectName string
		AgentName   string
	}{
		OrgName:     orgName,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockListMonitorsByAgent.Lock()
	mock.calls.ListMonitorsByAgent = append(mock.calls.ListMonitorsByAgent, callInfo)
	mock.lockListMonitorsByAgent.Unlock()
	return mock.ListMonitorsByAgentFunc(orgName, projectName, agentName)
}

// ListMonitorsByAgentCalls gets all the calls that were made to ListMonitorsByAgent.
// Check the length with:
//
//	len(mockedMonitorRepository.ListMonitorsByAgentCalls())
func (mock *MonitorRepositoryMock) ListMonitorsByAgentCalls() []struct {
	OrgName     string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		OrgName     string
		ProjectName string
		AgentName   string
	}
	mock.lockListMonitorsByAgent.RLock()
	calls = mock.calls.ListMonitorsByAgent
	mock.lockListMonitorsByAgent.RUnlock()
	return calls
}

// ListMonitorsByAgentEnvironment calls ListMonitorsByAgentEnvironmentFunc.
func (mock *MonitorRepositoryMock) ListMonitorsByAgentEnvironment(orgName string, projectName string, agentName string, environmentName string) ([]models.Monitor, error) {
	if mock.ListMonitorsByAgentEnvironmentFunc == nil {
		panic("MonitorRepositoryMock.ListMonitorsByAgentEnvironmentFunc: method is nil but MonitorRepository.ListMonitorsByAgentEnvironment was just called")
	}
	callInfo := struct {
		OrgName         string
		ProjectName     string
		AgentName       string
		EnvironmentName string
	}{
		OrgName:         orgName,
		ProjectName:     projectName,
		AgentName:       agentName,
		EnvironmentName: environmentName,
	}
	mock.lockListMonitorsByAgentEnvironment.Lock()
	mock.calls.ListMonitorsByAgentEnvironment = append(mock.calls.ListMonitorsByAgentEnvironment, callInfo)
	mock.lockListMonitorsByAgentEnvironment.Unlock()
	return mock.ListMonitorsByAgentEnvironmentFunc(orgName, projectName, agentName, environmentName)
}

// ListMonitorsByAgentEnvironmentCalls gets all the calls that were made to ListMonitorsByAgentEnvironment.
// Check the length with:
//
//	len(mockedMonitorRepository.ListMonitorsByAgentEnvironmentCalls())
func (mock *MonitorRepositoryMock) ListMonitorsByAgentEnvironmentCalls() []struct {
	OrgName         string
	ProjectName     string
	AgentName       string
	EnvironmentName string
} {
	var calls []struct {
		OrgName         string
		ProjectName     string
		AgentName       string
		EnvironmentName string
	}
	mock.lockListMonitorsByAgentEnvironment.RLock()
	calls = mock.calls.ListMonitorsByAgentEnvironment
	mock.lockListMonitorsByAgentEnvironment.RUnlock()
	return calls
}

// ListPendingOrRunningRuns calls ListPendingOrRunningRunsFunc.
func (mock *MonitorRepositoryMock) ListPendingOrRunningRuns(limit int) ([]models.MonitorRun, error) {
	if mock.ListPendingOrRunningRunsFunc == nil {
		panic("MonitorRepositoryMock.ListPendingOrRunningRunsFunc: method is nil but MonitorRepository.ListPendingOrRunningRuns was just called")
	}
	callInfo := struct {
		Limit int
	}{
		Limit: limit,
	}
	mock.lockListPendingOrRunningRuns.Lock()
	mock.calls.ListPendingOrRunningRuns = append(mock.calls.ListPendingOrRunningRuns, callInfo)
	mock.lockListPendingOrRunningRuns.Unlock()
	return mock.ListPendingOrRunningRunsFunc(limit)
}

// ListPendingOrRunningRunsCalls gets all the calls that were made to ListPendingOrRunningRuns.
// Check the length with:
//
//	len(mockedMonitorRepository.ListPendingOrRunningRunsCalls())
func (mock *MonitorRepositoryMock) ListPendingOrRunningRunsCalls() []struct {
	Limit int
} {
	var calls []struct {
		Limit int
	}
	mock.lockListPendingOrRunningRuns.RLock()
	calls = mock.calls.ListPendingOrRunningRuns
	mock.lockListPendingOrRunningRuns.RUnlock()
	return calls
}

// RunInTransaction calls RunInTransactionFunc.
func (mock *MonitorRepositoryMock) RunInTransaction(fn func(txRepo repositories.MonitorRepository) error) error {
	if mock.RunInTransactionFunc == nil {
		panic("MonitorRepositoryMock.RunInTransactionFunc: method is nil but MonitorRepository.RunInTransaction was just called")
	}
	callInfo := struct {
		Fn func(txRepo repositories.MonitorRepository) error
	}{
		Fn: fn,
	}
	mock.lockRunInTransaction.Lock()
	mock.calls.RunInTransaction = append(mock.calls.RunInTransaction, callInfo)
	mock.lockRunInTransaction.Unlock()
	return mock.RunInTransactionFunc(fn)
}

// RunInTransactionCalls gets all the calls that were made to RunInTransaction.
// Check the length with:
//
//	len(mockedMonitorRepository.RunInTransactionCalls())
func (mock *MonitorRepositoryMock) RunInTransactionCalls() []struct {
	Fn func(txRepo repositories.MonitorRepository) error
} {
	var calls []struct {
		Fn func(txRepo repositories.MonitorRepository) error
	}
	mock.lockRunInTransaction.RLock()
	calls = mock.calls.RunInTransaction
	mock.lockRunInTransaction.RUnlock()
	return calls
}

// UpdateMonitor calls UpdateMonitorFunc.
func (mock *MonitorRepositoryMock) UpdateMonitor(monitor *models.Monitor) error {
	if mock.UpdateMonitorFunc == nil {
		panic("MonitorRepositoryMock.UpdateMonitorFunc: method is nil but MonitorRepository.UpdateMonitor was just called")
	}
	callInfo := struct {
		Monitor *models.Monitor
	}{
		Monitor: monitor,
	}
	mock.lockUpdateMonitor.Lock()
	mock.calls.UpdateMonitor = append(mock.calls.UpdateMonitor, callInfo)
	mock.lockUpdateMonitor.Unlock()
	return mock.UpdateMonitorFunc(monitor)
}

// UpdateMonitorCalls gets all the calls that were made to UpdateMonitor.
// Check the length with:
//
//	len(mockedMonitorRepository.UpdateMonitorCalls())
func (mock *MonitorRepositoryMock) UpdateMonitorCalls() []struct {
	Monitor *models.Monitor
} {
	var calls []struct {
		Monitor *models.Monitor
	}
	mock.lockUpdateMonitor.RLock()
	calls = mock.calls.UpdateMonitor
	mock.lockUpdateMonitor.RUnlock()
	return calls
}

// UpdateMonitorRun calls UpdateMonitorRunFunc.
func (mock *MonitorRepositoryMock) UpdateMonitorRun(run *models.MonitorRun, updates map[string]interface{}) error {
	if mock.UpdateMonitorRunFunc == nil {
		panic("MonitorRepositoryMock.UpdateMonitorRunFunc: method is nil but MonitorRepository.UpdateMonitorRun was just called")
	}
	callInfo := struct {
		Run     *models.MonitorRun
		Updates map[string]interface{}
	}{
		Run:     run,
		Updates: updates,
	}
	mock.lockUpdateMonitorRun.Lock()
	mock.calls.UpdateMonitorRun = append(mock.calls.UpdateMonitorRun, callInfo)
	mock.lockUpdateMonitorRun.Unlock()
	return mock.UpdateMonitorRunFunc(run, updates)
}

// UpdateMonitorRunCalls gets all the calls that were made to UpdateMonitorRun.
// Check the length with:
//
//	len(mockedMonitorRepository.UpdateMonitorRunCalls())
func (mock *MonitorRepositoryMock) UpdateMonitorRunCalls() []struct {
	Run     *models.MonitorRun
	Updates map[string]interface{}
} {
	var calls []struct {
		Run     *models.MonitorRun
		Updates map[string]interface{}
	}
	mock.lockUpdateMonitorRun.RLock()
	calls = mock.calls.UpdateMonitorRun
	mock.lockUpdateMonitorRun.RUnlock()
	return calls
}

// UpdateNextRunTime calls UpdateNextRunTimeFunc.
func (mock *MonitorRepositoryMock) UpdateNextRunTime(monitorID uuid.UUID, nextRunTime *time.Time) error {
	if mock.UpdateNextRunTimeFunc == nil {
		panic("MonitorRepositoryMock.UpdateNextRunTimeFunc: method is nil but MonitorRepository.UpdateNextRunTime was just called")
	}
	callInfo := struct {
		MonitorID   uuid.UUID
		NextRunTime *time.Time
	}{
		MonitorID:   monitorID,
		NextRunTime: nextRunTime,
	}
	mock.lockUpdateNextRunTime.Lock()
	mock.calls.UpdateNextRunTime = append(mock.calls.UpdateNextRunTime, callInfo)
	mock.lockUpdateNextRunTime.Unlock()
	return mock.UpdateNextRunTimeFunc(monitorID, nextRunTime)
}

// UpdateNextRunTimeCalls gets all the calls that were made to UpdateNextRunTime.
// Check the length with:
//
//	len(mockedMonitorRepository.UpdateNextRunTimeCalls())
func (mock *MonitorRepositoryMock) UpdateNextRunTimeCalls() []struct {
	MonitorID   uuid.UUID
	NextRunTime *time.Time
} {
	var calls []struct {
		MonitorID   uuid.UUID
		NextRunTime *time.Time
	}
	mock.lockUpdateNextRunTime.RLock()
	calls = mock.calls.UpdateNextRunTime
	mock.lockUpdateNextRunTime.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *MonitorRepositoryMock) WithTx(tx *gorm.DB) repositories.MonitorRepository {
	if mock.WithTxFunc == nil {
		panic("MonitorRepositoryMock.WithTxFunc: method is nil but MonitorRepository.WithTx was just called")
	}
	callInfo := struct {
		Tx *gorm.DB
	}{
		Tx: tx,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(tx)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedMonitorRepository.WithTxCalls())
func (mock *MonitorRepositoryMock) WithTxCalls() []struct {
	Tx *gorm.DB
} {
	var calls []struct {
		Tx *gorm.DB
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
