// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
	"gorm.io/gorm"
)

// MonitorLLMMappingRepositoryMock is a mock implementation of repositories.MonitorLLMMappingRepository.
//
//	func TestSomethingThatUsesMonitorLLMMappingRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.MonitorLLMMappingRepository
//		mockedMonitorLLMMappingRepository := &MonitorLLMMappingRepositoryMock{
//			CreateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error {
//				panic("mock out the Create method")
//			},
//			DeleteByMonitorIDFunc: func(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID) error {
//				panic("mock out the DeleteByMonitorID method")
//			},
//			DeleteByMonitorIDAndProxyUUIDFunc: func(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID, proxyUUID uuid.UUID) error {
//				panic("mock out the DeleteByMonitorIDAndProxyUUID method")
//			},
//			ListByMonitorIDFunc: func(ctx context.Context, monitorID uuid.UUID) ([]models.MonitorLLMMapping, error) {
//				panic("mock out the ListByMonitorID method")
//			},
//			UpdateFunc: func(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedMonitorLLMMappingRepository in code that requires repositories.MonitorLLMMappingRepository
//		// and then make assertions.
//
//	}
type MonitorLLMMappingRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error

	// DeleteByMonitorIDFunc mocks the DeleteByMonitorID method.
	DeleteByMonitorIDFunc func(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID) error

	// DeleteByMonitorIDAndProxyUUIDFunc mocks the DeleteByMonitorIDAndProxyUUID method.
	DeleteByMonitorIDAndProxyUUIDFunc func(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID, proxyUUID uuid.UUID) error

	// ListByMonitorIDFunc mocks the ListByMonitorID method.
	ListByMonitorIDFunc func(ctx context.Context, monitorID uuid.UUID) ([]models.MonitorLLMMapping, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.MonitorLLMMapping
		}
		// DeleteByMonitorID holds details about calls to the DeleteByMonitorID method.
		DeleteByMonitorID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// DeleteByMonitorIDAndProxyUUID holds details about calls to the DeleteByMonitorIDAndProxyUUID method.
		DeleteByMonitorIDAndProxyUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
			// ProxyUUID is the proxyUUID argument value.
			ProxyUUID uuid.UUID
		}
		// ListByMonitorID holds details about calls to the ListByMonitorID method.
		ListByMonitorID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MonitorID is the monitorID argument value.
			MonitorID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *gorm.DB
			// Mapping is the mapping argument value.
			Mapping *models.MonitorLLMMapping
		}
	}
	lockCreate                        sync.RWMutex
	lockDeleteByMonitorID             sync.RWMutex
	lockDeleteByMonitorIDAndProxyUUID sync.RWMutex
	lockListByMonitorID               sync.RWMutex
	lockUpdate                        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MonitorLLMMappingRepositoryMock) Create(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error {
	if mock.CreateFunc == nil {
		panic("MonitorLLMMappingRepositoryMock.CreateFunc: method is nil but MonitorLLMMappingRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.MonitorLLMMapping
	}{
		Ctx:     ctx,
		Tx:      tx,
		Mapping: mapping,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, tx, mapping)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedMonitorLLMMappingRepository.CreateCalls())
func (mock *MonitorLLMMappingRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Mapping *models.MonitorLLMMapping
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.MonitorLLMMapping
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByMonitorID calls DeleteByMonitorIDFunc.
func (mock *MonitorLLMMappingRepositoryMock) DeleteByMonitorID(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID) error {
	if mock.DeleteByMonitorIDFunc == nil {
		panic("MonitorLLMMappingRepositoryMock.DeleteByMonitorIDFunc: method is nil but MonitorLLMMappingRepository.DeleteByMonitorID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MonitorID uuid.UUID
	}{
		Ctx:       ctx,
		Tx:        tx,
		MonitorID: monitorID,
	}
	mock.lockDeleteByMonitorID.Lock()
	mock.calls.DeleteByMonitorID = append(mock.calls.DeleteByMonitorID, callInfo)
	mock.lockDeleteByMonitorID.Unlock()
	return mock.DeleteByMonitorIDFunc(ctx, tx, monitorID)
}

// DeleteByMonitorIDCalls gets all the calls that were made to DeleteByMonitorID.
// Check the length with:
//
//	len(mockedMonitorLLMMappingRepository.DeleteByMonitorIDCalls())
func (mock *MonitorLLMMappingRepositoryMock) DeleteByMonitorIDCalls() []struct {
	Ctx       context.Context
	Tx        *gorm.DB
	MonitorID uuid.UUID
} {
	var calls []struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MonitorID uuid.UUID
	}
	mock.lockDeleteByMonitorID.RLock()
	calls = mock.calls.DeleteByMonitorID
	mock.lockDeleteByMonitorID.RUnlock()
	return calls
}

// DeleteByMonitorIDAndProxyUUID calls DeleteByMonitorIDAndProxyUUIDFunc.
func (mock *MonitorLLMMappingRepositoryMock) DeleteByMonitorIDAndProxyUUID(ctx context.Context, tx *gorm.DB, monitorID uuid.UUID, proxyUUID uuid.UUID) error {
	if mock.DeleteByMonitorIDAndProxyUUIDFunc == nil {
		panic("MonitorLLMMappingRepositoryMock.DeleteByMonitorIDAndProxyUUIDFunc: method is nil but MonitorLLMMappingRepository.DeleteByMonitorIDAndProxyUUID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MonitorID uuid.UUID
		ProxyUUID uuid.UUID
	}{
		Ctx:       ctx,
		Tx:        tx,
		MonitorID: monitorID,
		ProxyUUID: proxyUUID,
	}
	mock.lockDeleteByMonitorIDAndProxyUUID.Lock()
	mock.calls.DeleteByMonitorIDAndProxyUUID = append(mock.calls.DeleteByMonitorIDAndProxyUUID, callInfo)
	mock.lockDeleteByMonitorIDAndProxyUUID.Unlock()
	return mock.DeleteByMonitorIDAndProxyUUIDFunc(ctx, tx, monitorID, proxyUUID)
}

// DeleteByMonitorIDAndProxyUUIDCalls gets all the calls that were made to DeleteByMonitorIDAndProxyUUID.
// Check the length with:
//
//	len(mockedMonitorLLMMappingRepository.DeleteByMonitorIDAndProxyUUIDCalls())
func (mock *MonitorLLMMappingRepositoryMock) DeleteByMonitorIDAndProxyUUIDCalls() []struct {
	Ctx       context.Context
	Tx        *gorm.DB
	MonitorID uuid.UUID
	ProxyUUID uuid.UUID
} {
	var calls []struct {
		Ctx       context.Context
		Tx        *gorm.DB
		MonitorID uuid.UUID
		ProxyUUID uuid.UUID
	}
	mock.lockDeleteByMonitorIDAndProxyUUID.RLock()
	calls = mock.calls.DeleteByMonitorIDAndProxyUUID
	mock.lockDeleteByMonitorIDAndProxyUUID.RUnlock()
	return calls
}

// ListByMonitorID calls ListByMonitorIDFunc.
func (mock *MonitorLLMMappingRepositoryMock) ListByMonitorID(ctx context.Context, monitorID uuid.UUID) ([]models.MonitorLLMMapping, error) {
	if mock.ListByMonitorIDFunc == nil {
		panic("MonitorLLMMappingRepositoryMock.ListByMonitorIDFunc: method is nil but MonitorLLMMappingRepository.ListByMonitorID was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		MonitorID uuid.UUID
	}{
		Ctx:       ctx,
		MonitorID: monitorID,
	}
	mock.lockListByMonitorID.Lock()
	mock.calls.ListByMonitorID = append(mock.calls.ListByMonitorID, callInfo)
	mock.lockListByMonitorID.Unlock()
	return mock.ListByMonitorIDFunc(ctx, monitorID)
}

// ListByMonitorIDCalls gets all the calls that were made to ListByMonitorID.
// Check the length with:
//
//	len(mockedMonitorLLMMappingRepository.ListByMonitorIDCalls())
func (mock *MonitorLLMMappingRepositoryMock) ListByMonitorIDCalls() []struct {
	Ctx       context.Context
	MonitorID uuid.UUID
} {
	var calls []struct {
		Ctx       context.Context
		MonitorID uuid.UUID
	}
	mock.lockListByMonitorID.RLock()
	calls = mock.calls.ListByMonitorID
	mock.lockListByMonitorID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *MonitorLLMMappingRepositoryMock) Update(ctx context.Context, tx *gorm.DB, mapping *models.MonitorLLMMapping) error {
	if mock.UpdateFunc == nil {
		panic("MonitorLLMMappingRepositoryMock.UpdateFunc: method is nil but MonitorLLMMappingRepository.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.MonitorLLMMapping
	}{
		Ctx:     ctx,
		Tx:      tx,
		Mapping: mapping,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, tx, mapping)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedMonitorLLMMappingRepository.UpdateCalls())
func (mock *MonitorLLMMappingRepositoryMock) UpdateCalls() []struct {
	Ctx     context.Context
	Tx      *gorm.DB
	Mapping *models.MonitorLLMMapping
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *gorm.DB
		Mapping *models.MonitorLLMMapping
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
