// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// OrgPublisherCredentialRepositoryMock is a mock implementation of repositories.OrgPublisherCredentialRepository.
//
//	func TestSomethingThatUsesOrgPublisherCredentialRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.OrgPublisherCredentialRepository
//		mockedOrgPublisherCredentialRepository := &OrgPublisherCredentialRepositoryMock{
//			GetByOrgNameFunc: func(orgName string) (*models.OrgPublisherCredential, error) {
//				panic("mock out the GetByOrgName method")
//			},
//			UpsertFunc: func(cred *models.OrgPublisherCredential) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedOrgPublisherCredentialRepository in code that requires repositories.OrgPublisherCredentialRepository
//		// and then make assertions.
//
//	}
type OrgPublisherCredentialRepositoryMock struct {
	// GetByOrgNameFunc mocks the GetByOrgName method.
	GetByOrgNameFunc func(orgName string) (*models.OrgPublisherCredential, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(cred *models.OrgPublisherCredential) error

	// calls tracks calls to the methods.
	calls struct {
		// GetByOrgName holds details about calls to the GetByOrgName method.
		GetByOrgName []struct {
			// OrgName is the orgName argument value.
			OrgName string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Cred is the cred argument value.
			Cred *models.OrgPublisherCredential
		}
	}
	lockGetByOrgName sync.RWMutex
	lockUpsert       sync.RWMutex
}

// GetByOrgName calls GetByOrgNameFunc.
func (mock *OrgPublisherCredentialRepositoryMock) GetByOrgName(orgName string) (*models.OrgPublisherCredential, error) {
	if mock.GetByOrgNameFunc == nil {
		panic("OrgPublisherCredentialRepositoryMock.GetByOrgNameFunc: method is nil but OrgPublisherCredentialRepository.GetByOrgName was just called")
	}
	callInfo := struct {
		OrgName string
	}{
		OrgName: orgName,
	}
	mock.lockGetByOrgName.Lock()
	mock.calls.GetByOrgName = append(mock.calls.GetByOrgName, callInfo)
	mock.lockGetByOrgName.Unlock()
	return mock.GetByOrgNameFunc(orgName)
}

// GetByOrgNameCalls gets all the calls that were made to GetByOrgName.
// Check the length with:
//
//	len(mockedOrgPublisherCredentialRepository.GetByOrgNameCalls())
func (mock *OrgPublisherCredentialRepositoryMock) GetByOrgNameCalls() []struct {
	OrgName string
} {
	var calls []struct {
		OrgName string
	}
	mock.lockGetByOrgName.RLock()
	calls = mock.calls.GetByOrgName
	mock.lockGetByOrgName.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *OrgPublisherCredentialRepositoryMock) Upsert(cred *models.OrgPublisherCredential) error {
	if mock.UpsertFunc == nil {
		panic("OrgPublisherCredentialRepositoryMock.UpsertFunc: method is nil but OrgPublisherCredentialRepository.Upsert was just called")
	}
	callInfo := struct {
		Cred *models.OrgPublisherCredential
	}{
		Cred: cred,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(cred)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedOrgPublisherCredentialRepository.UpsertCalls())
func (mock *OrgPublisherCredentialRepositoryMock) UpsertCalls() []struct {
	Cred *models.OrgPublisherCredential
} {
	var calls []struct {
		Cred *models.OrgPublisherCredential
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
